### ISSUE TITLE
Derive Bitwidth from Tensor

### ISSUE THREAD

**Issue by nandeeka** [aws-neuron/aws-neuron-sdk#1008]
Is there a way to automatically derive the bitwidth given a type? For example, if I have a tensor `A`, I can get its type with `A.dtype`, but can I get the bitwidth of the individual elements? In Numpy, we have `itemwidth` (see [here](https://numpy.org/devdocs/reference/generated/numpy.ndarray.itemsize.html)). Thanks!

**Comment by nandeeka** [comment]
Following a comment from @aws-zhehongb, I also tried `O_DRAM.dtype.itemwidth` (following [this](https://numpy.org/doc/stable/reference/generated/numpy.dtype.itemsize.html) documentation) for some tensor `O_DRAM`. However, this also does not work. I see the error:
```
Traceback (most recent call last):
  File "/home/ubuntu/nki-kernels/out/../src/lora/direct_allocate.py", line 210, in <module>
    main()
  File "/home/ubuntu/nki-kernels/out/../src/lora/direct_allocate.py", line 207, in main
    benchmark_kernel()
  File "/home/ubuntu/nki-kernels/out/../src/lora/direct_allocate.py", line 184, in benchmark_kernel
    benchmark_func(I, PW, A, SB, O)
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 806, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.Kernel.__call__
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 867, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.call_impl
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 886, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.specialize_and_call
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 892, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.specialize_and_call
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 953, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.expand_kernel_with_ctx
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 954, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.expand_kernel_with_ctx
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 961, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.expand_kernel_with_ctx
  File "neuronxcc/starfish/penguin/targets/nki/TraceKernel.py", line 959, in neuronxcc.starfish.penguin.targets.nki.TraceKernel.TraceKernel.expand_kernel_with_ctx
  File "/home/ubuntu/nki-kernels/out/../src/lora/direct_allocate.py", line 6, in lora
    def lora(I_DRAM, PW_DRAM, A_DRAM, SB_DRAM, O_DRAM):
  File "/home/ubuntu/nki-kernels/out/../src/lora/direct_allocate.py", line 39, in lora
    do_addr = po_addr + po_blocks * N1 * N0 * O_DRAM.dtype.itemwidth
AttributeError: 'numpy.dtypes.Float16DType' object has no attribute 'itemwidth'
```
