### ISSUE TITLE
Error Benchmarking with NeuronPerf

### ISSUE THREAD

**Issue by nandeeka** [aws-neuron/aws-neuron-sdk#1040]
Following [this response](https://github.com/aws-neuron/aws-neuron-sdk/issues/1015#issuecomment-2415396727), I am trying to benchmark a PyTorch program using [this tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuronperf/neuronperf_examples.html#benchmark-a-model-from-source).

The exact example did not work (it uses `torch.neuron` instead of `torch_neuronx` and my environment did not like something about having multiple batched inputs), so I am using the code:

```python
import torch
import torch_neuronx

import neuronperf as npf
import neuronperf.torch

# Define a simple model
class Model(torch.nn.Module):
    def forward(self, x):
        x = x * 3
        return x + 1

# Instantiate
model = Model()
model.eval()

# Define some inputs
inputs = (torch.ones((1, 3, 224, 224)),)

# Compile for Neuron
model_neuron = torch_neuronx.trace(model, inputs)
model_neuron.save("model_neuron_b1.pt")

# Benchmark
reports = npf.torch.benchmark("model_neuron_b1.pt", inputs)

# View and save results
npf.print_reports(reports)
npf.write_csv(reports, "model_neuron_b1.csv")
```

However, even after my changes, I am unable to get this to run. I see the error:
```
2024-Nov-20 19:21:35.864216  2665:2666  ERROR   NRT:nrt_init                                Incompatible runtime state: NRT_STATE_CHILD
ERROR:neuronperf.benchmarking - Benchmarker 0 encountered an error during prep: 
Traceback (most recent call last):
  File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/neuronperf/benchmarking.py", line 345, in run
    self.setup()
  File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/neuronperf/benchmarking.py", line 244, in setup
    self.load()
  File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/neuronperf/benchmarking.py", line 181, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/neuronperf/torch/torch.py", line 61, in _neuron_load_fn
    model = torch.jit.load(model_filename)
  File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs. See the Neuron Runtime's troubleshooting guide for help on this
topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/
```
This seems to cause many more errors that keep printing all pointing to the fact that the "PyTorch Neuron Runtime could not be initialized". Unfortunately, I don't see a cause for my error [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-runtime/nrt-troubleshoot.html#failure-to-initialize-neuron).

I am using the DLAMI launched November 12 with `neuronperf` version `1.8.93.0+5dccae385`. Any help in debugging would be appreciated.

**Comment by fayyadd** [comment]
Thanks @nandeeka. We have reproduced the issue and are investigating.

**Comment by fayyadd** [comment]
Hi @nandeeka as a workaround can you try using PT1.13 instead of the PT2.1 AMI you used? I did not encounter this error when I tried reproducing with PT1.13

**Comment by fayyadd** [comment]
We are able to run this with the PT2.21 DLAMI by separating the tracing/saving from the benchmarking, using separate scripts for each:

tracing/saving:
```
import torch

import neuronperf as npf
import neuronperf.torch

# Define a simple model
class Model(torch.nn.Module):
    def forward(self, x):
        x = x * 3
        return x + 1

# Instantiate
model = Model()
model.eval()

# Define some inputs
inputs = (torch.ones((1, 3, 224, 224)),)

# Compile for Neuron
import torch_neuronx
model_neuron = torch_neuronx.trace(model, inputs)
model_neuron.save("model_neuron_b1.pt")
```

profiling:
```
import torch

import neuronperf as npf
import neuronperf.torch

# Define some inputs
inputs = (torch.ones((1, 3, 224, 224)),)

# Benchmark
reports = npf.torch.benchmark("model_neuron_b1.pt", inputs)

# View and save results
npf.print_reports(reports)
npf.write_csv(reports, "model_neuron_b1.csv")
```

Please let us know if this resolves your issue and if you have any further questions.

**Comment by nandeeka** [comment]
This worked. Thank you!
