### ISSUE TITLE
[NEURONX-CC Tensorizer Error] LateNeuronInstComb: Incorrect IR during Compilation

### ISSUE THREAD

**Issue by moyuanchen** [aws-neuron/aws-neuron-sdk#1070]
### Description

I am encountering an error while attempting to compile my model using torch_neuronx.trace() on AWS Trn1 instances. The compilation process fails with the following error:

[TEN404] (rng_bit_generator.10_pftranspose_25594) Internal tensorizer error: LateNeuronInstComb:Incorrect IR by <class 'neuronxcc.starfish.penguin.targets.transforms.TongaInstComb.LateNeuronInstComb'>
The error suggests that the IR is incorrect and advises opening a support ticket. Additionally, the compiler (neuronx-cc) fails with exit code 70.

The issue persists across multiple runs, and I have set the XLA_IR_DEBUG=1 and XLA_HLO_DEBUG=1 environment variables. Below are the details and relevant logs.

### Environment Details
Deep Learning AMI Neuron PyTorch 1.13 (Amazon Linux 2) 20240815

### Error log
python model_1.3_b.py 
2024-12-22 15:24:08.000779:  13717  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-12-22 15:24:08.000784:  13717  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ec2-user/neuroncc_compile_workdir/5fde167e-bcb5-4e5c-a1c3-0cd70ae3ae42/model.MODULE_13362955078774025298+d41d8cd9.hlo.pb', '--output', '/tmp/ec2-user/neuroncc_compile_workdir/5fde167e-bcb5-4e5c-a1c3-0cd70ae3ae42/model.MODULE_13362955078774025298+d41d8cd9.neff', '--verbose=35']
....
Compiler status PASS
2024-12-22 15:25:14.000088:  14189  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-12-22 15:25:14.000090:  14189  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ec2-user/neuroncc_compile_workdir/aec9e41f-8725-4faa-a1af-71ff57b47422/model.MODULE_7172654556840018934+d41d8cd9.hlo.pb', '--output', '/tmp/ec2-user/neuroncc_compile_workdir/aec9e41f-8725-4faa-a1af-71ff57b47422/model.MODULE_7172654556840018934+d41d8cd9.neff', '--verbose=35']
.
Compiler status PASS
/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:158: UserWarning: Received an input tensor that was unused. Tensor will be ignored. (index=0, shape=torch.Size([16, 32, 39, 91]), dtype=torch.float32)
  warnings.warn(
/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:158: UserWarning: Received an input tensor that was unused. Tensor will be ignored. (index=0, shape=torch.Size([16, 32, 39, 91]), dtype=torch.float32)
  warnings.warn(
..........root = neuronxcc/starfish/penguin/targets/transforms/TargetLowering.py
root = neuronxcc/starfish/penguin/targets/transforms
root = neuronxcc/starfish/penguin/targets
root = neuronxcc/starfish/penguin
root = neuronxcc/starfish

[TEN404] (rng_bit_generator.10_pftranspose_25594) Internal tensorizer error: LateNeuronInstComb:Incorrect IR by <class 'neuronxcc.starfish.penguin.targets.transforms.TongaInstComb.LateNeuronInstComb'> - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
root = neuronxcc/starfish/penguin/targets/transforms/TargetLowering.py
root = neuronxcc/starfish/penguin/targets/transforms
root = neuronxcc/starfish/penguin/targets
root = neuronxcc/starfish/penguin
root = neuronxcc/starfish

[TEN404] (rng_bit_generator.10_pftranspose_25594) Internal tensorizer error: LateNeuronInstComb:Incorrect IR by <class 'neuronxcc.starfish.penguin.targets.transforms.TongaInstComb.LateNeuronInstComb'> - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
Exception in device=TPU:1: neuronx-cc failed with 70
Traceback (most recent call last):
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 331, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 325, in _start_fn
    fn(gindex, *args)
  File "/home/ec2-user/model_1.3_b.py", line 338, in train
    model = torch_neuronx.trace(model, (example_input,))
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 574, in trace
    neff_filename, metaneff, flattener, packer, weights = _trace(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 639, in _trace
    neff_artifacts = generate_neff(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 492, in generate_neff
    neff_filename = hlo_compile(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 394, in hlo_compile
    raise RuntimeError(f"neuronx-cc failed with {status}")
RuntimeError: neuronx-cc failed with 70
Exception in device=TPU:0: neuronx-cc failed with 70
Traceback (most recent call last):
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 331, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 325, in _start_fn
    fn(gindex, *args)
  File "/home/ec2-user/model_1.3_b.py", line 338, in train
    model = torch_neuronx.trace(model, (example_input,))
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 574, in trace
    neff_filename, metaneff, flattener, packer, weights = _trace(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 639, in _trace
    neff_artifacts = generate_neff(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 492, in generate_neff
    neff_filename = hlo_compile(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 394, in hlo_compile
    raise RuntimeError(f"neuronx-cc failed with {status}")
RuntimeError: neuronx-cc failed with 70
Traceback (most recent call last):
  File "model_1.3_b.py", line 372, in <module>
    xmp.spawn(train, nprocs=2)
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 393, in spawn
    return torch.multiprocessing.start_processes(
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with exit code 17

### Request

Assistance in understanding the root cause of the tensorizer error.
Guidance on any specific operations or configurations to avoid.
Suggestions for debugging or additional logs to provide.

I can provide the complete model architecture and code if necessary.

**Comment by seanlatias** [comment]
Thanks for raising the issue. Yes, providing the complete code would help. The complete model architecture is not necessary as long as you can provide a minimal code block that can reproduce the issue.

**Comment by aws-liuayu** [comment]
Could you please provide the compiler artifacts for us to reproduce and debug the issue? It is located in`/tmp/ec2-user/neuroncc_compile_workdir/`. You can share the entire directory or at least we need the hlo file eg `/tmp/ec2-user/neuroncc_compile_workdir/5fde167e-bcb5-4e5c-a1c3-0cd70ae3ae42/model.MODULE_13362955078774025298+d41d8cd9.hlo.pb`

**Comment by 0x6b64** [comment]
@moyuanchen is this still an issue (using the latest Neuron releases). Can you provide us with the source code/instructions or HLO to reproduce this issue?
