### ISSUE TITLE
Tensorflow Retinanet based model compilation error | "The following operators are not implemented" 

### ISSUE THREAD

**Issue by Abdellah-Laassairi** [aws-neuron/aws-neuron-sdk#424]
## Issue description : 
I've expected to obtain the compiled binaries file for our object detection model which is retinanet based, however I've encountered a compilation error due to a set of unimplemented operators.

## Console output : 
```console
root@ac18c682fee2:/app/converter# neuron-ls
+--------+--------+--------+---------+
| NEURON | NEURON | NEURON |   PCI   |
| DEVICE | CORES  | MEMORY |   BDF   |
+--------+--------+--------+---------+
| 0      | 4      | 8 GB   | 00:1f.0 |
+--------+--------+--------+---------+
root@ac18c682fee2:/app/converter# neuron-cc compile /app/models/object-detection/serving_models --framework TENSORFLOW
2022-04-26 15:33:15.942189: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-26 15:33:15.942218: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-04-26 15:33:17.033745: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-26 15:33:17.033773: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-26 15:33:17.033797: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ac18c682fee2): /proc/driver/nvidia/version does not exist
2022-04-26 15:33:17.034894: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
04/26/2022 03:33:17 PM WARNING 7316 [tensorflow]: From /usr/local/bin/neuron-cc:8: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
2022-04-26 15:33:17.952038: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2999990000 Hz
04/26/2022 03:33:18 PM ERROR 7316 [neuron-cc]: Failed to parse model /app/models/object-detection/serving_models: The following operators are not implemented: {'TensorArrayScatterV3', 'Assign', 'StringJoin', 'RestoreV2', 'NonMaxSuppressionV3', 'TensorArrayReadV3', 'VariableV2', 'ShardedFilename', 'Exit', 'Merge', 'MergeV2Checkpoints', 'NextIteration', 'Enter', 'LoopCond', 'Switch', 'TruncatedNormal', 'IsVariableInitialized', 'TensorArrayV3', 'TensorArrayWriteV3', 'TensorArrayGatherV3', 'SaveV2', 'TensorArraySizeV3'} (NotImplementedError)
```

## Specifications

```console
root@6c0bf034c310:/# pip list | grep neuron
neuron-cc                 1.10.3.0+5c3cfc888
tensorboard-plugin-neuron 2.3.0.0
tensorflow-neuron         2.5.2.2.1.14.0
```
System specifications : 
```
  - Instance type: inf1.xlarge
  - Subsystem: ubuntu:18.04
```

**Comment by hannanjgaws** [comment]
Hi Abdellah-Laassairi,

It looks like you are invoking neuron-cc directly, which means that unsupported ops will not automatically be placed on CPU, leading to the compilation error you’re observing. Is there a specific reason you are not using the tensorflow neuron tracing API?

You can use the tensorflow neuron trace API to automatically partition unsupported operators onto the CPU to avoid compilation errors: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/api-tracing-python-api.html.

Also, an 8GB memory instance might be too small to compile your model. We recommend using an instance with more memory for compilation, such as an inf1.6xlarge or larger compute instance. You can use any inf1 instance size for deployment.

**Comment by Abdellah-Laassairi** [comment]
Hello!
Thanks for your feedback, I've used the neuron-cc compiler directly to avoid any negative impact on performance that might result from placing ops on the CPU. However I've tried implementing the neuron trace API as you've suggested and I've ran into issue https://github.com/aws/aws-neuron-sdk/issues/357 instead. 

```console
root@6c0bf034c310:/app/converter# python3 tf_2_neuron.py 
2022-04-27 10:37:31.488221: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-27 10:37:31.488247: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-04-27 10:37:32.577199: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-27 10:37:32.577225: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-27 10:37:32.577252: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (6c0bf034c310): /proc/driver/nvidia/version does not exist
2022-04-27 10:37:33.199787: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:37:47.741193: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-04-27 10:37:47.795369: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2999990000 Hz
INFO:TfNeuronConverter:Model Loading
WARNING:tensorflow:Issue encountered when serializing global_step.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing moving_average_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
2022-04-27 10:37:54.975563: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:37:54.975681: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:04.494316: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:04.494429: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:05.308737: I tensorflow/neuron/grappler/convert/segment.cc:456] There are 72 ops of 7 different types in the graph that are not compiled by neuron-cc: GatherV2, Placeholder, NoOp, ResizeBilinear, ArgMax, ResizeNearestNeighbor, NonMaxSuppressionV5, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.html).
2022-04-27 10:38:14.361231: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.361351: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.374003: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.374082: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.385802: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.385879: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.396695: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.396766: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.407500: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.407571: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.417821: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.417891: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.428195: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.428263: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.438499: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.438567: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.448843: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.448909: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.459230: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.459299: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:14.554598: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:14.554717: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.474099: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.474215: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.488986: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.489062: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.513963: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.514036: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.550369: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.550440: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.697591: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.697675: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.711541: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.711610: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.729090: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.729152: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.764726: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.764786: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:16.988389: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:16.988475: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.002334: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.002401: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.019930: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.019995: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.055968: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.056032: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.280251: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.280328: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.293994: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.294063: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.311493: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.311559: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.347450: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.347516: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.571081: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.571159: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.585003: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.585069: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.602585: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.602648: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.638734: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.638798: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.863387: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.863460: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.877097: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.877165: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.894944: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.895011: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:17.931020: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:17.931085: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.155490: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.155567: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.169213: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.169282: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.187020: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.187090: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.238278: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.238347: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.766323: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.766417: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.772059: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.772130: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.777542: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.777610: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.782651: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.782714: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.787715: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.787781: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.792715: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.792777: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.797685: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.797750: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.802601: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.802666: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.807718: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.807784: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.812749: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.812818: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:18.819750: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-04-27 10:38:18.819813: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-04-27 10:38:19.166074: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:39:16.702410: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:40:13.974744: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:41:11.529968: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:42:09.025143: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:43:06.611709: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:44:04.118648: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:45:01.760754: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:45:59.279257: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:46:57.398710: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-27 10:47:55.982208: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "tf_2_neuron.py", line 115, in <module>
    model = tfn.trace(model,example_inputs= example_input_1 )
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_neuron/python/_trace.py", line 213, in trace
    graph_def = gdu.run_compiler_on_subgraphs(graph_def, dumper)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_neuron/python/graph_def_util.py", line 332, in run_compiler_on_subgraphs
    executable, inputs, outputs = compile_savetemps(subgraph_def, inputs, outputs, node.name, dumper)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_neuron/python/neuron_cc_hlo.py", line 137, in compile_savetemps
    executable, new_inputs, new_outputs = hlo_to_neff(hlo_module, compiler_args, dumper)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_neuron/python/neuron_cc_hlo.py", line 194, in hlo_to_neff
    verify_hlo_opt(hlo_opt)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_neuron/python/neuron_cc_hlo.py", line 207, in verify_hlo_opt
    f.write(hlo_opt.get_snapshot().SerializeToString())
ValueError: Message xla.HloSnapshot exceeds maximum protobuf size of 2GB: 4613900447
```
I'm wondering if the implementation of new operators is something that's planned or not in order to compile the integrity of the graph instead of placing the ops that are not supported into the CPU. 
Thanks again!

**Comment by hannanjgaws** [comment]
Thank you for the update. As you noted, we are currently working on a fix for the 2GB protobuf limit. The roadmap item that you pointed to is the best way to track the progress on this fix.

We are continuously adding support for new operators in our releases. The best place to track our support for new operators is https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/tensorflow2-accelerated-ops.html. 

We will look into reproducing the 2GB protobuf failure. Are you able to share an open-source model that is representative of your RetinaNet model that we can use for internal testing?

**Comment by Abdellah-Laassairi** [comment]
Thank you for your response, I'll try to reproduce the issue with one of the models available in Tensorflow object detection model zoo and get back to you!

**Comment by Abdellah-Laassairi** [comment]
Hello! The issue can be reproduced using an exported efficientdet d5 model available [here](https://github.com/google/automl/blob/master/efficientdet/README.md) with input dimensions of [10,512,1280,3].

**Comment by mrnikwaws** [comment]
@Abdellah-Laassairi,

We are doing some work on the 2GB limit, which we will make available in a future release.  I have shared your link internally.

We'll share more on this issue once we have a way to work around this issue.  In the interim you can try compiling with smaller input dimensions to avoid the 2 GB limit.

**Comment by Abdellah-Laassairi** [comment]
Thank you !

**Comment by hannanjgaws** [comment]
Hi @Abdellah-Laassairi,

You can track the roadmap item (https://github.com/aws/aws-neuron-sdk/issues/357) for the most up to date status on the fix for the 2GB protobuf limit. I am going to resolve this issue in favor of the associated roadmap item. Please don't hesitate to open/re-open if you need further assistance.

**Comment by hannanjgaws** [comment]
Hi @Abdellah-Laassairi, we are hitting issues running the d5 model you pointed to. Can you provide the steps that you used to setup, export, and compile the d5 model?

**Comment by aws-owinop** [comment]
Hi @Abdellah-Laassairi,
Do you have any update on the request above?
