### ISSUE TITLE
Error happens when ssd-resnet34 model generation with compile_bs >= 4

### ISSUE THREAD

**Issue by chensongIntel** [aws-neuron/aws-neuron-sdk#480]
Definition in dockerfile 
```
ARG OS_VER="2"
ARG OS_IMAGE="amazonlinux"
FROM ${OS_IMAGE}:${OS_VER}

ARG NEURON_CC_VER="1.5.5.0+3cc38c60b"
ARG TENSORFLOW_VER="1.15.5"
ARG TENSORFLOW_NEURON_VER="1.15.5.1.5.1.0"
ARG AWS_NEURON_PIP_REPO="https://pip.repos.neuron.amazonaws.com"
RUN mkdir -p /home/ubuntu
RUN pip3 install virtualenv
RUN cd /home/ubuntu && python3 -m venv env && . ./env/bin/activate &&\
    pip3 install pip setuptools --upgrade &&\
    pip3 install "neuron-cc==${NEURON_CC_VER}"\
                "tensorflow==${TENSORFLOW_VER}"\
                "tensorflow-neuron==${TENSORFLOW_NEURON_VER}" \
                "numpy<=1.17.2"\
                "tensorflow-serving-api==1.15.0"\
                "torch>=1.0,<2.0"\
                "torchvision<1.0"\
                "pillow"\
                "matplotlib<4.0"\
                "Cython<0.29"\
                "pycocotools==2.0.1"\
                "torch-neuron"\
                --extra-index-url=${AWS_NEURON_PIP_REPO}
```

model generation command as below
`python3 ssd34_model_1200.py --torch_checkpoint=resnet34_custom.pt --output_saved_model=resnet34_tf_neuron/ --compile_bs=4 --compile_core=4`

```
Traceback (most recent call last):
  File "ssd34_model_1200.py", line 388, in <module>
    main()
  File "ssd34_model_1200.py", line 374, in main
    'Neuron executable (neff) is empty. Please check neuron-cc is installed and working properly '
AttributeError: Neuron executable (neff) is empty. Please check neuron-cc is installed and working properly ("pip install neuron-cc --force --extra-index-url=https://pip.repos.neuron.amazonaws.com" to force reinstall neuron-cc).
```

after "pip install ", error is still there.

btw, bs=1 or 2, model generation is successful

**Comment by awsrjh** [comment]
could you please send us the logs for the compilation?

**Comment by mrnikwaws** [comment]
Closing since we have not heard from the customer - please re-open if you can share your logs.
