### ISSUE TITLE
NotImplementedError: <class 'bool'>

### ISSUE THREAD

**Issue by aj2622** [aws-neuron/aws-neuron-sdk#481]
```
BaseModel(
  (backbone): ResNet(
    (conv1_1): ConvBNLayer(
      (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
      (_conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (_batch_norm): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (_act): Activation(
        (act): ReLU(inplace=True)
      )
    )
    (conv1_2): ConvBNLayer(
      (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
      (_conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (_batch_norm): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (_act): Activation(
        (act): ReLU(inplace=True)
      )
    )
    (conv1_3): ConvBNLayer(
      (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
      (_conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (_batch_norm): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (_act): Activation(
        (act): ReLU(inplace=True)
      )
    )
    (pool2d_max): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (stages): ModuleList(
      (0): Sequential(
        (bb_0_0): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (short): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (bb_0_1): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
      )
      (1): Sequential(
        (bb_1_0): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (short): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (bb_1_1): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
      )
      (2): Sequential(
        (bb_2_0): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (short): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (bb_2_1): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
      )
      (3): Sequential(
        (bb_3_0): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (short): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (bb_3_1): BasicBlock(
          (conv0): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (_act): Activation(
              (act): ReLU(inplace=True)
            )
          )
          (conv1): ConvBNLayer(
            (_pool2d_avg): AvgPool2d(kernel_size=2, stride=2, padding=0)
            (_conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (_batch_norm): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
      )
    )
  )
  (neck): DBFPN(
    (in2_conv): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (in3_conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (in4_conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (in5_conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (p5_conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (p4_conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (p3_conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (p2_conv): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  )
  (head): DBHead(
    (binarize): Head(
      (conv1): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (conv_bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu1): Activation(
        (act): ReLU(inplace=True)
      )
      (conv2): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
      (conv_bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu2): Activation(
        (act): ReLU(inplace=True)
      )
      (conv3): ConvTranspose2d(64, 1, kernel_size=(2, 2), stride=(2, 2))
    )
    (thresh): Head(
      (conv1): Conv2d(256, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (conv_bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu1): Activation(
        (act): ReLU(inplace=True)
      )
      (conv2): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
      (conv_bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu2): Activation(
        (act): ReLU(inplace=True)
      )
      (conv3): ConvTranspose2d(64, 1, kernel_size=(2, 2), stride=(2, 2))
    )
  )
)
```

trying to compile this model gives the following stack trace 

```
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 103, fused = 103, percent fused = 100.0%
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::avg_pool2d with inputs [<tf.Tensor 'Relu_6:0' shape=(1, 64, 312, 192) dtype=float32>, [2, 2], [2, 2], [0, 0], True, True, None]
INFO:Neuron:Exception = <class 'bool'>
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$395; falling back to native python function call
ERROR:Neuron:<class 'bool'>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/decorators.py", line 81, in trace
    transform_torch_graph_to_tensorflow(jit_trace, example_inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/decorators.py", line 580, in transform_torch_graph_to_tensorflow
    raise e
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/decorators.py", line 574, in transform_torch_graph_to_tensorflow
    tensor_outputs = local_func(op, *tensor_inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/ops/aten.py", line 974, in avg_pool2d
    raise NotImplementedError(type(ceil_mode))
NotImplementedError: <class 'bool'>
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 103, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::_convolution: 34 [supported]
INFO:Neuron: => aten::add: 11 [supported]
INFO:Neuron: => aten::avg_pool2d: 3 [supported]
INFO:Neuron: => aten::batch_norm: 25 [supported]
INFO:Neuron: => aten::cat: 1 [supported]
INFO:Neuron: => aten::max_pool2d: 1 [supported]
INFO:Neuron: => aten::relu: 21 [supported]
INFO:Neuron: => aten::sigmoid: 1 [supported]
INFO:Neuron: => aten::upsample_nearest2d: 6 [supported]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_19929/993837970.py in <module>
----> 1 model_neuron = torch.neuron.trace(model_, (random_input), strict=False)

~/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    166     with skip_inference_context() as s:
    167         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 168     cu.stats_post_compiler(neuron_graph)
    169 
    170     # Wrap the compiled version of the model in a script module. Note that this is

~/anaconda3/envs/aws_neuron_pytorch_p37/lib/python3.7/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    498         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    499             raise RuntimeError(
--> 500                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    501 
    502         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

is there any obvious way to fix this ? Not sure what this error means when it say in the logs that all operators are supported by neuron

**Comment by aj2622** [comment]
following https://github.com/aws/aws-neuron-sdk/issues/288#issuecomment-866284754

I was able to make things work. leaving this open in case this needs fixing

**Comment by mrnikwaws** [comment]
Hi @aj2622,

Glad to see you are unblocked.  The issue in this case is that the model you are using uses https://pytorch.org/docs/stable/generated/torch.nn.functional.avg_pool2d.html with ceil_mode=True.  

I'm going to create an internal tracking ticket to see if we can address this.  However since your issue is addressed I plan to close this ticket, unless I hear from you there is an outstanding issue for your model on neuron.
