### ISSUE TITLE
Convert error when converting over 2gb model.

### ISSUE THREAD

**Issue by Dong-Ki-Lee** [aws-neuron/aws-neuron-sdk#491]
Hello. 
While converting the model, there have been many discussions about the protobuf size issue, but I have not yet found a solution.

### Error log

`2022-09-26 02:57:53.744367: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
Traceback (most recent call last):
  File "conv.py", line 59, in <module>
    model_neuron = tfn.trace(diffusion_model, example_input)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow_neuron/python/_trace.py", line 176, in trace
    cfunc = convert_variables_to_constants_v2(func, aggressive_inlining=True)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1152, in convert_variables_to_constants_v2
    converted_input_indices)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1078, in _construct_concrete_function
    new_output_names)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 655, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 626, in wrap_function
    collections={}),
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 83, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 89, in wrapped
    return fn(*args, **kwargs)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 649, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 548, in new_func
    return func(*args, **kwargs)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/framework/importer.py", line 408, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/ec2-user/stable-diffusion-tensorflow/venv/lib64/python3.7/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 3440004855
`

### question

I think this issue is related (#357), is there a solution?
Or is there any other solution?

Thank you.

**Comment by aws-mvaria** [comment]
As you noted, the roadmap item (https://github.com/aws-neuron/aws-neuron-sdk/issues/357) is tracking the fix for the 2GB protobuf limit. I am going to resolve this issue in favor of the associated roadmap item.

@Dong-Ki-Lee - feel free to connect with us over email at [aws-neuron-support@amazon.com](mailto:aws-neuron-support@amazon.com). We implemented a prototype that will resolve this issue, but have not committed it to a release yet for other reasons. Would be great to give you the prototype as an early preview and unblock your workflow.

**Comment by aws-maens** [comment]
Roadmap Item for large protobuf : https://github.com/aws-neuron/aws-neuron-sdk/issues/582
