### ISSUE TITLE
Can't convert stable diffusion model

### ISSUE THREAD

**Issue by Dong-Ki-Lee** [aws-neuron/aws-neuron-sdk#492]
Hello

I try to convert unet model in diffusors model (stable diffusion)
But the conversion is not possible with the error below.
It's hard to understand because the error log is not clear, so is there a more detailed way or solution?

### Error Log 
```
Traceback (most recent call last):
  File "/home/waitlee/Documents/diffusers/scripts/convert.py", line 386, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/waitlee/anaconda3/envs/diffusers/lib/python3.7/site-packages/torch_neuron/decorators.py", line 82, in trace
    graph_def = graph.as_graph_def()
  File "/home/waitlee/anaconda3/envs/diffusers/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3618, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/home/waitlee/anaconda3/envs/diffusers/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_def
    graph.ParseFromString(compat.as_bytes(data))
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'
```

### Model Code 
```
import torch

from diffusers.models.unet_2d_condition import UNet2DConditionModel


class TraceableUnet2DConditionModelWrapper(torch.nn.Module):
    def __init__(self, model: UNet2DConditionModel):
        super(TraceableUnet2DConditionModelWrapper, self).__init__()
        self.model = model

    def forward(
        self,
        sample: torch.FloatTensor,
        timestep: torch.Tensor,
        encoder_hidden_states: torch.Tensor,
    ):
        output = self.model(sample, timestep, encoder_hidden_states, False)
        return output
```

### Convert Code
```
import torch
from diffusers import StableDiffusionPipeline
import torch_neuron
from convert import trace
from diffusers.models.traceable_models import TraceableUnet2DConditionModelWrapper # Model code above


@torch.no_grad()
def convert_models():
    pipeline = StableDiffusionPipeline.from_pretrained(
        "CompVis/stable-diffusion-v1-4",
        use_auth_token=True,
    )

    traced_unet = trace(
        TraceableUnet2DConditionModelWrapper(pipeline.unet),
        (
            torch.randn(1, 4, 64, 64),
            torch.LongTensor([0]),
            torch.randn(1, 77, 768)
        ),
        compiler_args=['--neuroncore-pipeline-cores', '16'],
    )
    torch.jit.save(traced_unet, 'traced_unet.pt')
```

Please let me know if there is any information that is lacking.
Thank you.

PS. When converting the unit model within the tensorflow version of the stable diffusion model, the conversion was not made due to the limitation that more than 2gb cannot be converted when converting protobuf from the internal code. #491

**Comment by jluntamazon** [comment]
This is a known issue due to the size of the model. Allowing large models like this to be compiled is a feature that we intend to address in a future release. Currently this model is not well-supported.

**Comment by Dong-Ki-Lee** [comment]
Thank you for your answer.
Do you have any specific plans?

**Comment by dimitry12** [comment]
I've seen someone splitting SD into chunks for inference on iPhone (!) into ~20 separate CoreML models. I wonder if that will work with Neuron as well. Of course, you will have to move activations around manually.

**Comment by Dong-Ki-Lee** [comment]
@dimitry12 Thank you for your opinion.
It's a possible solution to divide a large model into smaller models, but every time we serve a new model, if we have to divide the model into smaller models, it takes too much labor.
I'm sorry if what you said is not what I understand.

**Comment by dimitry12** [comment]
@Dong-Ki-Lee Yes, this is correct.

**Comment by dimitry12** [comment]
@Dong-Ki-Lee no, I haven't tried splitting SD into submodels myself. Here is the effort by another person which I was referring to: https://twitter.com/wattmaller1/status/1573768941096374274

**Comment by Dong-Ki-Lee** [comment]
Thank you for sharing.

**Comment by mrnikwaws** [comment]
Hi @Dong-Ki-Lee, 

We are still working on this model.  This is an associated roadmap item: https://github.com/aws-neuron/aws-neuron-sdk/issues/494 which is associated with the error you are seeing.

**Comment by awsrjh** [comment]
Hi @Dong-Ki-Lee,

we released an experimental fix for Tensorflow 2 in our last release (see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/tensorflow/tensorflow-neuron/api-tracing-python-api.html#special-flags ) , and we are continuing to work on this for PyTorch

**Comment by tchaton** [comment]
Hey @mrnikwaws,

What is the ETA for running stable diffusion with PyTorch on Inferentia ?

Best,
T.C

**Comment by aws-donkrets** [comment]
We plan to offer the Stable Diffusion Model on our recently announced  Inferentia2 architecture and expect to have it available in the near future. We will update this ticket when the Neuron SDK support is available.

**Comment by mrnikwaws** [comment]
@Dong-Ki-Lee  @tchaton,

We have added a fix for the 2GB limit (large model weights) in the latest version of the NeuronSDK (2.9.0). I am going to leave this issue open (unless you want to close it) on the Stable Diffusion model news for inf2 (which is still upcoming).

**Comment by yuko-i** [comment]
Failed to convert Unet model(stable-diffusion-v1-4), even inf2 and NeuronSDK 2.9.x.
How can Unet convert successfully? diffusers not supported?

As a side note, I have successfully converted BERT model of the [sample code](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/torch-neuronx/bert-base-cased-finetuned-mrpc-inference-on-trn1-tutorial.html). 

**AMI**
Deep Learning AMI Neuron PyTorch 1.13.0 (Ubuntu 20.04) 20230405

**packages versions**
aws-neuronx-collectives==2.12.27.0-cf5bcfbbc 
aws-neuronx-dkms==2.8.4.0   
aws-neuronx-oci-hook==2.1.97.0 
aws-neuronx-runtime-lib==2.12.16.0-8e42c5019
aws-neuronx-tools==2.9.5.0  

**Convert Code**
```
import torch
import torch_neuronx
from diffusers import UNet2DConditionModel

unet = UNet2DConditionModel.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="unet", torchscript=True)
unet.eval()

example =  (
    torch.randn(1, 4, 64, 64),
    torch.LongTensor([0]),
    torch.randn(1, 77, 768)
)

model_neuron = torch_neuronx.trace(unet, example)
filename = 'u_net_model.pt'
torch.jit.save(model_neuron, filename)

```

**Error**
```
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: ***************************************************************
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:  An Internal Compiler Error has occurred
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: ***************************************************************
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: 
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Error message:  Cannot handle aggregation of BNAggr!
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: 
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Error class:    AssertionError
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Error location: Unknown
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Command line:   /opt/aws_neuron_venv_pytorch/bin/neuronx-cc compile /tmp/tmpvtv9xk4d/model --framework XLA --target trn1 --output /tmp/tmpvtv9xk4d/graph.neff
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: 
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Internal details:
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/CommandDriver.py", line 237, in neuronxcc.driver.CommandDriver.CommandDriver.run
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1047, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 998, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1023, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1027, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 300, in neuronxcc.driver.Job.SingleInputJob.run
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 326, in neuronxcc.driver.Job.SingleInputJob.runOnState
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 300, in neuronxcc.driver.Job.SingleInputJob.run
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/Job.py", line 326, in neuronxcc.driver.Job.SingleInputJob.runOnState
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/jobs/Frontend.py", line 343, in neuronxcc.driver.jobs.Frontend.Frontend.runSingleInput
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/driver/jobs/Frontend.py", line 148, in neuronxcc.driver.jobs.Frontend.Frontend.runXLAFrontend
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Penguin.py", line 297, in neuronxcc.starfish.penguin.Penguin.runPenguin
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 150, in neuronxcc.starfish.penguin.Frontend.tensorizeXla
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 151, in neuronxcc.starfish.penguin.Frontend.tensorizeXla
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 159, in neuronxcc.starfish.penguin.Frontend.tensorizeXla
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Frontend.py", line 212, in neuronxcc.starfish.penguin.Frontend.tensorizeXlaFromFile
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Compile.py", line 215, in neuronxcc.starfish.penguin.Compile.compile_module
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Compile.py", line 217, in neuronxcc.starfish.penguin.Compile.compile_module
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/Compile.py", line 257, in neuronxcc.starfish.penguin.Compile.compile_module
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 445, in neuronxcc.starfish.penguin.DotTransform.PassManager.transformModule
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 464, in neuronxcc.starfish.penguin.DotTransform.PassManager.transformFunction
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 471, in neuronxcc.starfish.penguin.DotTransform.PassManager.transformFunction
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 143, in neuronxcc.starfish.penguin.DotTransform.DotTransform.runOnFunction
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 196, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 191, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 208, in neuronxcc.starfish.penguin.DotTransform.DotTransform.timed_run_
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 210, in neuronxcc.starfish.penguin.DotTransform.DotTransform.timed_run_
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 211, in neuronxcc.starfish.penguin.DotTransform.DotTransform.timed_run_
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 240, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 242, in neuronxcc.starfish.penguin.DotTransform.DotTransform.run_
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 342, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformFunction
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 343, in neuronxcc.starfish.penguin.DotTransform.DotTransform.transformFunction
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/DotTransform.py", line 333, in neuronxcc.starfish.penguin.DotTransform.DotTransform.runTransforms
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 2052, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.transformStmts
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1906, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.transformDAG
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1938, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.transformReduceLikeDAG
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1434, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.packInstsToSIMDMacro
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1805, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.buildBatchNormMacros
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1906, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.transformDAG
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1938, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.transformReduceLikeDAG
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1440, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.packInstsToSIMDMacro
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   File "neuronxcc/starfish/penguin/targets/sunda/passes/SundaSizeTiling.py", line 1591, in neuronxcc.starfish.penguin.targets.sunda.passes.SundaSizeTiling.SundaSizeTiling.buildBNAggrOpMacro
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: 
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Version information:
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   NeuronX Compiler version 2.5.0.28+1be23f232
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   HWM version 2.5.0.0-dad732dd6
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   NEFF version Dynamic
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   TVM not available
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   NumPy version 1.21.6
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]:   MXNet not available
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: 
2023-04-18T03:51:35Z ERROR 63543 [neuronx-cc]: Artifacts stored in: /home/ubuntu/neuronxcc-evuq5lm4
Traceback (most recent call last):
  File "Unet_convert.py", line 14, in <module>
    model_neuron = torch_neuronx.trace(unet, example)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 280, in trace
    neff_filename = hlo_compile(model_dir, compiler_workdir, compiler_args)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 203, in hlo_compile
    raise RuntimeError(f'neuronx-cc failed with {status}')
RuntimeError: neuronx-cc failed with 1
```

**Comment by jluntamazon** [comment]
As of [release 2.10](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#neuron-2-10-0-05-01-2023), we can now successfully compile stable diffusion for inference.

We have two samples available in the samples repository for different image sizes:
- https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/inference/hf_pretrained_sd2_512_inference.ipynb
- https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/inference/hf_pretrained_sd2_768_inference.ipynb

Closing this issue for now since this should now be resolved
