### ISSUE TITLE
NeuronPerf throwing error

### ISSUE THREAD

**Issue by abelghazinyan** [aws-neuron/aws-neuron-sdk#493]
I have a model which is successfully converted to aws neuron and inferred on Inf instance.
But when I want to use NeoronPerf for performance testings it throws errors.

`import torch  # or tensorflow, mxnet

import neuronperf
import neuronperf.torch  # or tensorflow, mxnet

batch_sizes = 1
input_shape = (batch_sizes, 3, 224, 224)
inputs = torch.ones(input_shape)  # or numpy array for TF, MX
latent = torch.FloatTensor(torch.rand(1, 512))
reports = neuronperf.torch.benchmark("simswap_neuron.pt", (inputs, latent), batch_sizes)`

The error:
`(aws_neuron_pytorch_p36) ubuntu@ip-172-31-13-57:~/ml$ python perf.py >> error.txt
INFO:neuronperf.benchmarking - Benchmarking 'simswap_neuron.pt', ~8.0 minutes remaining.
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
ERROR:neuronperf.benchmarking - Benchmarker 1 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''
ERROR:neuronperf.benchmarking - Benchmarker 2 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Benchmarker 3 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Benchmarker 0 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Child process encountered an error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Failure benchmarking config: {'model_filename': 'simswap_neuron.pt', 'model_name': 'simswap_neuron.pt', 'device_type': 'neuron', 'instance_type': 'inf1.xlarge', 'batch_size': 1, 'n_models': 4, 'workers_per_model': 1, 'pipeline_size': 1, 'n_devices': 4, 'performance_level': 3, 'multiprocess': True, 'multiinterpreter': False, 'stats_interval':'0.5', 'start_dts': '20221003-124242', 'duration': '120'}
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 1278, in benchmark
    multiinterpreter=multiinterpreter,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 888, in run_benchmarkers
    results = _run_benchmarkers_multiprocess(benchmarkers, duration)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 822, in _run_benchmarkers_multiprocess
    raise ChildProcessError()
ChildProcessError
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
ERROR:neuronperf.benchmarking - Benchmarker 2 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Benchmarker 1 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Benchmarker 3 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Benchmarker 0 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Child process encountered an error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Failure benchmarking config: {'model_filename': 'simswap_neuron.pt', 'model_name': 'simswap_neuron.pt', 'device_type': 'neuron', 'instance_type': 'inf1.xlarge', 'batch_size': 1, 'n_models': 4, 'workers_per_model': 2, 'pipeline_size': 1, 'n_devices': 4, 'performance_level': 3, 'multiprocess': True, 'multiinterpreter': False, 'stats_interval':'0.5', 'start_dts': '20221003-124442', 'duration': '120'}
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 1278, in benchmark
    multiinterpreter=multiinterpreter,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 888, in run_benchmarkers
    results = _run_benchmarkers_multiprocess(benchmarkers, duration)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 822, in _run_benchmarkers_multiprocess
    raise ChildProcessError()
ChildProcessError
(aws_neuron_pytorch_p36) ubuntu@ip-172-31-13-57:~/ml$ python perf.py > error.txt
INFO:neuronperf.benchmarking - Benchmarking 'simswap_neuron.pt', ~8.0 minutes remaining.
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
[E neuron_runtime.cpp:333] NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtime error message ''
ERROR:neuronperf.benchmarking - Benchmarker 0 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Benchmarker 3 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''
ERROR:neuronperf.benchmarking - Benchmarker 1 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''
ERROR:neuronperf.benchmarking - Benchmarker 2 encountered an error during prep:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Child process encountered an error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 243, in run
    self.setup()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 177, in setup
    self.load()
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 156, in load
    self.model = self.load_fn(self.model_filename, device_id=self.device_id)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/torch/torch.py", line 48, in _load_fn
    model = torch.jit.load(model_filename)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_RESOURCE_NC' (9) There were insufficent NCs for the requested operation Raw runtimeerror message ''

ERROR:neuronperf.benchmarking - Failure benchmarking config: {'model_filename': 'simswap_neuron.pt', 'model_name': 'simswap_neuron.pt', 'device_type': 'neuron', 'instance_type': 'inf1.xlarge', 'batch_size': 1, 'n_models': 4, 'workers_per_model': 1, 'pipeline_size': 1, 'n_devices': 4, 'performance_level': 3, 'multiprocess': True, 'multiinterpreter': False, 'stats_interval':'0.5', 'start_dts': '20221003-124734', 'duration': '120'}
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 1278, in benchmark
    multiinterpreter=multiinterpreter,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 888, in run_benchmarkers
    results = _run_benchmarkers_multiprocess(benchmarkers, duration)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/neuronperf/benchmarking.py", line 822, in _run_benchmarkers_multiprocess
    raise ChildProcessError()
ChildProcessError`

**Comment by shebbur-aws** [comment]
Hi abelghazinyan, 

The most likely cause of this error is that another process already had a model loaded on Neuron hardware when you ran the benchmark. So some cores were not available. Before you begin benchmarking, could you run neuron-top and verify that there are no cores in use?

Another side note, looks like you are using Python version 3.6 which is not supported officially. Recommend upgrading to latest release version of all our packages and dependencies - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/releasecontent.html 

Thanks.

**Comment by aws-stdun** [comment]
Hi @abelghazinyan,

This error has two possible causes:
1. You trying to load too many models
2. There is an issue with the runtime

One way that case 1 could happen is if your compiled model already loads onto multiple cores (this can happen when using Dynamic Batching, for example).

Change your benchmark call like this:
```
reports = neuronperf.torch.benchmark(
    "simswap_neuron.pt", 
    (inputs, latent), 
    batch_sizes=batch_sizes, 
    n_models=1
)
```

If this works, it narrows the problem to case 1.

On another note, I notice you are using the old version of the Neuron runtime. You could also consider upgrading your environment to [Runtime 2.x](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/index.html) and using a Python 3.7 environment instead of 3.6.

**Comment by aws-stdun** [comment]
Hi @abelghazinyan,

Did you manage to get this working?

**Comment by mrnikwaws** [comment]
Since we haven't hear back on the proposed resolution, closing this ticket
