### ISSUE TITLE
Unable to compile roberta-base from huggingface using torch SDK

### ISSUE THREAD

**Issue by parakalan** [aws-neuron/aws-neuron-sdk#495]
I'm getting this error 

`10/06/2022 04:09:54 AM ERROR [neuron-cc]: Error message:  Compiler generated too many instructions, this may due to a failure in parallelism extraction` while trying to compile Roberta

Here is the script I am running - 
```from transformers import AutoModel
from transformers import AutoTokenizer
transformer_name = "roberta-base"
model = AutoModel.from_pretrained(transformer_name)
model = model.requires_grad_(requires_grad=False)
tokenizer = AutoTokenizer.from_pretrained(transformer_name)
neuron_direcory = "./roberta-base-infx/"
max_seq_length = 514 
batch_size = 16
neuron_model_directory = neuron_direcory + "model.jit"
import tensorflow
import torch
import torch.neuron
import transformers
sequence = ["The company HuggingFace is based in New York City"] * batch_size
paraphrase = tokenizer.batch_encode_plus(sequence, max_length=max_seq_length, padding='max_length', truncation=True, return_tensors="pt")
paraphrase_classification_logits = model(**paraphrase)[0]
example_inputs_paraphrase = paraphrase['input_ids'].detach(), paraphrase['attention_mask'].detach()

def model_predict(input_ids, attention_mask):
    output = model(input_ids=input_ids, attention_mask=attention_mask, return_dict=False)
    return output
model_neuron.save(neuron_direcory)
```

The complete error log - 

```INFO:Neuron:There are 5 ops of 3 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, aten::cumsum, aten::type_as, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 717, fused = 691, percent fused = 96.37%
INFO:Neuron:Compiling function _NeuronGraph$9 with neuron-cc
INFO:Neuron:Compiling with command line: '/inferentia/bin/neuron-cc compile /tmp/tmpbo755_m4/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpbo755_m4/graph_def.neff --io-config {"inputs": {"0:0": [[16, 514, 768], "float32"], "1:0": [[16, 1, 1, 514], "float32"]}, "outputs": ["batchnorm_24/add_1:0", "Tanh_12:0"]} --verbose 35'
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
.........10/06/2022 04:09:54 AM ERROR [neuron-cc]: ***************************************************************
10/06/2022 04:09:54 AM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
10/06/2022 04:09:54 AM ERROR [neuron-cc]: ***************************************************************
10/06/2022 04:09:54 AM ERROR [neuron-cc]: 
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Error message:  Compiler generated too many instructions, this may due to a failure in parallelism extraction
10/06/2022 04:09:54 AM ERROR [neuron-cc]: 
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Error class:    RuntimeError
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Error location: job.Frontend.4
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Command line:   /inferentia/bin/neuron-cc compile /tmp/tmpbo755_m4/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpbo755_m4/graph_def.neff --io-config '{"inputs": {"0:0": [[16, 514, 768], "float32"], "1:0": [[16, 1, 1, 514], "float32"]}, "outputs": ["batchnorm_24/add_1:0", "Tanh_12:0"]}' --verbose 35
10/06/2022 04:09:54 AM ERROR [neuron-cc]: 
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Internal details:
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 244, in neuroncc.driver.Job.runSingleInputFn
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 236, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 237, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 247, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 217, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput.tensorize
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 219, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 220, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 242, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 133, in neuroncc.starfish.penguin.Frontend.compile
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 175, in neuroncc.starfish.penguin.Frontend.codegen
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 187, in neuroncc.starfish.penguin.Frontend.codegenBIR
10/06/2022 04:09:54 AM ERROR [neuron-cc]: 
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Version information:
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   Neuron Compiler version 1.4.1.0+737cbb69a
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   HWM version 1.4.1.0-0
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   NEFF version 1.0
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   TVM version 1.4.1.0+0
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   NumPy version 1.19.5
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   MXNet not available
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   TF not available
10/06/2022 04:09:54 AM ERROR [neuron-cc]:   ONNX not available
10/06/2022 04:09:54 AM ERROR [neuron-cc]: 
10/06/2022 04:09:54 AM ERROR [neuron-cc]: Artifacts stored in: /tmp/tmpbo755_m4

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$9; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/inferentia/bin/neuron-cc compile /tmp/tmpbo755_m4/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpbo755_m4/graph_def.neff --io-config '{"inputs": {"0:0": [[16, 514, 768], "float32"], "1:0": [[16, 1, 1, 514], "float32"]}, "outputs": ["batchnorm_24/add_1:0", "Tanh_12:0"]}' --verbose 35
Traceback (most recent call last):
  File "/inferentia/lib/python3.6/site-packages/torch_neuron/convert.py", line 330, in op_converter
    dynamic_batch_size=self.dynamic_batch_size, **kwargs)
  File "/inferentia/lib/python3.6/site-packages/torch_neuron/decorators.py", line 191, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/inferentia/bin/neuron-cc compile /tmp/tmpbo755_m4/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpbo755_m4/graph_def.neff --io-config '{"inputs": {"0:0": [[16, 514, 768], "float32"], "1:0": [[16, 1, 1, 514], "float32"]}, "outputs": ["batchnorm_24/add_1:0", "Tanh_12:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 717, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 98 [supported]
INFO:Neuron: => aten::add: 112 [supported]
INFO:Neuron: => aten::addmm: 1 [supported]
INFO:Neuron: => aten::contiguous: 12 [supported]
INFO:Neuron: => aten::cumsum: 1 [not supported]
INFO:Neuron: => aten::div: 12 [supported]
INFO:Neuron: => aten::dropout: 37 [supported]
INFO:Neuron: => aten::embedding: 3 [not supported]
INFO:Neuron: => aten::gelu: 12 [supported]
INFO:Neuron: => aten::layer_norm: 25 [supported]
INFO:Neuron: => aten::matmul: 96 [supported]
INFO:Neuron: => aten::mul: 2 [supported]
INFO:Neuron: => aten::ne: 1 [supported]
INFO:Neuron: => aten::permute: 48 [supported]
INFO:Neuron: => aten::rsub: 1 [supported]
INFO:Neuron: => aten::select: 1 [supported]
INFO:Neuron: => aten::size: 98 [supported]
INFO:Neuron: => aten::slice: 3 [supported]
INFO:Neuron: => aten::softmax: 12 [supported]
INFO:Neuron: => aten::t: 73 [supported]
INFO:Neuron: => aten::tanh: 1 [supported]
INFO:Neuron: => aten::to: 4 [supported]
INFO:Neuron: => aten::transpose: 12 [supported]
INFO:Neuron: => aten::type_as: 1 [not supported]
INFO:Neuron: => aten::unsqueeze: 2 [supported]
INFO:Neuron: => aten::view: 48 [supported]
INFO:Neuron: => aten::zeros: 1 [supported]
No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

**Comment by shebbur-aws** [comment]
Hi Sudharsan, thank for reporting the issue and providing the script for the repro. We have successfully reproduced the issue and currently looking into it. Will post once we have further updates to share.

Thanks.

**Comment by parakalan** [comment]
Thank you!
________________________________

**Comment by aws-owinop** [comment]
Hi @parakalan, we suspect you are trying to run with a batch size that is too large for this specific model on Inferentia. In general terms, Inferentia is optimized to maximize throughput with small batch sizes. We suggest you start with batch_size=1, check performance , and afterwards incrementally tune the batch_size to find the optimal configuration as per our guide [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-features/neuroncore-batching.html)

**Comment by jeffhataws** [comment]
Hi @parakalan, please let us know if you were able to follow @aws-owinop 's recommendation. Thanks!

**Comment by jeffhataws** [comment]
Hi @parakalan, I am closing this ticket for now. Please reopen or file new ticket if you still having problems. Thanks!
