### ISSUE TITLE
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::_convolution with inputs

### ISSUE THREAD

**Issue by heylamourding** [aws-neuron/aws-neuron-sdk#598]
Hi team, I encountered this issue. Could u help check?

```
import torch_neuron
image = torch.randn(1, 3,224,224)
torch.neuron.analyze_model(det_model, example_inputs=[image])
model_neuron = torch.neuron.trace(det_model, example_inputs=[image])
model_neuron.save("mmocr_db_traced_neuron.pt")
```

 
```
pip install torch==1.11.0
pip install torchvision==0.12.0
pip install torch-neuron==1.11.0.2.3.0.0
pip install torch-model-archiver==0.6.1
pip install neuron_cc==1.11.7
```

```
/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py:735: UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is.
  warnings.warn(
INFO:Neuron:The following operations are currently supported in torch-neuron for this model:
INFO:Neuron:aten::sigmoid
INFO:Neuron:aten::exp
INFO:Neuron:aten::mul
INFO:Neuron:prim::TupleUnpack
INFO:Neuron:aten::Int
INFO:Neuron:aten::upsample_nearest2d
INFO:Neuron:aten::add
INFO:Neuron:aten::max_pool2d
INFO:Neuron:aten::size
INFO:Neuron:prim::ListConstruct
INFO:Neuron:prim::TupleConstruct
INFO:Neuron:aten::_convolution
INFO:Neuron:prim::Constant
INFO:Neuron:aten::cat
INFO:Neuron:aten::relu
INFO:Neuron:aten::batch_norm
INFO:Neuron:aten::reciprocal
INFO:Neuron:aten::sub
INFO:Neuron:prim::NumToTensor
INFO:Neuron:100.00% of all operations (including primitives) (727 of 727) are supported
INFO:Neuron:100.00% of arithmetic operations (135 of 135) are supported
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 135, fused = 135, percent fused = 100.0%
2022-11-18 06:42:32.097899: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-18 06:42:32.281744: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
INFO:Neuron:Number of neuron graph operations 727 did not match traced graph 1046 - using heuristic matching of hierarchical information
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::_convolution with inputs [<tf.Tensor 'DBHead_6/Sequential_5/ReLU_10/aten_relu/Relu:0' shape=(1, 64, 56, 56) dtype=float32>, <tf.Tensor 'DBHead_6/Sequential_5/ConvTranspose2d_11/prim_Constant/Const:0' shape=(64, 64, 2, 2) dtype=float32>, <tf.Tensor 'DBHead_6/Sequential_5/ConvTranspose2d_11/prim_Constant_1/Const:0' shape=(64,) dtype=float32>, [2, 2], [0, 0], [1, 1], True, [0, 0], 1, False, False, True, True]
INFO:Neuron:Exception = Got an unexpected keyword argument 'value'
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$680; falling back to native python function call
ERROR:Neuron:Got an unexpected keyword argument 'value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch_neuron/convert.py", line 381, in op_converter
    neuron_function = self.subgraph_compiler(
  File "/usr/local/lib/python3.8/dist-packages/torch_neuron/decorators.py", line 80, in trace
    transform_torch_graph_to_tensorflow(jit_trace, example_inputs, neuron_graph=func, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_neuron/decorators.py", line 574, in transform_torch_graph_to_tensorflow
    raise e
  File "/usr/local/lib/python3.8/dist-packages/torch_neuron/decorators.py", line 568, in transform_torch_graph_to_tensorflow
    tensor_outputs = local_func(op, *tensor_inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch_neuron/ops/aten.py", line 148, in _convolution
    tensor = tf.nn.conv2d_transpose(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py", line 1170, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
TypeError: Got an unexpected keyword argument 'value'
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 135, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 14 [supported]
INFO:Neuron: => aten::_convolution: 34 [supported]
INFO:Neuron: => aten::add: 12 [supported]
INFO:Neuron: => aten::batch_norm: 24 [supported]
INFO:Neuron: => aten::cat: 2 [supported]
INFO:Neuron: => aten::exp: 1 [supported]
INFO:Neuron: => aten::max_pool2d: 1 [supported]
INFO:Neuron: => aten::mul: 1 [supported]
INFO:Neuron: => aten::reciprocal: 1 [supported]
INFO:Neuron: => aten::relu: 21 [supported]
INFO:Neuron: => aten::sigmoid: 2 [supported]
INFO:Neuron: => aten::size: 14 [supported]
INFO:Neuron: => aten::sub: 1 [supported]
INFO:Neuron: => aten::upsample_nearest2d: 7 [supported]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [10], in <cell line: 5>()
      2 image = torch.randn(1, 3,224,224)
      3 torch.neuron.analyze_model(det_model, example_inputs=[image])
----> 5 model_neuron = torch.neuron.trace(det_model, example_inputs=[image])
      7 model_neuron.save("mmocr_db_traced_neuron.pt")

File /usr/local/lib/python3.8/dist-packages/torch_neuron/convert.py:184, in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    182     logger.debug("skip_inference_context - trace with fallback at {}".format(get_file_and_line()))
    183     neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 184 cu.stats_post_compiler(neuron_graph)
    186 # Wrap the compiled version of the model in a script module. Note that this is
    187 # necessary for torch==1.8.1 due to the usage of `torch.classes.model.Model`. The
    188 # custom class must be a submodule of the traced graph.
    189 neuron_graph = AwsNeuronGraphModule(neuron_graph)

File /usr/local/lib/python3.8/dist-packages/torch_neuron/convert.py:492, in CompilationUnit.stats_post_compiler(self, neuron_graph)
    488             logger.info(' => {}: {} {}'.format(
    489                 name, remaining_count, supported_string))
    491 if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
--> 492     raise RuntimeError(
    493         "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    495 if percent_operations_compiled < 50.0:
    496     logger.warning(
    497         "torch.neuron.trace was unable to compile > 50% of the operators in the compiled model!")

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

**Comment by heylamourding** [comment]
Hi, any one can help on this issue?

**Comment by hannanjgaws** [comment]
Hi @heylamourding:

This type of error can occur because of a version of `tensorflow` which is incompatible with the framework/compiler. When using `torch-neuron`, you will need `tensorflow==1.15.0` installed. The version of `tensorflow` is derived from the `neuron-cc[tensorflow]` dependency.

To get the correct version of `tensorflow` for `torch-neuron`, the recommended way is to reinstall the neuron-cc compiler with the extra `[tensorflow]` specifier:

```
$ pip install --upgrade --force-reinstall --extra-index-url=https://pip.repos.neuron.amazonaws.com/ "neuron-cc[tensorflow]"
```

It’s not ideal, but it may also be a good idea to create a new virtual environment with the minimal set of dependencies needed to compile your model. Dependency issues may be easier to solve with a fresh start. The [torch-neuron install guide](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/setup/pytorch-install.html) has steps for creating a fresh environment.

In the coming release, this `tensorflow` version mismatch error will be much less ambiguous.

**Comment by heylamourding** [comment]
Hi @hannanjgaws , 

Thanks for ur solution. I created a python env 3.7 with conda and install following packages 

```
pip install tensorflow==1.15.0  
pip install torch==1.11.0
pip install torchvision==0.12.0 
pip install mmcv==1.6.1
pip install mmocr==0.6.1 
pip install mmdet==2.25.1 
pip install mmcv-full==1.6.1 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.11.0/index.html 
pip install matplotlib==3.5.3
pip install torch-neuron==1.11.0.2.3.0.0
pip install torch-model-archiver==0.6.1
pip install neuron_cc==1.11.7 
```

However, the error shows 
```
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 135, fused = 135, percent fused = 100.0%
INFO:Neuron:Number of neuron graph operations 727 did not match traced graph 1046 - using heuristic matching of hierarchical information
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$680; falling back to native python function call
ERROR:Neuron:Please check that neuron-cc is installed and working properly. You can install neuron-cc using 'python3 -m pip install neuron-cc[tensorflow] -U --extra-index-url=https://pip.repos.neuron.amazonaws.com'
Traceback (most recent call last):
  File "/workspace/miniconda3/envs/inferentia/lib/python3.7/site-packages/torch_neuron/convert.py", line 382, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/miniconda3/envs/inferentia/lib/python3.7/site-packages/torch_neuron/decorators.py", line 135, in trace
    "Please check that neuron-cc is installed and working properly. You can install neuron-cc using 'python3 -m pip install neuron-cc[tensorflow] -U --extra-index-url=https://pip.repos.neuron.amazonaws.com'")
RuntimeError: Please check that neuron-cc is installed and working properly. You can install neuron-cc using 'python3 -m pip install neuron-cc[tensorflow] -U --extra-index-url=https://pip.repos.neuron.amazonaws.com'
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 135, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 14 [supported]
INFO:Neuron: => aten::_convolution: 34 [supported]
INFO:Neuron: => aten::add: 12 [supported]
INFO:Neuron: => aten::batch_norm: 24 [supported]
INFO:Neuron: => aten::cat: 2 [supported]
INFO:Neuron: => aten::exp: 1 [supported]
INFO:Neuron: => aten::max_pool2d: 1 [supported]
INFO:Neuron: => aten::mul: 1 [supported]
INFO:Neuron: => aten::reciprocal: 1 [supported]
INFO:Neuron: => aten::relu: 21 [supported]
INFO:Neuron: => aten::sigmoid: 2 [supported]
INFO:Neuron: => aten::size: 14 [supported]
INFO:Neuron: => aten::sub: 1 [supported]
INFO:Neuron: => aten::upsample_nearest2d: 7 [supported]
```

I have installed neuron-cc. May I know why this error still exists?

**Comment by heylamourding** [comment]
Hi @hannanjgaws, I also tried following command as u suggested
```
pip install --upgrade --force-reinstall --extra-index-url=https://pip.repos.neuron.amazonaws.com/ "neuron-cc[tensorflow]"
```
But it shows 
```
ERROR: Could not install packages due to an OSError: [Errno 16] Device or resource busy: '.nfs98a1bbee36bd456f00000017'
```
May I know how do fix it? Thanks in advance!

**Comment by heylamourding** [comment]
```
Package                      Version
---------------------------- --------------------------
absl-py                      1.3.0
astor                        0.8.1
attrs                        22.1.0
backcall                     0.2.0
certifi                      2022.9.24
charset-normalizer           2.1.1
debugpy                      1.6.3
decorator                    5.1.1
dmlc-nnvm                    1.11.1.0+0
dmlc-topi                    1.11.1.0+0
dmlc-tvm                     1.11.1.0+0
entrypoints                  0.4
exceptiongroup               1.0.4
flatbuffers                  22.10.26
gast                         0.2.2
google-pasta                 0.2.0
grpcio                       1.50.0
h5py                         3.7.0
idna                         3.4
importlib-metadata           5.0.0
inferentia-hwm               1.11.0.0+0
iniconfig                    1.1.1
ipykernel                    6.16.2
ipython                      7.34.0
islpy                        2021.1+aws2021.x.39.0.bld0
jedi                         0.18.1
jupyter_client               7.4.7
jupyter_core                 4.11.2
Keras-Applications           1.0.8
Keras-Preprocessing          1.1.2
libclang                     14.0.6
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib-inline            0.1.6
nest-asyncio                 1.5.6
networkx                     2.4
neuron-cc                    1.11.7.0+aec18907e
numpy                        1.20.0
opt-einsum                   3.3.0
packaging                    21.3
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.3.0
pip                          22.3.1
pluggy                       1.0.0
prompt-toolkit               3.0.32
protobuf                     3.19.6
psutil                       5.9.4
ptyprocess                   0.7.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
Pygments                     2.13.0
pyparsing                    3.0.9
pytest                       7.2.0
python-dateutil              2.8.2
pyzmq                        24.0.1
requests                     2.28.1
rsa                          4.9
scipy                        1.4.1
setuptools                   65.6.0
six                          1.16.0
tensorboard                  1.15.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   1.15.0
tensorflow-estimator         1.15.1
tensorflow-io-gcs-filesystem 0.27.0
termcolor                    2.1.1
tomli                        2.0.1
torch                        1.11.0
torch-neuron                 1.11.0.2.3.0.0
torchvision                  0.12.0
tornado                      6.2
traitlets                    5.5.0
typing_extensions            4.4.0
urllib3                      1.26.12
wcwidth                      0.2.5
Werkzeug                     2.2.2
wheel                        0.38.4
wrapt                        1.14.1
zipp                         3.10.0

```
After running 
```
neuron-cc --version
```
Neuron Compiler version 1.11.7.0+aec18907e

HWM version 1.11.0.0-0
NEFF version Dynamic
TVM version 1.11.1.0+0
NumPy version 1.20.0
MXNet not available
TF not available
```

```

**Comment by heylamourding** [comment]
Hi @hannanjgaws, after few rounds of trying, I successfully solved bug. 

For others, who encountering same issue, you can try following package version.

```
absl-py==1.0.0
addict==2.4.0
astor==0.8.1
attrs==21.4.0
backcall==0.2.0
cached-property==1.5.2
captum==0.5.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.2
curlify==2.2.1
cycler==0.11.0
debugpy==1.6.0
decorator==5.1.1
dmlc-nnvm==1.10.0.0+0
dmlc-topi==1.10.0.0+0
dmlc-tvm==1.10.0.0+0
entrypoints==0.4
enum-compat==0.0.3
filelock==3.6.0
fonttools==4.32.0
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.44.0
h5py==3.6.0
huggingface-hub==0.5.1
idna==3.3
imageio==2.16.2
imgaug==0.4.0
importlib-metadata==4.11.3
inferentia-hwm==1.10.0.0+0
iniconfig==1.1.1
ipykernel==6.13.0
ipython==7.32.0
islpy==2021.1+aws2021.x.16.0.bld0
jarowinkler==1.0.2
jedi==0.18.1
joblib==1.1.0
jupyter-client==7.2.2
jupyter-core==4.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.4.2
lanms-neo==1.0.2
llvmlite==0.38.1
lmdb==1.3.0
Markdown==3.3.6
matplotlib==3.5.1
matplotlib-inline==0.1.3
natsort==8.1.0
nest-asyncio==1.5.5
networkx==2.4
neuron-cc==1.10.3.0+5c3cfc888
nltk==3.7
numba==0.55.2
numpy==1.20.0
opencv-python==4.5.4.60
opencv-python-headless==4.5.4.60
opt-einsum==3.3.0
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.1.0
pluggy==1.0.0
prompt-toolkit==3.0.29
protobuf==3.20.0
psutil==5.9.0
ptyprocess==0.7.0
py==1.11.0
pyclipper==1.3.0.post2
pycocotools==2.0.4
Pygments==2.11.2
pyparsing==3.0.8
pytest==7.1.1
python-dateutil==2.8.2
PyWavelets==1.3.0
PyYAML==6.0
pyzmq==22.3.0
rapidfuzz==2.0.11
regex==2022.3.15
requests==2.27.1
sacremoses==0.0.49
scikit-image==0.19.2
scipy==1.4.1
Shapely==1.8.2
six==1.16.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
terminaltables==3.1.10
tifffile==2021.11.2
tokenizers==0.10.3
tomli==2.0.1
torch==1.10.1
torch-model-archiver==0.5.0
torch-neuron==1.10.1.2.2.0.0
torchserve==0.5.0
torchvision==0.11.2
tornado==6.1
tqdm==4.64.1
traitlets==5.1.1
transformers==4.12.5
typing_extensions==4.1.1
urllib3==1.26.9
wcwidth==0.2.5
Werkzeug==2.1.1
wrapt==1.14.0
yapf==0.32.0
zipp==3.8.0
```

**Comment by hannanjgaws** [comment]
Hi @heylamourding:

Thank you for letting us know you were able to resolve the issue you were seeing. Please feel free to open a separate ticket if you encounter any additional issues while using Neuron.
