### ISSUE TITLE
Albert Pytorch Tracing Issue

### ISSUE THREAD

**Issue by kouohhashi** [aws-neuron/aws-neuron-sdk#603]
**Environment:**
torch: 1.11.0+cu102
torch-neuron: 1.11.0.2.3.0.0
Ubuntu: 20.04

**Problem:**
I tried to use torch_neuron to trace the Albert model but i got  an error of "RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!"

Since Albert is one of Bert like models, I thought I can compile it even though it's not 100% fused.
Could someone give me hints to debug?
Thanks in advance.

**Logs when tracing the Albert model:**
```
# convert pytorch into neuron
​
example_inputs = input_tensor
model_neuron = torch.neuron.trace(model, example_inputs, strict=False)
​
INFO:Neuron:There are 3 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 640, fused = 617, percent fused = 96.41%
INFO:Neuron:Number of neuron graph operations 1888 did not match traced graph 1606 - using heuristic matching of hierarchical information
INFO:Neuron:Compiling function _NeuronGraph$476 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/pytorch/bin/neuron-cc compile /tmp/tmp3plgr4yl/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp3plgr4yl/graph_def.neff --io-config {"inputs": {"0:0": [[1, 10, 128], "float32"], "1:0": [[1, 1, 1, 10], "float32"]}, "outputs": ["Linear_5/aten_linear/Add:0"]} --verbose 35'
...
INFO:Neuron:Compile command returned: -9
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$476; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/pytorch/bin/neuron-cc compile /tmp/tmp3plgr4yl/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp3plgr4yl/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 10, 128], "float32"], "1:0": [[1, 1, 1, 10], "float32"]}, "outputs": ["Linear_5/aten_linear/Add:0"]}' --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_neuron/convert.py", line 382, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_neuron/decorators.py", line 220, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/pytorch/bin/neuron-cc compile /tmp/tmp3plgr4yl/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp3plgr4yl/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 10, 128], "float32"], "1:0": [[1, 1, 1, 10], "float32"]}, "outputs": ["Linear_5/aten_linear/Add:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 640, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 77 [supported]
INFO:Neuron: => aten::add: 75 [supported]
INFO:Neuron: => aten::contiguous: 12 [supported]
INFO:Neuron: => aten::div: 12 [supported]
INFO:Neuron: => aten::dropout: 26 [supported]
INFO:Neuron: => aten::einsum: 12 [supported]
INFO:Neuron: => aten::embedding: 3 [not supported]
INFO:Neuron: => aten::layer_norm: 25 [supported]
INFO:Neuron: => aten::linear: 62 [supported]
INFO:Neuron: => aten::matmul: 24 [supported]
INFO:Neuron: => aten::mul: 49 [supported]
INFO:Neuron: => aten::ones: 1 [supported]
INFO:Neuron: => aten::permute: 48 [supported]
INFO:Neuron: => aten::pow: 12 [supported]
INFO:Neuron: => aten::rsub: 1 [supported]
INFO:Neuron: => aten::size: 75 [supported]
INFO:Neuron: => aten::slice: 2 [supported]
INFO:Neuron: => aten::softmax: 12 [supported]
INFO:Neuron: => aten::t: 12 [supported]
INFO:Neuron: => aten::tanh: 12 [supported]
INFO:Neuron: => aten::to: 25 [supported]
INFO:Neuron: => aten::transpose: 12 [supported]
INFO:Neuron: => aten::unsqueeze: 2 [supported]
INFO:Neuron: => aten::view: 48 [supported]
INFO:Neuron: => aten::zeros: 1 [supported]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2907/614065084.py in <module>
      2 
      3 example_inputs = input_tensor
----> 4 model_neuron = torch.neuron.trace(model, example_inputs, strict=False)

~/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    182         logger.debug("skip_inference_context - trace with fallback at {}".format(get_file_and_line()))
    183         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 184     cu.stats_post_compiler(neuron_graph)
    185 
    186     # Wrap the compiled version of the model in a script module. Note that this is

~/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    491         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    492             raise RuntimeError(
--> 493                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    494 
    495         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!

.........
```

**Comment by awsrjh** [comment]
Let us take a look and get back to you. 

Take care.

**Comment by kouohhashi** [comment]
I'm sorry, my bad.
I change instance type from inf1.xlarge into inf1.6xlarge and it worked.
Maybe my small tweak make my model needs more memory...
