### ISSUE TITLE
[torch-neuron] Is Swin (hugging face) supported in inferentia? 

### ISSUE THREAD

**Issue by heylamourding** [aws-neuron/aws-neuron-sdk#626]
Hi team, may I know whether swin is supported to deploy inferentia instance?

**Comment by heylamourding** [comment]
I firstly traced swinT model successfully. 
Afterwards, 
I tried to use the code below to convert model into neuron format
```
model_neuron = torch.neuron.trace(det_model, example_inputs=[image], strict=False)
```
Error code shows: 
```
/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch/jit/_trace.py:736: UserWarning: The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is.
  "The input to trace is already a ScriptModule, tracing it is a no-op. Returning the object as is."
INFO:Neuron:The following operations are currently supported in torch-neuron for this model:
INFO:Neuron:aten::zeros
INFO:Neuron:aten::Int
INFO:Neuron:aten::flatten
INFO:Neuron:aten::div
INFO:Neuron:aten::rsub
INFO:Neuron:aten::to
INFO:Neuron:prim::TupleUnpack
INFO:Neuron:aten::sub
INFO:Neuron:aten::matmul
INFO:Neuron:aten::cat
INFO:Neuron:aten::contiguous
INFO:Neuron:aten::eq
INFO:Neuron:prim::TupleConstruct
INFO:Neuron:aten::softmax
INFO:Neuron:aten::linear
INFO:Neuron:prim::NumToTensor
INFO:Neuron:aten::permute
INFO:Neuron:aten::remainder
INFO:Neuron:aten::layer_norm
INFO:Neuron:aten::gelu
INFO:Neuron:prim::ListConstruct
INFO:Neuron:aten::transpose
INFO:Neuron:aten::constant_pad_nd
INFO:Neuron:aten::unsqueeze
INFO:Neuron:aten::slice
INFO:Neuron:aten::ne
INFO:Neuron:aten::fill_
INFO:Neuron:aten::_convolution
INFO:Neuron:aten::view
INFO:Neuron:aten::size
INFO:Neuron:aten::masked_fill
INFO:Neuron:aten::mul
INFO:Neuron:aten::add
INFO:Neuron:prim::Constant
INFO:Neuron:aten::dropout
INFO:Neuron:The following operations are currently not supported in torch-neuron for this model:
INFO:Neuron:aten::adaptive_avg_pool1d
INFO:Neuron:aten::index
INFO:Neuron:aten::roll
INFO:Neuron:99.29% of all operations (including primitives) (3226 of 3249) are supported
INFO:Neuron:98.73% of arithmetic operations (1790 of 1813) are supported
INFO:Neuron:There are 23 ops of 3 different types in the TorchScript that are not compiled by neuron-cc: aten::adaptive_avg_pool1d, aten::index, aten::roll, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1813, fused = 42, percent fused = 2.32%
INFO:Neuron:Compiling function _NeuronGraph$1517 with neuron-cc
INFO:Neuron:Compiling with command line: '/workspace/.pyenv/versions/inferentia_conversion/bin/neuron-cc compile /tmp/tmpa40eqjc6/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpa40eqjc6/graph_def.neff --io-config {"inputs": {"0:0": [[1, 49, 768], "float32"]}, "outputs": ["transpose:0", "batchnorm/add_1:0"]} --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiling function _NeuronGraph$1518 with neuron-cc
INFO:Neuron:Compiling with command line: '/workspace/.pyenv/versions/inferentia_conversion/bin/neuron-cc compile /tmp/tmpnhoz2b0q/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpnhoz2b0q/graph_def.neff --io-config {"inputs": {"0:0": [[1, 49, 4, 1], "float32"], "1:0": [[1, 49, 3, 1], "float32"], "2:0": [[1, 4, 49, 1], "float32"], "3:0": [[1, 4, 4, 1], "float32"], "4:0": [[1, 4, 3, 1], "float32"], "5:0": [[1, 3, 49, 1], "float32"], "6:0": [[1, 3, 4, 1], "float32"], "7:0": [[1, 3, 3, 1], "float32"]}, "outputs": []} --verbose 35'
.
Compiler status PASS
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1518; falling back to native python function call
ERROR:Neuron:No such operator neuron::forward_v2_0
Traceback (most recent call last):
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 244, in trace
    return create_runnable(metaneff, neff, preprocessor, postprocessor, output_tensors, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 414, in create_runnable
    output_tensors
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 388, in create_runnable_v2
    forward_func = eval('torch.ops.neuron.forward_v2_{}'.format(len(output_tensors)))
  File "<string>", line 1, in <module>
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator neuron::forward_v2_0
INFO:Neuron:Compiling function _NeuronGraph$1519 with neuron-cc
INFO:Neuron:Compiling with command line: '/workspace/.pyenv/versions/inferentia_conversion/bin/neuron-cc compile /tmp/tmp1ya2_f5f/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp1ya2_f5f/graph_def.neff --io-config {"inputs": {"0:0": [[1, 21, 4, 1], "float32"], "1:0": [[1, 21, 3, 1], "float32"], "2:0": [[1, 4, 21, 1], "float32"], "3:0": [[1, 4, 4, 1], "float32"], "4:0": [[1, 4, 3, 1], "float32"], "5:0": [[1, 3, 21, 1], "float32"], "6:0": [[1, 3, 4, 1], "float32"], "7:0": [[1, 3, 3, 1], "float32"]}, "outputs": []} --verbose 35'
.
Compiler status PASS
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1519; falling back to native python function call
ERROR:Neuron:No such operator neuron::forward_v2_0
Traceback (most recent call last):
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 244, in trace
    return create_runnable(metaneff, neff, preprocessor, postprocessor, output_tensors, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 414, in create_runnable
    output_tensors
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 388, in create_runnable_v2
    forward_func = eval('torch.ops.neuron.forward_v2_{}'.format(len(output_tensors)))
  File "<string>", line 1, in <module>
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator neuron::forward_v2_0
INFO:Neuron:Compiling function _NeuronGraph$1520 with neuron-cc
INFO:Neuron:Compiling with command line: '/workspace/.pyenv/versions/inferentia_conversion/bin/neuron-cc compile /tmp/tmpf_86qrb8/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpf_86qrb8/graph_def.neff --io-config {"inputs": {"0:0": [[1, 7, 4, 1], "float32"], "1:0": [[1, 7, 3, 1], "float32"], "2:0": [[1, 4, 7, 1], "float32"], "3:0": [[1, 4, 4, 1], "float32"], "4:0": [[1, 4, 3, 1], "float32"], "5:0": [[1, 3, 7, 1], "float32"], "6:0": [[1, 3, 4, 1], "float32"], "7:0": [[1, 3, 3, 1], "float32"]}, "outputs": []} --verbose 35'
.
Compiler status PASS
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1520; falling back to native python function call
ERROR:Neuron:No such operator neuron::forward_v2_0
Traceback (most recent call last):
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 244, in trace
    return create_runnable(metaneff, neff, preprocessor, postprocessor, output_tensors, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 414, in create_runnable
    output_tensors
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 388, in create_runnable_v2
    forward_func = eval('torch.ops.neuron.forward_v2_{}'.format(len(output_tensors)))
  File "<string>", line 1, in <module>
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator neuron::forward_v2_0
INFO:Neuron:Compiling function _NeuronGraph$1521 with neuron-cc
INFO:Neuron:Compiling with command line: '/workspace/.pyenv/versions/inferentia_conversion/bin/neuron-cc compile /tmp/tmper2fvpx4/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmper2fvpx4/graph_def.neff --io-config {"inputs": {"0:0": [[1, 7, 4, 1], "float32"], "1:0": [[1, 7, 3, 1], "float32"], "2:0": [[1, 4, 7, 1], "float32"], "3:0": [[1, 4, 4, 1], "float32"], "4:0": [[1, 4, 3, 1], "float32"], "5:0": [[1, 3, 7, 1], "float32"], "6:0": [[1, 3, 4, 1], "float32"], "7:0": [[1, 3, 3, 1], "float32"]}, "outputs": []} --verbose 35'
.
Compiler status PASS
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1521; falling back to native python function call
ERROR:Neuron:No such operator neuron::forward_v2_0
Traceback (most recent call last):
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 244, in trace
    return create_runnable(metaneff, neff, preprocessor, postprocessor, output_tensors, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 414, in create_runnable
    output_tensors
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 388, in create_runnable_v2
    forward_func = eval('torch.ops.neuron.forward_v2_{}'.format(len(output_tensors)))
  File "<string>", line 1, in <module>
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator neuron::forward_v2_0
INFO:Neuron:Compiling function _NeuronGraph$1522 with neuron-cc
INFO:Neuron:Compiling with command line: '/workspace/.pyenv/versions/inferentia_conversion/bin/neuron-cc compile /tmp/tmpdhv_yltf/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpdhv_yltf/graph_def.neff --io-config {"inputs": {"0:0": [[1, 7, 4, 1], "float32"], "1:0": [[1, 7, 3, 1], "float32"], "2:0": [[1, 4, 7, 1], "float32"], "3:0": [[1, 4, 4, 1], "float32"], "4:0": [[1, 4, 3, 1], "float32"], "5:0": [[1, 3, 7, 1], "float32"], "6:0": [[1, 3, 4, 1], "float32"], "7:0": [[1, 3, 3, 1], "float32"]}, "outputs": []} --verbose 35'
.
Compiler status PASS
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$1522; falling back to native python function call
ERROR:Neuron:No such operator neuron::forward_v2_0
Traceback (most recent call last):
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/convert.py", line 389, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 244, in trace
    return create_runnable(metaneff, neff, preprocessor, postprocessor, output_tensors, **kwargs)
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 414, in create_runnable
    output_tensors
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch_neuron/decorators.py", line 388, in create_runnable_v2
    forward_func = eval('torch.ops.neuron.forward_v2_{}'.format(len(output_tensors)))
  File "<string>", line 1, in <module>
  File "/workspace/.pyenv/versions/inferentia_conversion/lib/python3.7/site-packages/torch/_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator neuron::forward_v2_0
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 1813, compiled = 2, percent compiled = 0.11%
INFO:Neuron:The neuron partitioner created 6 sub-graphs
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 6, Percent of model sub-graphs successfully compiled = 16.7%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::layer_norm: 1
INFO:Neuron: => aten::transpose: 1
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 437 [supported]
INFO:Neuron: => aten::_convolution: 1 [supported]
INFO:Neuron: => aten::adaptive_avg_pool1d: 1 [not supported]
INFO:Neuron: => aten::add: 47 [supported]
INFO:Neuron: => aten::cat: 3 [supported]
INFO:Neuron: => aten::constant_pad_nd: 12 [supported]
INFO:Neuron: => aten::contiguous: 53 [supported]
INFO:Neuron: => aten::div: 81 [supported]
INFO:Neuron: => aten::dropout: 37 [supported]
INFO:Neuron: => aten::eq: 5 [supported]
INFO:Neuron: => aten::fill_: 45 [supported]
INFO:Neuron: => aten::flatten: 1 [supported]
INFO:Neuron: => aten::gelu: 12 [supported]
INFO:Neuron: => aten::index: 12 [not supported]
INFO:Neuron: => aten::layer_norm: 28 [supported]
INFO:Neuron: => aten::linear: 75 [supported]
INFO:Neuron: => aten::masked_fill: 10 [supported]
INFO:Neuron: => aten::matmul: 24 [supported]
INFO:Neuron: => aten::mul: 17 [supported]
INFO:Neuron: => aten::ne: 5 [supported]
INFO:Neuron: => aten::permute: 89 [supported]
INFO:Neuron: => aten::remainder: 48 [supported]
INFO:Neuron: => aten::roll: 10 [not supported]
INFO:Neuron: => aten::rsub: 20 [supported]
INFO:Neuron: => aten::size: 235 [supported]
INFO:Neuron: => aten::slice: 228 [supported]
INFO:Neuron: => aten::softmax: 12 [supported]
INFO:Neuron: => aten::sub: 9 [supported]
INFO:Neuron: => aten::to: 5 [supported]
INFO:Neuron: => aten::transpose: 13 [supported]
INFO:Neuron: => aten::unsqueeze: 32 [supported]
INFO:Neuron: => aten::view: 199 [supported]
INFO:Neuron: => aten::zeros: 5 [supported]
WARNING:Neuron:torch.neuron.trace was unable to compile > 50% of the operators in the compiled model!
WARNING:Neuron:Please review the torch.neuron.analyze_model output and if you believe you are seeing a failure
WARNING:Neuron:Lodge an issue on https://github.com/aws/aws-neuron-sdk/issues if you believe the model is not compiling as expected
```

**Comment by heylamourding** [comment]
May I know whether it is still possible to convert?

**Comment by hannanjgaws** [comment]
Hi @heylamourding:

We can reproduce the issue you are seeing. We are working on a fix for this issue, and we will provide an update once we have made progress resolving the issue.

**Comment by heylamourding** [comment]
Thanks @hannanjgaws ! Looking forward to your solution.

**Comment by heylamourding** [comment]
Hi @hannanjgaws, any update on this issue?

**Comment by heylamourding** [comment]
Hi @hannanjgaws , is there any rough timeline to fix the above issue? Inferentia is quite crucial for us to perform cost reduction. Appreciate your help!

**Comment by heylamourding** [comment]
Hi @kamranjkhan, I have sent the email. Please check the mail box accordingly. Please let me know the rough timeline. Thanks!

**Comment by shebbur-aws** [comment]
Hi @heylamourding, we have a fix for this issue which will be released in one of our upcoming releases.

Thanks,
Shruthi.

**Comment by heylamourding** [comment]
Hi @shebbur-aws, thanks for the info! May I know when will the release happens?

**Comment by aws-maens** [comment]
Hi @heylamourding , currently we can't provide an ETA for a release.
As @shebbur-aws mentioned, we have a fix and if you are interested in testing the fix before it will be available in an official release you can contact the Neuron team at aws-neuron-support@amazon.com .
Thanks
Maen
