### ISSUE TITLE
Unable to reproduce seq2seq example from docs

### ISSUE THREAD

**Issue by mathcass** [aws-neuron/aws-neuron-sdk#631]
👋🏻 Hi, my ultimate goal is to compile my own T5-based models so that they work on Inferentia instances on AWS. As a test of this, I've been trying to run through this tutorial, 

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html

I'm trying to run this under AWS SageMaker Studio, using a standard ml.t3.medium instance. When I copy that notebook up to SageMaker and execute it, I'm unable to compile the model. I'm certain to install the versions specified in the initial cells, then restart the kernel before continuing. 

<details>
  <summary>Here's a stack trace that I see after running the cell to compile the model (click to toggle)</summary>
Here's a stack trace that I see after running the cell to compile the model
<br>

```
/opt/conda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:716: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert key_padding_mask is None or key_padding_mask.shape == (bsz, src_len)
/opt/conda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:718: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_weights.size() == (bsz * self.num_heads, tgt_len, src_len)
/opt/conda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:736: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_output.size() == (bsz * self.num_heads, tgt_len, self.head_dim)
/opt/conda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:287: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if torch.isinf(x).any() or torch.isnan(x).any():
INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuron-cc/neuron-cc-ops/neuron-cc-ops-pytorch.html)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 431, fused = 423, percent fused = 98.14%
/opt/conda/lib/python3.7/site-packages/torch/tensor.py:593: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/torch_neuron/ops/aten.py:1703: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:Neuron:Compiling function _NeuronGraph$200 with neuron-cc
INFO:Neuron:Compiling with command line: '/opt/conda/bin/neuron-cc compile /tmp/tmpzwjhjhwp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpzwjhjhwp/graph_def.neff --io-config {"inputs": {"0:0": [[1, 32, 512], "float32"], "1:0": [[1, 32], "bool"]}, "outputs": ["BartEncoder_1/aten_transpose_1/transpose:0"]} --verbose 35'
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$200; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/opt/conda/bin/neuron-cc compile /tmp/tmpzwjhjhwp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpzwjhjhwp/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 32, 512], "float32"], "1:0": [[1, 32], "bool"]}, "outputs": ["BartEncoder_1/aten_transpose_1/transpose:0"]}' --verbose 35
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch_neuron/convert.py", line 392, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_neuron/decorators.py", line 229, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/opt/conda/bin/neuron-cc compile /tmp/tmpzwjhjhwp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpzwjhjhwp/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 32, 512], "float32"], "1:0": [[1, 32], "bool"]}, "outputs": ["BartEncoder_1/aten_transpose_1/transpose:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 431, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 78 [supported]
INFO:Neuron: => aten::ScalarImplicit: 1 [supported]
INFO:Neuron: => aten::add: 13 [supported]
INFO:Neuron: => aten::add_: 36 [supported]
INFO:Neuron: => aten::arange: 1 [supported]
INFO:Neuron: => aten::bmm: 12 [supported]
INFO:Neuron: => aten::contiguous: 24 [supported]
INFO:Neuron: => aten::dropout: 25 [supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::eq: 1 [supported]
INFO:Neuron: => aten::layer_norm: 12 [supported]
INFO:Neuron: => aten::masked_fill: 6 [supported]
INFO:Neuron: => aten::matmul: 36 [supported]
INFO:Neuron: => aten::mul: 31 [supported]
INFO:Neuron: => aten::silu: 6 [supported]
INFO:Neuron: => aten::size: 25 [supported]
INFO:Neuron: => aten::softmax: 6 [supported]
INFO:Neuron: => aten::t: 36 [supported]
INFO:Neuron: => aten::transpose: 32 [supported]
INFO:Neuron: => aten::unsqueeze: 12 [supported]
INFO:Neuron: => aten::view: 36 [supported]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-1e9298af0728> in <module>
      8     num_beams=num_beams,
      9     max_encoder_length=max_encoder_length,
---> 10     max_decoder_length=max_decoder_length,
     11 )
     12 

<ipython-input-9-3003f82e9ee8> in trace(self, model, num_texts, num_beams, max_encoder_length, max_decoder_length)
     24         )
     25         encoder = NeuronEncoder(model)
---> 26         self.encoder = torch_neuron.trace(encoder, inputs)
     27 
     28         # Trace the decoder (with expanded inputs)

/opt/conda/lib/python3.7/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, single_fusion_ratio_threshold, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    193         logger.debug("skip_inference_context - trace with fallback at {}".format(get_file_and_line()))
    194         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 195     cu.stats_post_compiler(neuron_graph)
    196 
    197     # Wrap the compiled version of the model in a script module. Note that this is

/opt/conda/lib/python3.7/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    501         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    502             raise RuntimeError(
--> 503                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    504 
    505         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

</details>

Here's the notebook downloaded and attached to a gist, which includes that output as well as the package versions, https://gist.github.com/mathcass/3e1fe2e29b62895844e6f8f25bc0668e

Do you have any suggestions for debugging this? Or do you know what's going wrong here? I'm happy to provide any further information to help debug this.

Thank you. Any help here is appreciated.

**Comment by mathcass** [comment]
I started down this path while trying to adapt the code from this issue for my own purposes, https://github.com/aws-neuron/aws-neuron-sdk/issues/443 - When I couldn't get that working, I tried running through the example from the docs itself, only to find that I couldn't get them running.

**Comment by aws-mvaria** [comment]
Hello, we are working on updating the tutorial content which should address the issue you are seeing. We will update you as soon as the content is available.

**Comment by mathcass** [comment]
Hi @aws-mvaria, I was wondering if there were any updates at all? Or at least is there a brief explanation of the issue? (I'm happy to dig in with some pointers.) 

My biggest worry is that using these Seq2Seq models from Huggingface isn't supported any longer.

**Comment by mrnikwaws** [comment]
Hi @mathcass,

The MarianMT tutorial has been updated, so I think your original issue here should be resolved.  

Please note: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/model-architecture-fit.html:
 * inf1 (torch-neuron) is a poor hardware fit for these kinds of models  
 * trn1/inf2 (torch-neuronx) have active development for inference use cases (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/roadmap-readme.html#neuron-roadmap), with training currently supported.

Broadly speaking we are actively working on supporting Hugging Face LLMs, and hugging face is working on making them run efficiently on Neuron hardware: https://github.com/huggingface/optimum-neuron.

Please reopen the issue if the same problem persists, or open a new one if you have a different query.

**Comment by mathcass** [comment]
Thank you @mrnikwaws! I'm excited to see the new developments for Neuron. I'll take a look at inf2 since that is definitely new from the last time I looked. I appreciate you looping back around to notify me of the fix here.
