### ISSUE TITLE
Custom model using torch.flip does compile, but cannot infer

### ISSUE THREAD

**Issue by BayMinimum** [aws-neuron/aws-neuron-sdk#634]
Hi, I'm trying to compile my custom PyTorch model composed of embedding layer and MLP. The model uses custom embedding layer that accumulates the embedding weight before embedding lookup.

```py
import torch.neuron
from torch import nn
import torch.nn.functional as F


class CumulativeEmbedding(nn.Module):
    def __init__(self, num_embeddings, embedding_dim):
        super().__init__()
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
    
    def forward(self, x):
        cumulative_weight = torch.cumsum(torch.flip(self.embedding.weight, dims=(0,)), dim=0)
        return F.embedding(x.long(), cumulative_weight)


class Model(nn.Module):
    def __init__(self, num_embeddings, embedding_dim):
        super().__init__()
        self.embedding = CumulativeEmbedding(num_embeddings, embedding_dim)
        self.net = nn.Sequential(*(nn.Linear(embedding_dim, embedding_dim) for _ in range(2)))
    
    def forward(self, x):
        embeddings = self.embedding(x)
        return self.net(embeddings)


class Models(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, n_models):
        super().__init__()
        self.models = nn.ModuleList([Model(num_embeddings, embedding_dim) for _ in range(n_models)])
    
    def forward(self, x):
        return torch.cat([model(x) for model in self.models], dim=-1) 
```

The model does compile, but inference fails even with the same example input for trace.

```py
num_embeddings = 20
embedding_dim = 128
model = Models(num_embeddings, embedding_dim, 2)
example_input = (torch.rand(1, 128) * (num_embeddings - 1)).long()
print(model(example_input).shape)  # torch.Size([2, 128, 128])

model_neuron = torch.neuron.trace(
    model,
    example_inputs=[example_input],
    fallback=True,
    dynamic_batch_size=True,
    compiler_args=["--fast-math", "none"],
)  # Successfully compiles
print(model_neuron(example_input).shape)  # ERROR!
```

Model compile log:
```
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 21, compiled = 11, percent compiled = 52.38%
INFO:Neuron:The neuron partitioner created 4 sub-graphs
INFO:Neuron:Neuron successfully compiled 3 sub-graphs, Total fused subgraphs = 4, Percent of model sub-graphs successfully compiled = 75.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::add_: 2
INFO:Neuron: => aten::cat: 1
INFO:Neuron: => aten::cumsum: 2
INFO:Neuron: => aten::flip: 2
INFO:Neuron: => aten::matmul: 2
INFO:Neuron: => aten::t: 2
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::add_: 2 [supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::matmul: 2 [supported]
INFO:Neuron: => aten::t: 2 [supported]
INFO:Neuron: => aten::to: 2 [supported]
```

Traceback:
```
Traceback (most recent call last):
  File "cumsum_demo.py", line 51, in <module>
    print(model_neuron(example_input).shape)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/decorators.py(381): forward
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(580): __call__
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(209): run_op
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(198): __call__
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/runtime.py(69): forward
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_trace.py(934): trace_module
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_trace.py(733): trace
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/tensorboard.py(324): tb_parse
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/tensorboard.py(550): tb_graph
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/decorators.py(491): maybe_generate_tb_graph_def
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py(552): maybe_determine_names_from_tensorboard
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py(211): trace
cumsum_demo.py(44): <module>
RuntimeError: Inconsistent batch sizes found on inputs. All batch tensors must have the same dim 0 size.
```
embedding is not supported (which was expected), thus the model is split into subgraphs -- before embedding and after it (which was also expected). But why does it fail to infer?

Note: I've found that removing torch.flip operation in the model or disabling dynamic batching makes the error disappear.

Neuron related package version in my environment:
```
aws-neuronx-runtime-discovery==2.9
libneuronxla==0.1.472
neuron-cc==1.13.5.0+7dcf000a6
neuronperf==1.6.1.0+a63399af5
neuronx-cc==2.2.0.73+0af5a171c
neuronx-hwm==2.2.0.3+58e9eca77
torch==1.8.1
torch-neuron==1.8.1.2.5.8.0
torch-neuronx==1.11.0.1.2.0
torch-xla==1.11.0+torchneuron3
```

**Comment by jeffhataws** [comment]
Thanks for filing. We are looking at this and will get back to you.

**Comment by hannanjgaws** [comment]
Hi @BayMinimum:

We were able to reproduce the error you’re seeing. Models that contain unsupported operators, such as `aten::embedding`, are partitioned to run on CPU. During partitioning, additional operators that track shapes are also sent to CPU. However, there’s an issue in our partitioner where the input batch sizes are not properly recorded at inference time when these shape operators are sent to CPU. This is [known issue](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/torch/torch-neuron/torch-neuron.html#dynamic-batching) and is being worked on.

The easiest way to fix this issue is to compile `aten::embedding` instead of partitioning it to CPU. This can be accomplished by using the `fallback=False` flag during compilation to compile all operators in your model:

```
model_neuron = torch_neuron.trace(
    model,
    example_inputs=[example_input],
    fallback=False,
    dynamic_batch_size=True,
    compiler_args=["--fast-math", "none"],
)
```

Note that this model is a special case where the positional embedding table is relatively small. Embedding operator support is disabled by default because there are many cases where moving this to device causes worse performance.

Can you retry compiling your model using `fallback=False` to see if it resolves the error you’re seeing?

**Comment by BayMinimum** [comment]
Thanks for your prompt response. I've retried compiling the model using `fallback=False` and it did resolve the error I've seen.

Closing this issue since using `fallback=False` works for my case. I'll look forward for the partitioner issue fix!
