### ISSUE TITLE
[Hugging Face] neuron compiler fails on tracing DeBERTa v1 and v2 models on INF1

### ISSUE THREAD

**Issue by JingyaHuang** [aws-neuron/aws-neuron-sdk#642]
* System information
```
OS unbuntu 20.04.5 LTS
```
```
dmlc-tvm                           1.13.0.0+0
neuron-cc                          1.13.5.0+7dcf000a6
torch                              1.12.1
torch-neuron                       1.12.1.2.5.8.0
torchvision                        0.13.1
transformers                       4.26.1
```
```
aws-neuronx-dkms/unknown,now 2.6.33.0 amd64 [installed,upgradable to: 2.7.33.0]
aws-neuronx-tools/unknown,now 2.6.1.0 amd64 [installed,upgradable to: 2.8.2.0]
```

<details><summary>Error log</summary>

```
Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at hf-internal-testing/tiny-random-DebertaModel and are newly initialized: ['pooler.dense.weight', 'classifier.weight', 'pooler.dense.bias', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py:664: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  scale = torch.sqrt(torch.tensor(query_layer.size(-1), dtype=torch.float) * scale_factor)
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py:664: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  scale = torch.sqrt(torch.tensor(query_layer.size(-1), dtype=torch.float) * scale_factor)
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py:121: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  output = input.masked_fill(rmask, torch.tensor(torch.finfo(input.dtype).min))
WARNING:Neuron: Found Python static code known as PythonOp. Static methods are not torch operators and hence aren't compilable by torch_neuron which causes graph partitioning and limits performance optimizations by neuron.
WARNING:Neuron: Your PythonOp is in: /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py(678): forward
WARNING:Neuron: Consider replacing this static code with a non-pythonOp code to potentially improve performance.

WARNING:Neuron: Found Python static code known as PythonOp. Static methods are not torch operators and hence aren't compilable by torch_neuron which causes graph partitioning and limits performance optimizations by neuron.
WARNING:Neuron: Your PythonOp is in: /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py(678): forward
WARNING:Neuron: Consider replacing this static code with a non-pythonOp code to potentially improve performance.

WARNING:Neuron: Found Python static code known as PythonOp. Static methods are not torch operators and hence aren't compilable by torch_neuron which causes graph partitioning and limits performance optimizations by neuron.
WARNING:Neuron: Your PythonOp is in: /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py(678): forward
WARNING:Neuron: Consider replacing this static code with a non-pythonOp code to potentially improve performance.

WARNING:Neuron: Found Python static code known as PythonOp. Static methods are not torch operators and hence aren't compilable by torch_neuron which causes graph partitioning and limits performance optimizations by neuron.
WARNING:Neuron: Your PythonOp is in: /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py(678): forward
WARNING:Neuron: Consider replacing this static code with a non-pythonOp code to potentially improve performance.

WARNING:Neuron: Found Python static code known as PythonOp. Static methods are not torch operators and hence aren't compilable by torch_neuron which causes graph partitioning and limits performance optimizations by neuron.
WARNING:Neuron: Your PythonOp is in: /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/deberta/modeling_deberta.py(678): forward
WARNING:Neuron: Consider replacing this static code with a non-pythonOp code to potentially improve performance.

INFO:Neuron:There are 8 ops of 2 different types in the TorchScript that are not compiled by neuron-cc: prim::PythonOp, aten::embedding, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuron-cc/neuron-cc-ops/neuron-cc-ops-pytorch.html)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 416, fused = 413, percent fused = 99.28%
WARNING:tensorflow:From /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/ops/aten.py:2277: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$294 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpnzrrbpjs/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpnzrrbpjs/graph_def.neff --io-config {"inputs": {"0:0": [[2, 18], "int64"]}, "outputs": ["DebertaModel_4/DebertaEmbeddings_2/aten_slice_3/StridedSlice:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$295 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmptvy9tiit/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmptvy9tiit/graph_def.neff --io-config {"inputs": {"0:0": [[2, 18, 32], "float32"], "inp.1:0": [[1, 18, 32], "float32"], "inp:0": [[2, 18, 32], "float32"], "3:0": [[2, 18], "int64"]}, "outputs": ["DebertaModel_4/DebertaEmbeddings_2/aten_mul/mul:0", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_24/DebertaAttention_3/DisentangledSelfAttention_2/aten_chunk/split:2", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_24/DebertaAttention_3/DisentangledSelfAttention_2/aten_matmul/MatMul:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$296 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpm6w1k8ko/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpm6w1k8ko/graph_def.neff --io-config {"inputs": {"0:0": [[2, 18], "int64"]}, "outputs": ["DebertaModel_4/DebertaEncoder_3/aten_to/Cast:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$297 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmp9gswgsn5/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp9gswgsn5/graph_def.neff --io-config {"inputs": {"0:0": [[2, 4, 18, 8], "float32"], "1:0": [[2, 4, 18, 18], "float32"], "2:0": [[2, 18, 32], "float32"]}, "outputs": ["DebertaModel_4/DebertaEncoder_3/DebertaLayer_24/DebertaOutput_5/DebertaLayerNorm_7/aten_add_1/add:0", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_25/DebertaAttention_3/DisentangledSelfAttention_2/aten_chunk/split:2", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_25/DebertaAttention_3/DisentangledSelfAttention_2/aten_matmul/MatMul:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$298 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpn8e551ay/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpn8e551ay/graph_def.neff --io-config {"inputs": {"0:0": [[2, 4, 18, 8], "float32"], "1:0": [[2, 4, 18, 18], "float32"], "2:0": [[2, 18, 32], "float32"]}, "outputs": ["DebertaModel_4/DebertaEncoder_3/DebertaLayer_25/DebertaOutput_5/DebertaLayerNorm_7/aten_add_1/add:0", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_26/DebertaAttention_3/DisentangledSelfAttention_2/aten_chunk/split:2", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_26/DebertaAttention_3/DisentangledSelfAttention_2/aten_matmul/MatMul:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$299 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpogvmifyw/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpogvmifyw/graph_def.neff --io-config {"inputs": {"0:0": [[2, 4, 18, 8], "float32"], "1:0": [[2, 4, 18, 18], "float32"], "2:0": [[2, 18, 32], "float32"]}, "outputs": ["DebertaModel_4/DebertaEncoder_3/DebertaLayer_26/DebertaOutput_5/DebertaLayerNorm_7/aten_add_1/add:0", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_27/DebertaAttention_3/DisentangledSelfAttention_2/aten_chunk/split:2", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_27/DebertaAttention_3/DisentangledSelfAttention_2/aten_matmul/MatMul:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$300 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpqjn427zi/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqjn427zi/graph_def.neff --io-config {"inputs": {"0:0": [[2, 4, 18, 8], "float32"], "1:0": [[2, 4, 18, 18], "float32"], "2:0": [[2, 18, 32], "float32"]}, "outputs": ["DebertaModel_4/DebertaEncoder_3/DebertaLayer_27/DebertaOutput_5/DebertaLayerNorm_7/aten_add_1/add:0", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_28/DebertaAttention_3/DisentangledSelfAttention_2/aten_chunk/split:2", "DebertaModel_4/DebertaEncoder_3/DebertaLayer_28/DebertaAttention_3/DisentangledSelfAttention_2/aten_matmul/MatMul:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$301 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpilyduutw/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpilyduutw/graph_def.neff --io-config {"inputs": {"0:0": [[2, 4, 18, 8], "float32"], "1:0": [[2, 4, 18, 18], "float32"], "2:0": [[2, 18, 32], "float32"]}, "outputs": ["Linear_7/aten_linear/Add:0"]} --fast-math none --verbose 35'
.
Compiler status PASS
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 416, compiled = 413, percent compiled = 99.28%
INFO:Neuron:The neuron partitioner created 8 sub-graphs
INFO:Neuron:Neuron successfully compiled 8 sub-graphs, Total fused subgraphs = 8, Percent of model sub-graphs successfully compiled = 100.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 41
INFO:Neuron: => aten::add: 42
INFO:Neuron: => aten::add_: 2
INFO:Neuron: => aten::chunk: 5
INFO:Neuron: => aten::contiguous: 5
INFO:Neuron: => aten::detach: 10
INFO:Neuron: => aten::div: 16
INFO:Neuron: => aten::gelu: 6
INFO:Neuron: => aten::linear: 22
INFO:Neuron: => aten::matmul: 10
INFO:Neuron: => aten::mean: 22
INFO:Neuron: => aten::mul: 18
INFO:Neuron: => aten::permute: 20
INFO:Neuron: => aten::pow: 11
INFO:Neuron: => aten::select: 1
INFO:Neuron: => aten::size: 46
INFO:Neuron: => aten::slice: 13
INFO:Neuron: => aten::sqrt: 16
INFO:Neuron: => aten::squeeze: 1
INFO:Neuron: => aten::sub: 22
INFO:Neuron: => aten::to: 35
INFO:Neuron: => aten::transpose: 5
INFO:Neuron: => aten::unsqueeze: 24
INFO:Neuron: => aten::view: 20
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::embedding: 3 [not supported]
Traceback (most recent call last):
  File "test_min.py", line 18, in <module>
    export(
  File "/home/ubuntu/optimum-neuron/optimum/neuron/exporter/convert.py", line 150, in export
    export_neuron(model, config, output)
  File "/home/ubuntu/optimum-neuron/optimum/neuron/exporter/convert.py", line 271, in export_neuron
    neuron_model.save(output)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 714, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: 
Could not export Python function call 'XSoftmax'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/native_ops/prim.py(46): PythonOp
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(342): __call__
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(209): run_op
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(198): __call__
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/runtime.py(69): forward
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_trace.py(967): trace_module
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_trace.py(750): trace
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/tensorboard.py(324): tb_parse
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/tensorboard.py(550): tb_graph
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/decorators.py(491): maybe_generate_tb_graph_def
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py(552): maybe_determine_names_from_tensorboard
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py(211): trace
/home/ubuntu/optimum-neuron/optimum/neuron/exporter/convert.py(270): export_neuron
/home/ubuntu/optimum-neuron/optimum/neuron/exporter/convert.py(150): export
test_min.py(18): <module>
```

</details>

Short version:
```
Could not export Python function call 'XSoftmax'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? 
```

* Reproduction
```python
import copy
import os
from pathlib import Path

from transformers import AutoModelForSequenceClassification

from optimum.exporters.neuron import export, validate_model_outputs
from optimum.exporters.neuron.model_configs import DebertaNeuronConfig

model_id = "hf-internal-testing/tiny-random-DebertaModel"
model = AutoModelForSequenceClassification.from_pretrained(model_id)
reference_model = copy.deepcopy(model)
neuron_config = DebertaNeuronConfig(
    config=model.config, task="sequence-classification", batch_size=2, sequence_length=18
)
output_path = Path("model.pt")

export(
    model=model,
    config=neuron_config,
    output=output_path,
    auto_cast="none",
)

run = 10
value_failures = []
for _ in range(run):
    validate_model_outputs(
        config=neuron_config,
        reference_model=reference_model,
        neuron_model_path=output_path,
        neuron_named_outputs=["logits"],
    )
```

It seems that the tracing failed for deberta’s masked softmax as it is a custom auto grad function. As with neuron-cc compiler is for inference and has no need for supporting backward, could replace it with:

__Hacky fix__
```python
class XSoftmax():
    @staticmethod
    def apply(input, mask, dim):
        rmask = ~(mask.to(torch.bool))

        output = input.masked_fill(rmask, torch.tensor(torch.finfo(input.dtype).min))
        output = torch.softmax(output, dim)
        output.masked_fill_(rmask, 0)

        return output
```

`XDropout` has the same issue, but with I guess with `model.eval()` it would be fine.

__Possible solution__

If it makes sense, we could add a model patcher for models with custom autograd functions in `optimum-neuron`. Or does the Annapurna team has any better suggestion?

**Comment by JingyaHuang** [comment]
Link the same issue in optimum-neuron: https://github.com/huggingface/optimum-neuron/issues/17

**Comment by aws-donkrets** [comment]
Thanks for noting this issue. We will investigate and update this ticket when we have more information.

**Comment by waring92** [comment]
@hannanjgaws 
please, can you share the forward-only `XSoftmax` class code?
