### ISSUE TITLE
[Hugging Face] neuron-cc fails on tracing Distilbert model on multiple-choice task on INF1

### ISSUE THREAD

**Issue by JingyaHuang** [aws-neuron/aws-neuron-sdk#645]
* System information
```
OS unbuntu 20.04.5 LTS
```
```
dmlc-tvm                           1.13.0.0+0
neuron-cc                          1.13.5.0+7dcf000a6
torch                              1.12.1
torch-neuron                       1.12.1.2.5.8.0
torchvision                        0.13.1
transformers                       4.26.1
```
```
aws-neuronx-dkms/unknown,now 2.6.33.0 amd64 [installed,upgradable to: 2.7.33.0]
aws-neuronx-tools/unknown,now 2.6.1.0 amd64 [installed,upgradable to: 2.8.2.0]
```

<details><summary>Error log</summary>

```
Some weights of DistilBertForMultipleChoice were not initialized from the model checkpoint at hf-internal-testing/tiny-random-DistilBertModel and are newly initialized: ['pre_classifier.weight', 'classifier.bias', 'pre_classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py:218: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask, torch.tensor(torch.finfo(scores.dtype).min)
INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuron-cc/neuron-cc-ops/neuron-cc-ops-pytorch.html)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 229, fused = 220, percent fused = 96.07%
WARNING:tensorflow:From /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/ops/aten.py:1703: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$248 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpi3pgxstp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpi3pgxstp/graph_def.neff --io-config {"inputs": {"0:0": [[2, 3, 18], "int64"], "1:0": [[2, 3, 18], "int64"], "2:0": [[6, 18, 32], "float32"], "3:0": [[1, 18, 32], "float32"]}, "outputs": ["aten_view_1/Reshape:0"]} --fast-math none --verbose 35'
.03/23/2023 01:56:10 PM ERROR 88826 [IRVerifier]: Tensor has undef value TongaSB partitions[0] uint8 %DistilBertModel_22/Transformer_3/TransformerBlock_14/MultiHeadSelfAttention_4/aten_view_3/Reshape:0[18, 6]
03/23/2023 01:56:10 PM ERROR 88826 [Tensorizer]: Transformation error on operator: Linear_34/aten_linear/MatMul
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: ***************************************************************
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:  An Internal Compiler Error has occurred
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: ***************************************************************
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: 
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Error message:  Incorrect IR by <class 'neuroncc.starfish.penguin.targets.tonga.passes.LegalizeTongaType.LegalizeTongaType'>
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: 
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Error class:    AssertionError
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Error location: Unknown
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Command line:   /home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpi3pgxstp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpi3pgxstp/graph_def.neff --io-config '{"inputs": {"0:0": [[2, 3, 18], "int64"], "1:0": [[2, 3, 18], "int64"], "2:0": [[6, 18, 32], "float32"], "3:0": [[1, 18, 32], "float32"]}, "outputs": ["aten_view_1/Reshape:0"]}' --fast-math none --verbose 35
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: 
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Internal details:
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 224, in neuroncc.driver.CommandDriver.CommandDriver.run
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 576, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 554, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 558, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 427, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 377, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 378, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 388, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 358, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend.tensorize
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 47, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 48, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 69, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/Compile.py", line 262, in neuroncc.starfish.penguin.Compile.compile_cu
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 378, in neuroncc.starfish.penguin.DotTransform.PassManager.transformFunction
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 124, in neuroncc.starfish.penguin.DotTransform.DotTransform.runOnFunction
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 178, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 160, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 186, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 188, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 189, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 206, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 207, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 289, in neuroncc.starfish.penguin.DotTransform.DotTransform.transformFunction
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/Tonga.py", line 352, in neuroncc.starfish.penguin.targets.tonga.Tonga.TongaLowering.verify
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 275, in neuroncc.starfish.penguin.DotTransform.DotTransform.verify
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: 
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Version information:
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   Neuron Compiler version 1.13.5.0+7dcf000a6
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   HWM version 1.13.0.0-0
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   NEFF version Dynamic
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   TVM version 1.13.0.0+0
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   NumPy version 1.18.5
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   MXNet not available
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]:   TF not available
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: 
03/23/2023 01:56:11 PM ERROR 88826 [neuron-cc]: Artifacts stored in: /tmp/tmpi3pgxstp

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$248; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpi3pgxstp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpi3pgxstp/graph_def.neff --io-config '{"inputs": {"0:0": [[2, 3, 18], "int64"], "1:0": [[2, 3, 18], "int64"], "2:0": [[6, 18, 32], "float32"], "3:0": [[1, 18, 32], "float32"]}, "outputs": ["aten_view_1/Reshape:0"]}' --fast-math none --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py", line 391, in op_converter
    neuron_function = self.subgraph_compiler(
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/decorators.py", line 228, in trace
    raise subprocess.SubprocessError(
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmpi3pgxstp/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpi3pgxstp/graph_def.neff --io-config '{"inputs": {"0:0": [[2, 3, 18], "int64"], "1:0": [[2, 3, 18], "int64"], "2:0": [[6, 18, 32], "float32"], "3:0": [[1, 18, 32], "float32"]}, "outputs": ["aten_view_1/Reshape:0"]}' --fast-math none --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 229, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 34 [supported]
INFO:Neuron: => aten::add: 11 [supported]
INFO:Neuron: => aten::contiguous: 5 [supported]
INFO:Neuron: => aten::detach: 5 [supported]
INFO:Neuron: => aten::div: 5 [supported]
INFO:Neuron: => aten::dropout: 12 [supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::eq: 5 [supported]
INFO:Neuron: => aten::expand_as: 5 [supported]
INFO:Neuron: => aten::gelu: 5 [supported]
INFO:Neuron: => aten::layer_norm: 11 [supported]
INFO:Neuron: => aten::linear: 32 [supported]
INFO:Neuron: => aten::masked_fill: 5 [supported]
INFO:Neuron: => aten::matmul: 10 [supported]
INFO:Neuron: => aten::relu: 1 [supported]
INFO:Neuron: => aten::select: 1 [supported]
INFO:Neuron: => aten::size: 14 [supported]
INFO:Neuron: => aten::slice: 3 [supported]
INFO:Neuron: => aten::softmax: 5 [supported]
INFO:Neuron: => aten::to: 5 [supported]
INFO:Neuron: => aten::transpose: 25 [supported]
INFO:Neuron: => aten::view: 28 [supported]
Traceback (most recent call last):
  File "test_neuron_export.py", line 29, in <module>
    export(
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py", line 155, in export
    return export_neuron(model, config, output, auto_cast, auto_cast_type, disable_fast_relayout)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py", line 277, in export_neuron
    neuron_model = neuron.trace(model, dummy_inputs, compiler_args=compiler_args)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py", line 195, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py", line 502, in stats_post_compiler
    raise RuntimeError(
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

</details>

Short version:
```
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

* Reproduction
```python
import copy
from pathlib import Path

from transformers import AutoModelForMultipleChoice

from optimum.exporters.neuron import export, validate_model_outputs
from optimum.exporters.neuron.model_configs import DistilBertNeuronConfig

model_id = "hf-internal-testing/tiny-random-DistilBertModel"
model = AutoModelForMultipleChoice.from_pretrained(model_id)
reference_model = copy.deepcopy(model)
neuron_config = DistilBertNeuronConfig(
    config=model.config, task="multiple-choice", batch_size=2, sequence_length=18, num_choices=3
)
output_path = Path("model.pt")

export(
    model=model,
    config=neuron_config,
    output=output_path,
    auto_cast="none",
    # auto_cast_type="fp16",
    # disable_fast_relayout=False,
)

# Validation
run = 1
value_failures = []
for _ in range(run):
    validate_model_outputs(
        config=neuron_config,
        reference_model=reference_model,
        neuron_model_path=output_path,
        neuron_named_outputs=neuron_config.outputs,
    )
```

And a little bit more context, I also tested with BERT on the multiple-choice task, as well as DistilBERT on some other tasks(classifications, masked-lm...), and the tracing was successful.

**Comment by JingyaHuang** [comment]
Hi @awsrjh, I am closing this issue as its root problem is the same as #641. Thanks a lot for helping me find the cause!
