### ISSUE TITLE
How to compile seq2seq model using torch_neuronx

### ISSUE THREAD

**Issue by yzGao22** [aws-neuron/aws-neuron-sdk#653]
Hi team, 

We are trying to compile a sequence-to-sequence model using torch_neuronx. The code works fine with 'torch_neuron' and we can get the neuron traced model successfully. But when using torch_neuronx, it outputs 'Input tensor is not an XLA tensor: torch.FloatTensor'. We tried to relocate the tensors to XLA devices but didn't help.

Below is the code to reproduce the problem:
```
import os

import torch
import numpy as np
import pandas as pd
from typing import Any, Optional, cast
from torch.nn import functional as F

from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainer, Seq2SeqTrainingArguments, AutoTokenizer
from transformers import BartTokenizer, PegasusTokenizer, MT5Tokenizer
from transformers import BartForConditionalGeneration, PegasusForConditionalGeneration, MT5Model, MT5ForConditionalGeneration
from transformers import GenerationMixin, AutoConfig
from transformers.modeling_outputs import Seq2SeqLMOutput, BaseModelOutput
from transformers.modeling_utils import PreTrainedModel

import torch_neuronx
import torch_xla.core.xla_model as xm
```
```
# BRIO and other BART / PEGASUS based encoder&decoder
class PaddedEncoder(torch.nn.Module):

    def __init__(self, model):
        super().__init__()
        self.encoder = model.model.encoder
        self.main_input_name = 'input_ids'

    def forward(self, input_ids, attention_mask):
        return self.encoder(input_ids, attention_mask=attention_mask, return_dict=False)


class PaddedDecoder(torch.nn.Module):

    def __init__(self, model):
        super().__init__()
        self.weight = model.model.shared.weight.clone().detach()
        self.bias = model.final_logits_bias.clone().detach()
        self.decoder = model.model.decoder

    def forward(self, input_ids, attention_mask, encoder_outputs, index):

        # Invoke the decoder
        hidden, = self.decoder(
            input_ids=input_ids.to(xm.xla_device()),
            encoder_hidden_states=encoder_outputs.to(xm.xla_device()),
            encoder_attention_mask=attention_mask.to(xm.xla_device()),
            return_dict=False,
            use_cache=False,
        )

        _, n_length, _ = hidden.shape

        # Create selection mask
        mask = torch.arange(n_length, dtype=torch.float32).to(xm.xla_device()) == index
        mask = mask.view(1, -1, 1)

        # Broadcast mask
        masked = torch.multiply(hidden, mask)

        # Reduce along 1st dimension
        hidden = torch.sum(masked, 1, keepdims=True)

        # Compute final linear layer for token probabilities
        logits = F.linear(
            hidden,
            self.weight,
            bias=self.bias
        )
```
```
class PaddedGenerator(PreTrainedModel, GenerationMixin):

    @classmethod
    def from_model(cls, model):
        generator = cls(model.config)
        if model.config.architectures[0] == 'MT5ForConditionalGeneration':
            generator.encoder = PaddedEncoderMT5(model)
            generator.decoder = PaddedDecoderMT5(model).to(xm.xla_device())
        else:
            generator.encoder = PaddedEncoder(model).to(xm.xla_device())
            generator.decoder = PaddedDecoder(model).to(xm.xla_device())
        return generator.to(xm.xla_device())
        #return generator

    def prepare_inputs_for_generation(
            self,
            input_ids,
            encoder_outputs=None,
            attention_mask=None,
            **kwargs,
    ):
        # Pad the inputs for Neuron
        current_length = input_ids.shape[1]
        pad_size = self.config.max_length - current_length
        return dict(
            input_ids=F.pad(input_ids, (0, pad_size)),
            attention_mask=attention_mask.to(xm.xla_device()),
            encoder_outputs=encoder_outputs.last_hidden_state.to(xm.xla_device()),
            current_length=torch.tensor(current_length - 1,device=xm.xla_device()),
        )

    def get_encoder(self):
        def encode(input_ids, attention_mask, **kwargs):
            output, = self.encoder(input_ids, attention_mask)
            return BaseModelOutput(
                last_hidden_state=output,
            )
        return encode

    def forward(self, input_ids, attention_mask, encoder_outputs, current_length, **kwargs):
        logits = self.decoder(input_ids, attention_mask, encoder_outputs, current_length)
        return Seq2SeqLMOutput(logits=logits)
    
    # ------------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------------
    
    @property
    def device(self):  # Attribute required by beam search
        return torch.device(xm.xla_device())
        #return torch.device('cpu')

    def save_pretrained(self, directory):
        if os.path.isfile(directory):
            print(f"Provided path ({directory}) should be a directory, not a file")
            return
        os.makedirs(directory, exist_ok=True)
        torch.jit.save(self.encoder, os.path.join(directory, 'encoder.pt'))
        torch.jit.save(self.decoder, os.path.join(directory, 'decoder.pt'))
        self.config.save_pretrained(directory)

    @classmethod
    def from_pretrained(cls, directory):
        config = AutoConfig.from_pretrained(directory)
        obj = cls(config)
        obj.encoder = torch.jit.load(os.path.join(directory, 'encoder.pt'))
        obj.decoder = torch.jit.load(os.path.join(directory, 'decoder.pt'))
        setattr(obj.encoder, 'main_input_name', 'input_ids')  # Attribute required by beam search
        return obj
```
```
def trace(model, num_texts, num_beams, max_decoder_length, max_encoder_length):
    """
    Traces the encoder and decoder modules for use on Neuron.

    This function fixes the network to the given sizes. Once the model has been
    compiled to a given size, the inputs to these networks must always be of
    fixed size.

    Args:
        model (PaddedGenerator): The padded generator to compile for Neuron
        num_texts (int): The number of input texts to translate at once
        num_beams (int): The number of beams to compute per text
        max_decoder_length (int): The maximum number of tokens to be generated
        max_encoder_length (int): The maximum number of input tokens that will be encoded
    """

    # Trace the encoder
    inputs = (
        torch.ones((num_texts, max_encoder_length), dtype=torch.long,device=xm.xla_device()),
        torch.ones((num_texts, max_encoder_length), dtype=torch.long,device=xm.xla_device()),
    )
    #for item in inputs:
        #print('device encoder: ',item.device)
    encoder = torch_neuronx.trace(model.encoder, inputs)

    # Trace the decoder (with expanded inputs)
    batch_size = num_texts * num_beams
    inputs = (
        torch.ones((batch_size, max_decoder_length), dtype=torch.long,device=xm.xla_device()),
        torch.ones((batch_size, max_encoder_length), dtype=torch.long,device=xm.xla_device()),
        torch.ones(batch_size*max_encoder_length, model.config.d_model, dtype=torch.float,device=xm.xla_device()),
        torch.tensor(0,device=xm.xla_device()),
    )
    for item in inputs:
        print('device decoder: ',item.device)
        
    decoder = torch_neuronx.trace(model.decoder, inputs)

    traced = PaddedGenerator(model.config)
    traced.encoder = encoder
    traced.decoder = decoder
    setattr(encoder, 'main_input_name', 'input_ids')  # Attribute required by beam search
    return traced
```
```
model_directory = {"MT5": "csebuetnlp/mT5_multilingual_XLSum",
                   "BRIO": "Yale-LILY/brio-cnndm-uncased",
                   "BART": "knkarthick/MEETING_SUMMARY",                 # the latest version of BART
                   "PEGASUS": "google/pegasus-cnn_dailymail",
                  }

model_name = "BRIO"                       # model you want to neuron trace
num_texts = 1                             # Number of input texts to decode
num_beams = 1                            # Number of beams per input text
max_encoder_length = 128                 # Maximum input token length, should match with the decoder length 
max_decoder_length = 128                   # Maximum output token length

# load pretrained model and tokenizer
if model_name == "BRIO" or model_name == "BART":
    model = BartForConditionalGeneration.from_pretrained(model_directory[model_name])
    tokenizer = BartTokenizer.from_pretrained(model_directory[model_name])

elif model_name == "PEGASUS":
    model = PegasusForConditionalGeneration.from_pretrained(model_directory[model_name])
    tokenizer = PegasusTokenizer.from_pretrained(model_directory[model_name])
    
elif model_name == "MT5":
    model = AutoModelForSeq2SeqLM.from_pretrained(model_directory[model_name])
    tokenizer = AutoTokenizer.from_pretrained(model_directory[model_name])

model.config.max_length = max_decoder_length
```
```
# Neuron Execution
paddded_model = PaddedGenerator.from_model(model)
neuron_model = trace(paddded_model, num_texts, num_beams, max_decoder_length, max_encoder_length)
```

Below is the error massage:
```
RuntimeError                              Traceback (most recent call last)
Cell In[7], line 3
      1 # Neuron Execution
      2 paddded_model = PaddedGenerator.from_model(model)
----> 3 neuron_model = trace(paddded_model, num_texts, num_beams, max_decoder_length, max_encoder_length)

Cell In[4], line 37, in trace(model, num_texts, num_beams, max_decoder_length, max_encoder_length)
     34 for item in inputs:
     35     print('device decoder: ',item.device)
---> 37 decoder = torch_neuronx.trace(model.decoder, inputs)
     39 traced = PaddedGenerator(model.config)
     40 traced.encoder = encoder

File [~/.local/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:242](https://vscode-remote+ssh-002dremote-002bsumm.vscode-resource.vscode-cdn.net/home/ubuntu/datascience/text_summarization/Neuron/~/.local/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:242), in trace(func, example_inputs, states, compiler_workdir, compiler_args, options)
    240 # Convert the function to a HloProto message
    241 with torch_neuronx.contexts.mock_neuron_cores():
--> 242     hlo, input_parameter_names, constant_parameter_tensors, flattener, packer = xla_trace(
    243         func,
    244         example_inputs,
    245         states,
    246     )
    248 # Create a temporary directory for artifacts if none is specified
    249 context = nullcontext()
...
	Py_BytesMain
	__libc_start_main
	_start
*** End stack trace ***
Input tensor is not an XLA tensor: torch.FloatTensor
```

The installation of torch_neuronx follows the guide in the following link:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/setup/pytorch-update.html#pytorch-neuronx-update

The other environment information are below:
python==3.8
torch==1.13.1+cu117
transformers==4.28.1
numpy==1.21.6
The code is run on m5.16xlarge EC2 instance.

Thank you.

**Comment by daan-triumph** [comment]
Hey, shouldn't you run this on a neuron instance? Like inf2 or trn1?

Also, could you share your work on wrapping the mt5 model? e.g. PaddedDecoderMT5

**Comment by yzGao22** [comment]
Hi @daan-triumph , I think the compile process doesn't have to be on inferential instance like inf1 or inf2. We run this code on m5.16xlarge with _torch.neuron_ to get the traced model, which runs well on inf1 instance.

And the part for wrapping mt5 doesn't work, so I didn't put it here.

**Comment by yzGao22** [comment]
Thank you @daan-triumph, the code you provide works for mt5 model and the error about 'XLA tensor' is solved. But I got another issue when runs the code I shared before for 'BRIO' model, which shows that:

```
ValueError                                Traceback (most recent call last)
Cell In[7], line 3
      1 # Neuron Execution
      2 paddded_model = PaddedGenerator.from_model(model)
----> 3 neuron_model = trace(paddded_model, num_texts, num_beams, max_decoder_length, max_encoder_length)

Cell In[4], line 38, in trace(model, num_texts, num_beams, max_decoder_length, max_encoder_length)
     35 for item in inputs:
     36     print('device decoder: ',item.device)
---> 38 decoder = torch_neuronx.trace(model.decoder, inputs)
     40 traced = PaddedGenerator(model.config)
     41 traced.encoder = encoder

File [~/.local/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:242](https://vscode-remote+ssh-002dremote-002bsumm.vscode-resource.vscode-cdn.net/home/ubuntu/datascience/text_summarization/Neuron/~/.local/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:242), in trace(func, example_inputs, states, compiler_workdir, compiler_args, options)
    240 # Convert the function to a HloProto message
    241 with torch_neuronx.contexts.mock_neuron_cores():
--> 242     hlo, input_parameter_names, constant_parameter_tensors, flattener, packer = xla_trace(
    243         func,
    244         example_inputs,
    245         states,
    246     )
    248 # Create a temporary directory for artifacts if none is specified
    249 context = nullcontext()
...
--> 102 tensors, identifiers = zip(*uniques.items())
    103 packer = structure.Packer(layout, identifiers, constants)
    105 # Lower the HLO graph

ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by danbochman** [comment]
> 

Thank you very much for the code example! I am able to compile t5 models with it; However, I am unable to use them for inference. I'm getting the following error:

```
Traceback (most recent call last):
  File "infer_neuron_t5.py", line 64, in <module>
    infer(model_neuron, tokenizer_cpu, text)
  File "infer_neuron_t5.py", line 36, in infer
    output = model.generate(
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/generation/utils.py", line 1322, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/generation/utils.py", line 627, in _prepare_encoder_decoder_kwargs_for_generation
    encoder_signature = set(inspect.signature(encoder.forward).parameters)
AttributeError: 'function' object has no attribute 'forward'
```

I think it has to do with `get_encoder()` returning a function and not the `nn.Module`, perhaps I didn't fully understand how you intended for the NeuronGeneration to be called for inference.
Can you please share an example where you use the `infer()` function?

**Comment by gonzachiar** [comment]
Any news on this?

**Comment by jluntamazon** [comment]
You should be able to produce valid results using the same padded generator code from here: https://github.com/aws-neuron/aws-neuron-sdk/issues/672#issuecomment-1540781448

First create the `neuron_padded_generation.py` and then you can use the following script to compare CPU output to Neuron output:

`main.py`
```python
import os
from neuron_padded_generation import PaddedGenerator, trace
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

model_name = 'Yale-LILY/brio-cnndm-uncased'
num_texts = 1                             # Number of input texts to decode
num_beams = 4                             # Number of beams per input text
max_encoder_length = 128                  # Maximum input token length
max_decoder_length = 128                  # Maximum output token length


def infer(model, tokenizer, text):
    # Truncate and pad the max length to ensure that the token size is compatible with fixed-sized encoder (Not necessary for pure CPU execution)
    batch =  tokenizer(text, max_length=max_decoder_length, truncation=True, padding='max_length', return_tensors="pt")
    output = model.generate(**batch, max_length=max_decoder_length, num_beams=num_beams, num_return_sequences=num_beams)
    results = [tokenizer.decode(t, skip_special_tokens=True) for t in output]
    for i, summary in enumerate(results):
        print(i + 1, summary)


def main():

    text = 'I am a small frog'
    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)
    model_cpu = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    model_cpu.config.max_length = max_decoder_length
    model_cpu.eval()

    print('Default CPU Results:')
    infer(model_cpu, tokenizer, text)

    padded_cpu = PaddedGenerator.from_model(model_cpu)
    print('Padded CPU Results:')
    infer(padded_cpu, tokenizer, text)

    padded_neuron = trace(padded_cpu, num_texts, num_beams, max_decoder_length, max_encoder_length, compiler_args='--auto-cast=none')
    padded_neuron.save_pretrained('neuron/')
    print('Neuron Results:')
    infer(padded_neuron, tokenizer, text)


if __name__ == '__main__':
    main()
```

Note that this model appears to be sensitive to data type casting which is why I use the `--auto-cast=none` flag above. This makes the results identical. You can change the auto-cast settings to adjust speed vs accuracy.

See: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/neuronx-cc/neuronx-cc-training-mixed-precision.html

Let us know if this resolves the issue

**Comment by aws-taylor** [comment]
Hello @yzGao22,

 We haven't heard from you in a while, so I'm going to go ahead and resolve this issue. If the fix @jluntamazon proposed above did not fix your issue then please re-open and let us know.
 
 Regards,
Taylor
