### ISSUE TITLE
[torch-neuronx] Compiling Error from PyTorch Sagemaker Training Job on trn1

### ISSUE THREAD

**Issue by rileyhun** [aws-neuron/aws-neuron-sdk#674]
Hello,

I'm trying to train one of our models using the `ml.trn1.2xlarge` on Sagemaker Training. It's using this docker image - `763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training-neuronx:1.13.1-neuronx-py38-sdk2.10.0-ubuntu20.04`. 
The model is proprietary, so I cannot share the a reproducible example unfortunately. I can successfully train this model using a standard GPU and it's about 1M parameters. 

Here is the error I'm getting though in the logs: 

```
OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
 
 During handling of the above exception, another exception occurred
 Traceback (most recent call last)
 File "entry.py", line 220, in <module>
 _train()
 File "entry.py", line 204, in _train
 crimsonML.train_and_evaluate.runSageMaker(args, trainConfig, evalConfig)
 File "/opt/ml/code/crimsonML/train_and_evaluate.py", line 95, in runSageMaker
 m.train()
 File "/opt/ml/code/crimsonML/base/TrainerBase.py", line 446, in train
 trainLoss = self._trainEpoch(model, optimizer, trainDataLoader, criterion)
 File "/opt/ml/code/crimsonML/base/TrainerBase.py", line 361, in _trainEpoch
 raise e
 File "/opt/ml/code/crimsonML/base/TrainerBase.py", line 342, in _trainEpoch
 batchOutput = model(data)
 File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
 return forward_call(*input, **kwargs)
 File "crimsonML/networks/GAT_HG.py", line 90, in forward
 h = self.encoder(data.x, data.edge_index)
 File "crimsonML/networks/GAT_HG.py", line 45, in forward
 x = layer(x, edge_index)
 File "/usr/local/lib/python3.8/site-packages/torch_geometric/nn/conv/gatv2_conv.py", line 250, in forward
 out = self.propagate(edge_index, x=(x_l, x_r), edge_attr=edge_attr,
 File "/usr/local/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 467, in propagate
 out = self.message(**msg_kwargs)
 File "/usr/local/lib/python3.8/site-packages/torch_geometric/nn/conv/gatv2_conv.py", line 293, in message
 alpha = softmax(alpha, index, ptr, size_i)
 File "/usr/local/lib/python3.8/site-packages/torch_geometric/utils/softmax.py", line 68, in softmax
 out_sum = scatter(out, index, dim, dim_size=N, reduce='sum') + 1e-16"
Command "/usr/local/bin/python3.8 entry.py --batchSize 32 --dataloaderTrainerNetwork crimsonML/dataloaders/DataLoaderHGContrastive.py:crimsonML/trainers/TrainerHGContrastive.py:crimsonML/networks/GAT_HG.py --epochs 2 --evalConfig crimsonML/configs/EvalConfig.json --gpu xla --learningRate 0.0001 --learningRateDecayEpochs 10 --learningRateDecayRate 0.5 --maxEntities 500 --minEntities 20 --optimizer Adam --patience 20 --sampleSize 10 --schedule ReduceLROnPlateau --trainConfig crimsonML/configs/TrainConfigContrastive.json"
```

Dependencies in the dockerfile: 
```
RUN pip install torch==1.13.0+cu116 torchvision==0.14.0+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 && \
    pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
```

**Comment by jluntamazon** [comment]
Hello @rileyhun, would you be able to share any non-proprietary code that reproduces the error? I suspect the issue may be related to `torch-geometric` since this is a library that we have not looked to formally support

**Comment by rileyhun** [comment]
Hello @jluntamazon, I can talk to our ML developers who own this code. Would it be possible to hop onto a screenshare session with you and I can show you the code that way?

**Comment by jluntamazon** [comment]
Thank you for the script! We are looking at this now

**Comment by rileyhun** [comment]
Thanks very much @jluntamazon! And thanks for leading me in the right direction. You were right in that it's most likely due to lack of support for `torch-geometric`

**Comment by aws-donkrets** [comment]
Hi @rileyhun, - I plan to add support for torch-geometric to our Roadmap, although no commitment when it will occur.

**Comment by okung567** [comment]
any updates on this or guidance on how to use pyg on neuron?

**Comment by musunita** [comment]
Hi @rileyhun, The sample code that was submitted to demonstrate the issue is now running successfully, as mentioned by @jimburtoft. If you still need further assistance, please reopen the issue.

Thank you
