### ISSUE TITLE
[HuggingFace] INF1 - Compiled model with dynamic batching failed while loading

### ISSUE THREAD

**Issue by JingyaHuang** [aws-neuron/aws-neuron-sdk#681]
Hi team, 

I met an issue when trying to enable dynamic batching on INF1. The serialized traced model with dynamic batching enabled seems have inconsistent input shapes, and failed while loading with `torch.jit.load`.

Did I do anything wrong?

* System information
```
OS unbuntu 20.04.5 LTS
```
* Neuron driver
```
aws-neuronx-dkms/unknown,now 2.9.4.0 amd64 [installed]
aws-neuronx-tools/unknown,now 2.10.1.0 amd64 [installed]
```
* Pip installed
```
dmlc-tvm                 1.15.0.0+0
neuron-cc                1.15.0.0+eec0c3604
optimum-neuron           0.0.5.dev0
torch                    1.13.1
torch-neuron             1.13.1.2.7.1.0
torchvision              0.14.1
```

<details><summary>Error log</summary>

```
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at hf-internal-testing/tiny-random-BertModel and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:Neuron:There are 3 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuron-cc/neuron-cc-ops/neuron-cc-ops-pytorch.html)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 250, fused = 242, percent fused = 96.8%
WARNING:tensorflow:From /home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/ops/aten.py:2387: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:Neuron:Compiler args type is <class 'list'> value is ['--fast-math', 'none']
INFO:Neuron:Compiling function _NeuronGraph$320 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/Install/aws_neuron_venv_pytorch/bin/neuron-cc compile /tmp/tmp568z2ce7/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp568z2ce7/graph_def.neff --io-config {"inputs": {"tensor.1:0": [[2, 18], "int64"], "1:0": [[2, 18, 32], "float32"], "2:0": [[2, 18, 32], "float32"], "3:0": [[1, 18, 32], "float32"]}, "outputs": ["BertForSequenceClassification_1/Linear_5/aten_linear/Add:0"]} --fast-math none --verbose 35'
..
Compiler status PASS
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 250, compiled = 242, percent compiled = 96.8%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 100.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 40
INFO:Neuron: => aten::add: 16
INFO:Neuron: => aten::add_: 1
INFO:Neuron: => aten::contiguous: 5
INFO:Neuron: => aten::div: 5
INFO:Neuron: => aten::dropout: 17
INFO:Neuron: => aten::gelu: 5
INFO:Neuron: => aten::layer_norm: 11
INFO:Neuron: => aten::linear: 32
INFO:Neuron: => aten::matmul: 10
INFO:Neuron: => aten::mul: 1
INFO:Neuron: => aten::permute: 20
INFO:Neuron: => aten::rsub: 1
INFO:Neuron: => aten::select: 1
INFO:Neuron: => aten::size: 40
INFO:Neuron: => aten::slice: 3
INFO:Neuron: => aten::softmax: 5
INFO:Neuron: => aten::tanh: 1
INFO:Neuron: => aten::to: 1
INFO:Neuron: => aten::transpose: 5
INFO:Neuron: => aten::unsqueeze: 2
INFO:Neuron: => aten::view: 20
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 1 [supported]
INFO:Neuron: => aten::add: 1 [supported]
INFO:Neuron: => aten::embedding: 3 [not supported]
INFO:Neuron: => aten::size: 1 [supported]
INFO:Neuron: => aten::slice: 2 [supported]
Traceback (most recent call last):
  File "test_dynamic_bs.py", line 67, in <module>
    neuron_model = torch.jit.load(output_path)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
ValueError: Dynamic batching was enabled but all compiled batch inputs and outputs did not have the same dim 0 size:
        Input #0 shape: [2 18]
        Input #1 shape: [2 18 32]
        Input #2 shape: [2 18 32]
        Input #3 shape: [1 18 32]
        Output #0 shape: [2 2]
Inconsistent batch size found.
```

</details>

Short version:
```
Traceback (most recent call last):
  File "test_dynamic_bs.py", line 67, in <module>
    neuron_model = torch.jit.load(output_path)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/Install/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
ValueError: Dynamic batching was enabled but all compiled batch inputs and outputs did not have the same dim 0 size:
        Input #0 shape: [2 18]
        Input #1 shape: [2 18 32]
        Input #2 shape: [2 18 32]
        Input #3 shape: [1 18 32]
        Output #0 shape: [2 2]
Inconsistent batch size found.
```

* Reproduction
    *  `pip install git+https://github.com/huggingface/optimum-neuron.git optimum`
    * script
```python
import copy
from pathlib import Path
import torch
from transformers import AutoModelForSequenceClassification

from optimum.exporters.neuron import export, validate_model_outputs
from optimum.exporters.neuron.model_configs import BertNeuronConfig

model_id = "hf-internal-testing/tiny-random-BertModel"
model = AutoModelForSequenceClassification.from_pretrained(model_id)
neuron_config = BertNeuronConfig(
    config=model.config, task="text-classification", dynamic_batch_size=True, batch_size=2, sequence_length=18
)
output_path = Path("test_bert/model.pt")

export(
    model=model,
    config=neuron_config,
    output=output_path,
    auto_cast=None,
)

neuron_model = torch.jit.load(output_path)
```

**Comment by aws-mvaria** [comment]
Hi @JingyaHuang 

This encounters an issue with Neuron where the position id tensor that is created in the model does not have the same batch dimension as the inputs. This tensor is used in an unsupported operation (embedding) which means that the output of the positional embedding operation is considered an input to the Neuron model. Neuron requires that all model inputs have the same batch dimension when using `dynamic_batch_size=True`.

If dynamic batching is _necessary_, your best option is to ensure that the batch dimensions match by compiling with `batch_size=1`.

If dynamic batching is _optional_, you can still compile with `batch_size=2`, but with dynamic batching disabled.

Lastly, you should be able to successfully compile this model with CPU partitioning disabled to attempt to force the operations to Neuron. This is possible by disabling the fallback flag: `torch_neuron.trace(…, fallback=False)`. This is not usually recommended because it can cause compilation failures and performance problems.

Thanks

**Comment by JingyaHuang** [comment]
Hi @aws-mvaria,

Thanks for the explanation, it is very clear!

And I have an extra question on the dynamic batching. Does your answer also apply to __neuronx inference__? 

As I am also enabling dynamic batching for neuronx inference, and I experimented with batch_size > 1 (dynamic batching ON) with the same model, it seems to work with reasonable accuracy. As neuron and neuronx use different tracing approaches,  I am wondering if there is the same downside if I set a batch size other than 1 for  neuronx.

**Comment by TheoEnns** [comment]
@JingyaHuang It is likely to work out of the box with torch-neuronx inference since we support embedding operations by default. This means that the graph here should compile as a single unit and will not encounter the same issue.

However, there are some downsides: 
- When using torch-neuronx, currently there is no graph partitioning feature to enable unsupported ops.
- Secondly, torch-neuronx is only supporting inf2 and trn1 for inference and it does not currently support compilation for inf1.
- The dynamic batching API is slightly different and can be enabled on a model any time after compilation: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/api-reference-guide/inference/api-torch-neuronx-trace.html#dynamic-batching

**Comment by JingyaHuang** [comment]
Hi @TheoEnns,

Thanks for the explanation. For the neuron dynamic batching(INF1), I tried with compiling with input batch size of 1. This time I can use `torch.load.jit` to load the model and do the inference with inputs of batch size 1. However, when I try to do inference with batch size 2, I got the following error. 
```
dummy shape is torch.Size([2, 18])
Traceback (most recent call last):
  File "test_dynamic_bs.py", line 70, in <module>
    output_neuron = neuron_model(*dummy_tuple)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_neuron/runtime/___torch_mangle_195.py", line 20, in forward
    _5 = torch.embedding(CONSTANTS.c3, _2)
    model = _NeuronGraph_32.model
    _6 = ops.neuron.forward_v2_1([argument_2, _3, _4, _5], model)
         ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_6,)

Traceback of TorchScript, original code (most recent call last):
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/_ops.py(442): __call__
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/decorators.py(416): forward
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(1194): _call_impl
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(580): __call__
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(209): run_op
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/graph.py(198): __call__
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/runtime.py(69): forward
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py(1194): _call_impl
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_trace.py(976): trace_module
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch/jit/_trace.py(759): trace
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/tensorboard.py(324): tb_parse
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/tensorboard.py(550): tb_graph
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/decorators.py(526): maybe_generate_tb_graph_def
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py(580): maybe_determine_names_from_tensorboard
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/convert.py(233): trace
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py(285): export_neuron
/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py(156): export
test_dynamic_bs.py(37): <module>
RuntimeError: Inconsistent batch sizes found on inputs. All batch tensors must have the same dim 0 size.
        Input tensor #0 shape: 2 18
        Input tensor #1 shape: 2 18 32
        Input tensor #2 shape: 2 18 32
        Input tensor #3 shape: 1 18 32
```

It seems that it is not dynamic as one input (seems to be the output of positional embedding operation) has a different batch size)

* Reproduction
```python
import copy
from pathlib import Path
import torch
from transformers import AutoModelForSequenceClassification

from optimum.exporters.neuron import export, validate_model_outputs
from optimum.exporters.neuron.model_configs import BertNeuronConfig

model_id = "hf-internal-testing/tiny-random-BertModel"
model = AutoModelForSequenceClassification.from_pretrained(model_id)
neuron_config = BertNeuronConfig(
    config=model.config, task="text-classification", dynamic_batch_size=True, batch_size=1, sequence_length=18
)
output_path = Path("test_bert/model.neuron")

export(
    model=model,
    config=neuron_config,
    output=output_path,
    auto_cast=None,
)


# Generate dummy input with different batch size
input_shapes = {"batch_size": neuron_config.batch_size+1, "sequence_length": neuron_config.sequence_length}
dummy = neuron_config.generate_dummy_inputs(return_tuple=False, **input_shapes)
dummy_tuple = tuple(dummy.values())
print(f"dummy shape is {dummy['input_ids'].shape}")

# Inference
neuron_model = torch.jit.load(output_path)
output_neuron = neuron_model(*dummy_tuple)
```

And I also had a try with `fallback=False` (although it is not recommended) __it works, with correct output logits__. (so I will set the fall back euqals to `True` by default for the moment).

Wonder if it is normal that I got the error even when compiling with batch size=1? Did I do something wrong? Thanks for helping!

**Comment by mrnikwaws** [comment]
This looks like a bug in BertNeuronConfig - where the last input does not have the correct batch dimension.  I'd recommend taking a look at the dummy tuple and consider a) Turning into a list, b) Updating the last argument to have the correct batch dimension.

```
RuntimeError: Inconsistent batch sizes found on inputs. All batch tensors must have the same dim 0 size.
        Input tensor #0 shape: 2 18
        Input tensor #1 shape: 2 18 32
        Input tensor #2 shape: 2 18 32
        Input tensor #3 shape: 1 18 32
```

**Comment by aws-donkrets** [comment]
Hi @JingyaHuang - were you able to update he model as  @mrnikwaws suggested? Did that resolve your issue?

**Comment by aws-donkrets** [comment]
Hi @JingyaHuang - closing this old ticket. If you encounter the issue again please submit a new ticket. Thx.
