### ISSUE TITLE
[HuggingFace] Compiling pretrained huggingface layoutlmV3 with neuron.trace, IndexError: index out of range in self

### ISSUE THREAD

**Issue by srg9000** [aws-neuron/aws-neuron-sdk#683]
ENV details: ml.inf1.xlarge instance
torch==1.19.3 (and tested on torch 1.13.3)
transformers==4.20.0
python 3.8.16

I am trying to compile a pretrained model from huggingface hub "microsoft/layoutlmv3-base", the model as-is works but i get the following error in `torch.neuron.trace` step:
```
Traceback (most recent call last):
  File "compile_neuron_lmv3.py", line 57, in <module>
    model_neuron = torch.neuron.trace(model, example_input, strict=False,
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch_neuron/convert.py", line 180, in trace
    neuron_graph, jit_trace = to_graph(func, example_inputs, return_trace=True, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch_neuron/convert.py", line 252, in to_graph
    jit_trace = torch.jit.trace(func_or_mod, example_inputs, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/jit/_trace.py", line 735, in trace
    return trace_module(
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/jit/_trace.py", line 952, in trace_module
    module._c._create_method_from_trace(
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 833, in forward
    embedding_output = self.embeddings(
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 258, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/ubuntu/.pyenv/versions/3.8.16/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

My script is:
```
import tensorflow  # to workaround a protobuf version conflict issue
import torch
import torch.neuron
from transformers import AutoTokenizer, AutoModel, AutoConfig, LayoutLMv3Processor, LayoutLMv3Model
import transformers
import os
import numpy as np
from PIL import Image

import warnings

# Setting up NeuronCore groups for inf1.6xlarge with 16 cores
num_cores = 4 # This value should be 4 on inf1.xlarge and inf1.2xlarge
os.environ['NEURON_RT_NUM_CORES'] = str(num_cores)

processor = LayoutLMv3Processor.from_pretrained("microsoft/layoutlmv3-base", apply_ocr=False)
model = LayoutLMv3Model.from_pretrained("microsoft/layoutlmv3-base", return_dict=False)
model.eval()

image = Image.fromarray(np.array(np.random.rand(244, 244, 3)*255).astype(np.uint8))
words = ["This", "is", "a", "big", "long", "sentense"]
boxes = [[1, 2, 3, 4], [34, 344, 233, 555], [1, 2, 3, 4], [1, 2, 32, 40], [1, 2, 3, 4], [1, 2, 32, 40]]

encoding = processor(
                image,
                words,
                boxes=boxes,
                return_tensors="pt",
                padding='max_length',
                max_length=512,
                truncation=True,
                return_overflowing_tokens=True,
                return_offsets_mapping=True,
                return_token_type_ids=True
            )
offset_mapping = encoding.pop('offset_mapping')
overflow_to_sample_mapping = encoding.pop('overflow_to_sample_mapping')
encoding['pixel_values'] = torch.stack(encoding['pixel_values'])

for k,v in encoding.items():
    print(k, v.dtype, v.shape)
print(model.embeddings.token_type_embeddings(encoding['token_type_ids']))

# Run the original PyTorch model on compilation exaple
#with torch.no_grad():
outputs = model(**encoding)[0]
print(outputs)
print("#"*30, flush=True)

# Convert example inputs to a format that is compatible with TorchScript tracing
example_input = tuple(encoding.values())
for i in example_input:
    print(i)

# Run torch.neuron.trace to generate a TorchScript that is optimized by AWS Neuron
#with torch.no_grad():
model_neuron = torch.neuron.trace(model, example_input, strict=False,
    compiler_args=["--neuroncore-pipeline-cores", str(num_cores)],
)

# Verify the TorchScript works on both example inputs
neuron_logits = model_neuron(*example_input)
print(neuron_logits)

# Save the TorchScript for later use
model_neuron.save('layoutlmv3-base-neuron.pt')
```

I get the outputs from the normal model but get the error in the trace step.

**Comment by jeffhataws** [comment]
If I run on CPU using "model(*example_input)", I also see " index out of range in self" error. When I inspect the model.forward function, I see these positional arguments:
```
print(inspect.getsource(model.forward))

def forward(
    self,
    input_ids: Optional[torch.LongTensor] = None,
    bbox: Optional[torch.LongTensor] = None,
    attention_mask: Optional[torch.FloatTensor] = None,
    token_type_ids: Optional[torch.LongTensor] = None,
    position_ids: Optional[torch.LongTensor] = None,
    head_mask: Optional[torch.FloatTensor] = None,
    inputs_embeds: Optional[torch.FloatTensor] = None,
    pixel_values: Optional[torch.FloatTensor] = None,
    output_attentions: Optional[bool] = None,
    output_hidden_states: Optional[bool] = None,
    return_dict: Optional[bool] = None,
   ) -> Union[Tuple, BaseModelOutput]:
```
While the dictionary "encoding" has fields:
```
input_ids torch.int64 torch.Size([1, 128])
token_type_ids torch.int64 torch.Size([1, 128])
attention_mask torch.int64 torch.Size([1, 128])
bbox torch.int64 torch.Size([1, 128, 4])
pixel_values torch.float32 torch.Size([1, 3, 224, 224])
```
In order to pass "encoding"'s tensors to model.forward via positional arguments, as required by trace API, we need to create [a wrapper](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/troubleshooting-guide.html#torch-jit-trace-issues) like below to take "encoding"'s field order and remap to model.forward's positional arguments:
```
# Wrapper to convert the encoding order to model.forward's keyword arguments with None inputs
class NeuronCompatibilityWrapper(torch.nn.Module):
    def __init__(self, model):
        super(NeuronCompatibilityWrapper, self).__init__()
        self.model = model

    # The wrapper's arguments' positions match "encoding"'s field order
    def forward(self, input_ids, token_type_ids, attention_mask, bbox, pixel_values):
        # remap to model.forward's keyword arguments; unspecified arguments default to None
        y = {'input_ids': input_ids,
             'bbox': bbox,
             'attention_mask': attention_mask,
             'token_type_ids': token_type_ids,
             'pixel_values': pixel_values}
        return self.model(**y)

model_wrapped = NeuronCompatibilityWrapper(model)
```
Then pass the example_input to test on CPU to double check before using Neuron trace:
```
model_wrapped(*example_input) # this now works without error

model_neuron = torch.neuron.trace(model_wrapped, example_input, strict=False,
    compiler_args=["--neuroncore-pipeline-cores", str(num_cores)],
)

torch.jit.save(model_neuron, "layoutlmv3-base-neuron.pt")
```
I am now able to compile:
```
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 813, compiled = 768, percent compiled = 94.46%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 100.0%
```
Let me know if this works for you.

**Comment by mrnikwaws** [comment]
Closing since it has been a month now and it seems the solution is good
