### ISSUE TITLE
Compiler Error without regex package

### ISSUE THREAD

**Issue by justusschock** [aws-neuron/aws-neuron-sdk#714]
Hey, 

I tried to run the mnist-mlp example and the compile failed with the following error-message:

<details>
<summary>Error Message</summary>

```
----------Training ---------------
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/neuron_cc_wrapper", line 5, in <module>
    from libneuronxla.neuron_cc_wrapper import main
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/libneuronxla/neuron_cc_wrapper.py", line 15, in <module>
    from libneuronxla.neuron_cc_cache import CacheUrl, create_compile_cache, NEURON_COMPILE_CACHE_URL_INFO, CACHE_STRUCTURE_INFO
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/libneuronxla/neuron_cc_cache.py", line 13, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
2023-08-02 18:17:33.693944: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
2023-08-02 18:17:33.708494: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] StackTrace:
2023-08-02 18:17:33.708528: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** Begin stack trace ***
2023-08-02 18:17:33.708540: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        tsl::CurrentStackTrace()
2023-08-02 18:17:33.708549: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::ReportComputationError(tsl::Status const&, absl::lts_20220623::Span<xla::XlaComputation const* const>, absl::lts_20220623::Span<xla::Shape const* const>)
2023-08-02 18:17:33.708559: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2023-08-02 18:17:33.708569: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-02 18:17:33.708579: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2023-08-02 18:17:33.708589: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-02 18:17:33.708599: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-02 18:17:33.708608: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-02 18:17:33.708614: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]        clone
2023-08-02 18:17:33.708624: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** End stack trace ***
2023-08-02 18:17:33.708634: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-08-02 18:17:33.708644: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Status: INTERNAL: From /job:localservice/replica:0/task:0:
2023-08-02 18:17:33.708654: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 2 root error(s) found.
2023-08-02 18:17:33.708664: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (0) INTERNAL: neuronx-cc compilation failed.
2023-08-02 18:17:33.708674: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-08-02 18:17:33.708684: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[XRTExecute_G12]]
2023-08-02 18:17:33.708694: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (1) INTERNAL: neuronx-cc compilation failed.
2023-08-02 18:17:33.708702: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]         [[{{node XRTExecute}}]]
2023-08-02 18:17:33.708710: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 successful operations.
2023-08-02 18:17:33.708719: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 derived errors ignored.
2023-08-02 18:17:33.708729: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Recent warning and error logs:
2023-08-02 18:17:33.708740: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Traceback (most recent call last):
  File "/project/studios/this_studio/aws-neuron-samples/torch-neuronx/training/mnist_mlp/train.py", line 71, in <module>
    main()
  File "/project/studios/this_studio/aws-neuron-samples/torch-neuronx/training/mnist_mlp/train.py", line 51, in main
    xm.mark_step() # XLA: collect ops and run them in XLA runtime
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 988, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
         [[{{node XRTExecute}}]]
         [[XRTExecute_G12]]
  (1) INTERNAL: neuronx-cc compilation failed.
         [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
```

</details>

After installing the `regex` package, which isn't a requirement but used internally, everything runs fine. 
So the fix probably is to either switch from `import regex as re` to `import re` if the advanced functionality isn't used or to add `regex` to the list of dependencies.

Cheers,
Justus

**Comment by awsilya** [comment]
@justusschock thank you for the feedback.  We'll get this fixed.

**Comment by jyang-aws** [comment]
please check out our latest release 2.13. it fixes this issue. thanks!
