### ISSUE TITLE
Cannot compile Donut model on Inferentia2

### ISSUE THREAD

**Issue by dneemuth** [aws-neuron/aws-neuron-sdk#732]
I am trying to compile a [Donut](https://github.com/clovaai/donut) model with torch-neuronx on inf2 (inf2.xlarge) instance. Actually using the following aws base image (check reference below)  to compile a docker image, and the entry point calls a python script that compiles model to run on inf2.

BASE_IMAGE=763104351884.dkr.ecr.${AWS_REGION}.amazonaws.com/**pytorch-inference-neuronx:1.13.1-neuronx-py310-sdk2.12.0-ubuntu20.04**

I'm not able to decipher the error message. can you please assist & do let me know if you require additional info. thnks.

**Here is my code:**
`import torch
import os
import importlib
import requests
from transformers import DonutProcessor, VisionEncoderDecoderModel
from PIL import Image
import torch_xla.core.xla_model as xm

chip_type = os.environ.get("CHIP_TYPE", "inf1")

print(f"Selecting chip type: {chip_type}")

if chip_type  == "inf1":
    import torch_neuron as neuron_lib
elif chip_type == "inf2":
    import torch_neuronx as neuron_lib

batch_size = 1

sequence_length = 128

model_name = 'naver-clova-ix/donut-base-finetuned-cord-v2'

# 2. LOAD PRE-TRAINED MODEL
print(f'\nLoading pre-trained model: {model_name}')
processor = DonutProcessor.from_pretrained(model_name)
model = VisionEncoderDecoderModel.from_pretrained(model_name)

# 1. TOKENIZE THE INPUT
# note: if you don't include return_tensors='pt' you'll get a list of lists which is easier for
# exploration but you cannot feed that into a model.
                                                

# let's perform inference on an image
url = "https://media.snopes.com/2017/07/walmart-jajket.jpg"
image = Image.open(requests.get(url, stream=True).raw)
image = image.convert("RGB")
# prepare inputs
pixel_values = processor(image, return_tensors="pt").pixel_values
task_prompt = "<s>"
decoder_input_ids = processor.tokenizer(task_prompt, add_special_tokens=False, return_tensors="pt").input_ids
decoder_input_ids = torch.unsqueeze(decoder_input_ids, dim=0)
print('input_ids shape',decoder_input_ids.shape)
print('\nTracing model ...')

pipeline_cores = 1
pixel_values = torch.unsqueeze(pixel_values, dim=0)
xla_device = xm.xla_device()
pixel_values = pixel_values.to(xla_device)
print('pixel_values device', pixel_values.device)
print('pixel_values shape', pixel_values.shape)
decoder_input_ids = decoder_input_ids.to(xla_device)
print('decoder_input_ids device', decoder_input_ids.device)

example_inputs = (
    torch.cat(tuple(pixel_values) * batch_size,0), 
    torch.cat(tuple(decoder_input_ids) * batch_size,0)
)

model_traced = neuron_lib.trace(model, example_inputs, compiler_workdir=f'{chip_type}-compiler-workdir')

print('tracing completed.')`

**I am getting the following error**

`ubuntu@ip-172-31-73-154:~/workspace/dodogeny-neuron-api/trace-model$ ./build.sh 
CHIP TYPE: inf2
Base Neuron Docker image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-neuronx:1.13.1-neuronx-py310-sdk2.12.0-ubuntu20.04
[+] Building 0.3s (10/10) FINISHED                                                docker:default
 => [internal] load build definition from Dockerfile                                        0.0s
 => => transferring dockerfile: 431B                                                        0.0s
 => [internal] load .dockerignore                                                           0.0s
 => => transferring context: 68B                                                            0.0s
 => [internal] load metadata for 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-infe  0.1s
 => [auth] sharing credentials for 763104351884.dkr.ecr.us-east-1.amazonaws.com             0.0s
 => [1/4] FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-neuronx:1.13  0.0s
 => [internal] load build context                                                           0.0s
 => => transferring context: 17.87kB                                                        0.0s
 => CACHED [2/4] RUN pip install transformers evaluate datasets sentencepiece tensorboard   0.0s
 => [3/4] COPY ./trace-model /trace-model                                                   0.0s
 => [4/4] WORKDIR /trace-model                                                              0.0s
 => exporting to image                                                                      0.0s
 => => exporting layers                                                                     0.0s
 => => writing image sha256:29d58cfda570e0570f7b22aa79d8389a860384eaf6efe9ec9b7eda4bc7a5d6  0.0s
 => => naming to 156045795168.dkr.ecr.us-east-1.amazonaws.com/bert-inf-trace-model          0.0s
ubuntu@ip-172-31-73-154:~/workspace/dodogeny-neuron-api/trace-model$ ./run.sh 
CHIP TYPE: inf2
Base Neuron Docker image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-neuronx:1.13.1-neuronx-py310-sdk2.12.0-ubuntu20.04
BASE PATH FOR FILE: /home/ubuntu/workspace/dodogeny-neuron-api/trace-model
CHIP TYPE inf2
43b3eeadf60581612617effc6495cb5bfcf5c5839bda7503dafd587040614829
ubuntu@ip-172-31-73-154:~/workspace/dodogeny-neuron-api/trace-model$ ./logs.sh 
CHIP TYPE: inf2
Base Neuron Docker image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference-neuronx:1.13.1-neuronx-py310-sdk2.12.0-ubuntu20.04
Running Container to Trace Model
Selecting chip type: inf2

Loading pre-trained model: naver-clova-ix/donut-base-finetuned-cord-v2
Downloading (…)rocessor_config.json: 100%|██████████████████████| 362/362 [00:00<00:00, 2.77MB/s]
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Downloading (…)okenizer_config.json: 100%|██████████████████████| 536/536 [00:00<00:00, 4.24MB/s]
Downloading (…)tencepiece.bpe.model: 100%|███████████████████| 1.30M/1.30M [00:00<00:00, 326MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████████████| 4.02M/4.02M [00:00<00:00, 98.5MB/s]
Downloading (…)in/added_tokens.json: 100%|██████████████████| 1.52k/1.52k [00:00<00:00, 14.6MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████| 335/335 [00:00<00:00, 1.33MB/s]
Downloading (…)lve/main/config.json: 100%|██████████████████| 4.74k/4.74k [00:00<00:00, 29.8MB/s]
Downloading pytorch_model.bin: 100%|███████████████████████████| 806M/806M [00:01<00:00, 477MB/s]
input_ids shape torch.Size([1, 1, 1])

Tracing model ...
pixel_values device xla:1
pixel_values shape torch.Size([1, 1, 3, 1280, 960])
decoder_input_ids device xla:1
2023-08-28 13:39:58.000662: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:08.000286: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:14.000771: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:21.000247: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:27.000713: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:34.000196: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:40.000652: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:47.000126: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:40:53.000607: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:00.000090: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:06.000681: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:13.000167: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:19.000654: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:26.000142: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:32.000632: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:39.000114: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:45.000623: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:52.000102: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:41:58.000597: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:05.000100: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:11.000582: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:18.000059: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:24.000918: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:31.000397: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:37.000882: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:44.000377: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:50.000887: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:42:57.000358: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:43:03.000934: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
2023-08-28 13:43:11.000087: INFO ||NCC_WRAPPER||: Compile cache path: /var/tmp/neuron-compile-cache
.
Compiler status PASS
ERROR ***************************************************************
ERROR  An Internal Compiler Error has occurred
ERROR ***************************************************************
ERROR 
ERROR Error message:  simplifyStmtPredicates() takes exactly 1 positional argument (2 given)
ERROR 
ERROR Error class:    TypeError
ERROR Error location: Unknown
ERROR 
Traceback (most recent call last):
  File "/trace-model/trace-model.py", line 63, in <module>
    model_traced = neuron_lib.trace(model, example_inputs, compiler_workdir=f'{chip_type}-compiler-workdir')
  File "/opt/conda/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 289, in trace
    neff_filename, metaneff, flattener, packer = _trace(
  File "/opt/conda/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 357, in _trace
    neff_filename = hlo_compile(model_dir, compiler_workdir, compiler_args)
  File "/opt/conda/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 249, in hlo_compile
    raise RuntimeError(f'neuronx-cc failed with {status}')
RuntimeError: neuronx-cc failed with 1`

**Comment by jluntamazon** [comment]
Hello @dneemuth,

Thank you for the script! We have reproduced a compilation issue and are looking into a fix. We'll get back to you here as we make progress.

**Comment by dneemuth** [comment]
hello @jluntamazon ,

 sorry for bothering. but do you have any updates for the above? 
 can you please send me an official link where I can keep a watch on the new upcoming releases. thank you in advance.

**Comment by aws-donkrets** [comment]
Hi @dneemuth - we are still investigating a fix for this issue. This error is occurring in a few other models so we are actively working on it.
Each Neuron SDK release is accompanied by updated documentation. New releases are announced on the documentation landing page, which you can find here - https://awsdocs-neuron.readthedocs-hosted.com/en/latest/index.html
