### ISSUE TITLE
An Internal Compiler Error has occurred with list index out of range

### ISSUE THREAD

**Issue by DaeyangCho** [aws-neuron/aws-neuron-sdk#766]
Hello, I tried to compile our company's lip sync model on r5.8xlarge instance, but I got the error.
There was no unsupported operators and arithmetic operations.

```
INFO:Neuron:100.00% of all operations (including primitives) (10285 of 10285) are supported
INFO:Neuron:100.00% of arithmetic operations (2682 of 2682) are supported
```

I got the following log error message:
```
.10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: ***************************************************************
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:  An Internal Compiler Error has occurred
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: ***************************************************************
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: 
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Error message:  list index out of range
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: 
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Error class:    IndexError
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Error location: Unknown
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Command line:   /opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpckix24cr/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpckix24cr/graph_def.neff --io-config '{"inputs": {"tensor.1:0": [[4, 3, 192, 192], "float32"], "1:0": [[4, 1, 80, 16], "float32"]}, "outputs": ["Decoder_54/DecoderAttnBlock_109/aten_add_3/add:0"]}' --verbose 35
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: 
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Internal details:
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 224, in neuroncc.driver.CommandDriver.CommandDriver.run
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 580, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 558, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 562, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 429, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 379, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 380, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 390, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 360, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend.tensorize
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 47, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 48, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 69, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/Compile.py", line 255, in neuroncc.starfish.penguin.Compile.compile_cu
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/Compile.py", line 284, in neuroncc.starfish.penguin.Compile.try_fallback_on_count_exceeded
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 115, in neuroncc.starfish.penguin.DotTransform.DotTransform.transform
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 378, in neuroncc.starfish.penguin.DotTransform.PassManager.transformFunction
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 124, in neuroncc.starfish.penguin.DotTransform.DotTransform.runOnFunction
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 178, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 160, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 186, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 188, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 189, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 206, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 207, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 287, in neuroncc.starfish.penguin.DotTransform.DotTransform.transformFunction
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 281, in neuroncc.starfish.penguin.DotTransform.DotTransform.runTransforms
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/TilingForNewLayout.py", line 1608, in neuroncc.starfish.penguin.targets.tonga.passes.TilingForNewLayout.TilingForNewLayout.transformStmts
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/TilingForNewLayout.py", line 1413, in neuroncc.starfish.penguin.targets.tonga.passes.TilingForNewLayout.TilingForNewLayout.transformDAG
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/TilingForNewLayout.py", line 733, in neuroncc.starfish.penguin.targets.tonga.passes.TilingForNewLayout.TilingForNewLayout.packInstsToMatMulMacro
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: 
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Version information:
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   Neuron Compiler version 1.15.0.0+eec0c3604
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   HWM version 1.14.1.0-a9fb5c73a
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   NEFF version Dynamic
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   TVM version 1.15.0.0+0
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   NumPy version 1.20.3
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   MXNet not available
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]:   TF not available
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: 
10/11/2023 02:56:13 AM ERROR 12411 [neuron-cc]: Artifacts stored in: /tmp/tmpckix24cr

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$2426; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpckix24cr/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpckix24cr/graph_def.neff --io-config '{"inputs": {"tensor.1:0": [[4, 3, 192, 192], "float32"], "1:0": [[4, 1, 80, 16], "float32"]}, "outputs": ["Decoder_54/DecoderAttnBlock_109/aten_add_3/add:0"]}' --verbose 35
Traceback (most recent call last):
  File "/opt/aws_neuron_venv_pytorch_inf1/lib64/python3.8/site-packages/torch_neuron/convert.py", line 413, in op_converter
    neuron_function = self.subgraph_compiler(
  File "/opt/aws_neuron_venv_pytorch_inf1/lib64/python3.8/site-packages/torch_neuron/decorators.py", line 263, in trace
    raise subprocess.SubprocessError(
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/opt/aws_neuron_venv_pytorch_inf1/bin/neuron-cc compile /tmp/tmpckix24cr/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpckix24cr/graph_def.neff --io-config '{"inputs": {"tensor.1:0": [[4, 3, 192, 192], "float32"], "1:0": [[4, 1, 80, 16], "float32"]}, "outputs": ["Decoder_54/DecoderAttnBlock_109/aten_add_3/add:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 2682, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 550 [supported]
INFO:Neuron: => aten::_convolution: 115 [supported]
INFO:Neuron: => aten::adaptive_avg_pool2d: 16 [supported]
INFO:Neuron: => aten::add: 68 [supported]
INFO:Neuron: => aten::add_: 41 [supported]
INFO:Neuron: => aten::addmm: 17 [supported]
INFO:Neuron: => aten::cat: 4 [supported]
INFO:Neuron: => aten::cos: 12 [supported]
INFO:Neuron: => aten::dropout: 16 [supported]
INFO:Neuron: => aten::flatten: 4 [supported]
INFO:Neuron: => aten::flip: 25 [supported]
INFO:Neuron: => aten::floor_divide: 12 [supported]
INFO:Neuron: => aten::gelu: 4 [supported]
INFO:Neuron: => aten::instance_norm: 37 [supported]
INFO:Neuron: => aten::layer_norm: 12 [supported]
INFO:Neuron: => aten::leaky_relu: 51 [supported]
INFO:Neuron: => aten::leaky_relu_: 49 [supported]
INFO:Neuron: => aten::linear: 45 [supported]
INFO:Neuron: => aten::log: 12 [supported]
INFO:Neuron: => aten::matmul: 8 [supported]
INFO:Neuron: => aten::mean: 1 [supported]
INFO:Neuron: => aten::mul: 282 [supported]
INFO:Neuron: => aten::pad: 50 [not supported]
INFO:Neuron: => aten::permute: 14 [supported]
INFO:Neuron: => aten::rand: 24 [supported]
INFO:Neuron: => aten::repeat: 26 [supported]
INFO:Neuron: => aten::reshape: 193 [supported]
INFO:Neuron: => aten::rsqrt: 12 [supported]
INFO:Neuron: => aten::size: 341 [supported]
INFO:Neuron: => aten::slice: 246 [supported]
INFO:Neuron: => aten::softmax: 5 [supported]
INFO:Neuron: => aten::sqrt: 12 [supported]
INFO:Neuron: => aten::sub: 50 [supported]
INFO:Neuron: => aten::sum: 13 [supported]
INFO:Neuron: => aten::t: 17 [supported]
INFO:Neuron: => aten::to: 158 [supported]
INFO:Neuron: => aten::transpose: 16 [supported]
INFO:Neuron: => aten::unbind: 6 [supported]
INFO:Neuron: => aten::unsqueeze: 84 [supported]
INFO:Neuron: => aten::view: 33 [supported]
INFO:Neuron: => aten::zeros: 1 [supported]
Traceback (most recent call last):
  File "compile_neuron.py", line 48, in <module>
    model_neuron = torch.neuron.trace(compile_model, example_inputs=[x2, x3])
  File "/opt/aws_neuron_venv_pytorch_inf1/lib64/python3.8/site-packages/torch_neuron/convert.py", line 217, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/opt/aws_neuron_venv_pytorch_inf1/lib64/python3.8/site-packages/torch_neuron/convert.py", line 530, in stats_post_compiler
    raise RuntimeError(
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

This is my first time with neuron compile, so any help would be greatly appreciated.

**Comment by aws-donkrets** [comment]
Hi [DaeyangCho](https://github.com/DaeyangCho) - sorry you are having a problem compiling your model. The RunTimeError essentially is reporting that the compiler did not successfully produce a NEFF (executable model) file., even though all the operators are supported.   As a first step, can you upgrade your environment to our latest inf1 SDK (compiler 1.19) and retry the compilation to verify the issue still exists in the latest release.

**Comment by DaeyangCho** [comment]
I re-compiled with the latest inf1 SDK (compiler 1.19).
The log related to "An Internal Compiler Error" disappeared, but the log under the "INFO:Neuron:Compile command returned: 1" remains the same.

**Comment by DaeyangCho** [comment]
The following log appears before the internal error log appears.
```
Decoder_54/DecoderAttnBlock_109/SynthesisLayer_111/aten__convolution/transpose:0 - [192, 192, 4, 32], tensor_layout: [F,F,P,B]
 access_layout [F,F,P,B], accesses: ['18437 L', '19626 S'], path: [[_identity,_identity,_identity,_identity]]
Decoder_54/DecoderAttnBlock_109/SynthesisLayer_111/aten_mul_4/mul:0 - [4, 32, 32, 3, 3], tensor_layout: [B,F,F,F,F]
 access_layout [B,F,F,F,F], accesses: ['18409 L', '18368 L', '18367 S'], path: [[_identity,_identity,_identity,_identity,_identity]]
Decoder_54/DecoderAttnBlock_109/SynthesisLayer_111/aten_reshape_1/Reshape:0 - [4, 32], tensor_layout: [B,F]
 access_layout [B,F], accesses: ['18407 L', '19563 S'], path: [[_identity,_identity]]
Decoder_54/DecoderAttnBlock_109/ToRGBLayer_255/aten_reshape/Reshape:0 - [4, 32], tensor_layout: [F,P]
 access_layout [F,P], accesses: ['19572 S', '18597 L'], path: [[_identity,_identity]]
layoutgroup_profile(total_dmas=0, total_tripcount=101632083, total_transpose_tripcount=133548, total_pf_transposes=103, total_bf_transposes=202, block_axes_tripcount=101498535, parallel_axes_tripcount=17
22218, dags_no_parallelism=38)
```

**Comment by micwade-aws** [comment]
@DaeyangCho - without the model for reproduction, we won't be able to help debug what is going on.  I'm going to close this ticket for now, but if it's possible to share the model code privately, please reach out at aws-neuron-support@amazon.com.
