### ISSUE TITLE
Zero1 Tutorial Failing for SignalException

### ISSUE THREAD

**Issue by aws-sadaf** [aws-neuron/aws-neuron-sdk#774]
### Problem Statement:
We see a compilation issue while running the Zero-1 tutorial with Latest compiler and Neuron bits from v2.15.0. 

### Tutorial:
https://awsdocs-neuron-staging.readthedocs-hosted.com/en/release_2.15.0/frameworks/torch/torch-neuronx/tutorials/training/zero1_gpt2.html#zero1-gpt2-pretraining-tutorial

### Neuron Bits:
```
aws-neuronx-collectives/now 2.18.4.0-a734a55eb amd64 [installed,local]
aws-neuronx-devtools/now 2.15.4.0 amd64 [installed,local]
aws-neuronx-dkms/now 2.14.5.0 amd64 [installed,local]
aws-neuronx-gpsimd-customop-lib/now 0.8.1.0 amd64 [installed,local]
aws-neuronx-gpsimd-tools/now 0.8.0.0-dc50bd08c amd64 [installed,local]
aws-neuronx-oci-hook/now 2.2.27.0 amd64 [installed,local]
aws-neuronx-runtime-lib/now 2.18.4.0-f907d44be amd64 [installed,local]
aws-neuronx-tools/now 2.15.4.0 amd64 [installed,local]

NeuronX Compiler version 2.11.0.18+fada6114a

aws-neuronx-runtime-discovery 2.9
libneuronxla                  0.5.524
neuron-torch-tools            1.0.0.484+b2510589d
neuronx-cc                    2.11.0.18+fada6114a
neuronx-distributed           0.5.0
neuronx-hwm                   2.11.0.0+e34678757
torch-neuronx                 1.13.1.1.12.0
torch-xla                     1.13.1+torchneuronc
transformers-neuronx          0.8.235
```

### Steps to reproduce

1. Follow the tutorial to clone the repo and install the requirements. 
2. Run the training script with pre-compilation.
`neuron_parallel_compile bash run_clm.sh MIXED wikitext-103-raw-v1`
3. After successful completion of pre-compilation, trigger the main training job using `bash run_clm.sh MIXED wikitext-103-raw-v1`

### Logs:
```
***** Running training *****
  Num examples = 114248
  Num Epochs = 29
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 100000
  0%|          | 0/100000 [00:00<?, ?it/s]2023-10-11 16:01:48.000333:  457915  INFO ||NEURON_CACHE||: Compile cache path: /home/ubuntu/neuron_cache/gpt_1p5B/ip-10-0-9-227
2023-10-11 16:01:50.000230:  457915  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /home/ubuntu/neuron_cache/gpt_1p5B/ip-10-0-9-227/neuronxcc-2.11.0.18+fada6114a/MODULE_16845508720433978572+6c1f42df/model.neff. Exiting with a successfully compiled graph.
  0%|          | 1/100000 [00:08<233:35:34,  8.41s/it]WARNING:torch.distributed.elastic.agent.server.api:Received 15 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338916 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338917 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338918 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338919 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338920 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338921 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338922 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338923 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338924 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338925 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338926 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338927 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338928 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338929 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338930 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338931 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338932 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338933 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338934 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338935 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338936 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338937 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338938 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338939 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338940 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338941 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338942 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338943 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338944 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338945 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338946 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338947 closing signal SIGTERM
Traceback (most recent call last):
  File "/home/ubuntu/aws_neuron_venv_pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/ubuntu/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 338849 got signal: 15
```

**Comment by jyang-aws** [comment]
issue resolved and verified, will be included in the coming release.
