### ISSUE TITLE
BIRCodegen does not support broadcast patterns, but found one

### ISSUE THREAD

**Issue by greenguy33** [aws-neuron/aws-neuron-sdk#798]
I'm running the Causal Language Model finetuning [script found on the optimum-neuron examples page ](https://github.com/huggingface/optimum-neuron/blob/main/examples/language-modeling/run_clm.py) on a trn1.2xlarge instance. At some point in the pipeline (either during the training or at model saving, depending on how many processes I run per core) the following difficult-to-decipher error is thrown:

`BIRCodegen does not support broadcast patterns, but found one in {0,+,0}[45]`
 
Below is the full stack trace:

```
[INFO|trainers.py:378] 2023-11-09 21:35:33,643 >> Saving model checkpoint to test_clm
[INFO|configuration_utils.py:460] 2023-11-09 21:35:33,645 >> Configuration saved in test_clm/config.json
[INFO|configuration_utils.py:544] 2023-11-09 21:35:33,645 >> Configuration saved in test_clm/generation_config.json
2023-11-09 21:35:34.000903:  15709  INFO ||NEURON_CACHE||: Compile cache path: /tmp/tmp_b9balli/neuron-compile-cache
2023-11-09 21:35:34.000905:  15709  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ec2-user/neuroncc_compile_workdir/11be0679-9e31-4756-b46e-82df545abfba/model.MODULE_5782661062090079200+d41d8cd9.hlo.pb', '--output', '/tmp/ec2-user/neuroncc_compile_workdir/11be0679-9e31-4756-b46e-82df545abfba/model.MODULE_5782661062090079200+d41d8cd9.neff', '--verbose=35']
.............
2023-11-09 21:39:52.000474:  15709  ERROR ||NEURON_CC_WRAPPER||: Compilation failed for /tmp/ec2-user/neuroncc_compile_workdir/11be0679-9e31-4756-b46e-82df545abfba/model.MODULE_5782661062090079200+d41d8cd9.hlo.pb after 0 retries.
Traceback (most recent call last):
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/bin/neuron_cc_wrapper", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/libneuronxla/neuron_cc_wrapper.py", line 298, in main
    neuron_xla_compile(args.input_file, " ".join(unparsed_args), args.output, cache_key=args.cache_key,
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/libneuronxla/neuron_cc_wrapper.py", line 268, in neuron_xla_compile
    ret = compile_with_cache(output, compile_cache, cache_key, execution_mode,
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/libneuronxla/neuron_cc_wrapper.py", line 201, in compile_with_cache
    raise(e)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/libneuronxla/neuron_cc_wrapper.py", line 181, in compile_with_cache
    ret = call_neuron_compiler(
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/libneuronxla/neuron_cc_wrapper.py", line 129, in call_neuron_compiler
    raise RuntimeError(f"Failed compilation with {cmd}: {res.stderr.decode()}")
RuntimeError: Failed compilation with ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/ec2-user/neuroncc_compile_workdir/11be0679-9e31-4756-b46e-82df545abfba/model.MODULE_5782661062090079200+d41d8cd9.hlo.pb', '--output', '/tmp/ec2-user/neuroncc_compile_workdir/11be0679-9e31-4756-b46e-82df545abfba/model.MODULE_5782661062090079200+d41d8cd9.neff', '--verbose=35']: 
2023-11-09T21:39:52Z BIRCodegen does not support broadcast patterns, but found one in {0,+,0}[45]

2023-11-09 21:39:52.779806: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.781583: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.908196: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] StackTrace:
2023-11-09 21:39:52.908242: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** Begin stack trace ***
2023-11-09 21:39:52.908251: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	tsl::CurrentStackTrace()
2023-11-09 21:39:52.908255: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	xla::util::ReportComputationError(tsl::Status const&, absl::lts_20220623::Span<xla::XlaComputation const* const>, absl::lts_20220623::Span<xla::Shape const* const>)
2023-11-09 21:39:52.908259: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2023-11-09 21:39:52.908264: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.908270: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	xla::util::MultiWait::Complete(std::function<void ()> const&)
2023-11-09 21:39:52.908276: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.908280: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.908284: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.908287: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	clone
2023-11-09 21:39:52.908290: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** End stack trace ***
2023-11-09 21:39:52.908293: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-11-09 21:39:52.908297: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Status: INTERNAL: From /job:localservice/replica:0/task:0:
2023-11-09 21:39:52.908300: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 2 root error(s) found.
2023-11-09 21:39:52.908306: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (0) INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.908309: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	 [[{{node XRTExecute}}]]
2023-11-09 21:39:52.908313: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	 [[XRTExecute_G15]]
2023-11-09 21:39:52.908319: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (1) INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.908327: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	 [[{{node XRTExecute}}]]
2023-11-09 21:39:52.908331: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 successful operations.
2023-11-09 21:39:52.908336: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 derived errors ignored.
2023-11-09 21:39:52.908341: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Recent warning and error logs:
2023-11-09 21:39:52.908346: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Traceback (most recent call last):
  File "run_clm.py", line 616, in <module>
2023-11-09 21:39:52.909526: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] StackTrace:
2023-11-09 21:39:52.909556: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** Begin stack trace ***
2023-11-09 21:39:52.909564: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	tsl::CurrentStackTrace()
2023-11-09 21:39:52.909570: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	xla::util::ReportComputationError(tsl::Status const&, absl::lts_20220623::Span<xla::XlaComputation const* const>, absl::lts_20220623::Span<xla::Shape const* const>)
2023-11-09 21:39:52.909575: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2023-11-09 21:39:52.909580: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.909583: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	xla::util::MultiWait::Complete(std::function<void ()> const&)
2023-11-09 21:39:52.909587: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.909590: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.909594: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	
2023-11-09 21:39:52.909597: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	clone
2023-11-09 21:39:52.909603: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] *** End stack trace ***
2023-11-09 21:39:52.909606: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 
2023-11-09 21:39:52.909609: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Status: INTERNAL: From /job:localservice/replica:0/task:0:
2023-11-09 21:39:52.909612: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 2 root error(s) found.
2023-11-09 21:39:52.909616: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (0) INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.909619: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	 [[{{node XRTExecute}}]]
2023-11-09 21:39:52.909623: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	 [[XRTExecute_G15]]
2023-11-09 21:39:52.909627: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   (1) INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.909633: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 	 [[{{node XRTExecute}}]]
2023-11-09 21:39:52.909636: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 successful operations.
2023-11-09 21:39:52.909639: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] 0 derived errors ignored.
2023-11-09 21:39:52.909642: E tensorflow/compiler/xla/xla_client/xla_util.cc:90] Recent warning and error logs:
2023-11-09 21:39:52.909654: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
2023-11-09 21:39:52.909659: E tensorflow/compiler/xla/xla_client/xla_util.cc:90]   OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Traceback (most recent call last):
  File "run_clm.py", line 616, in <module>
    main()
  File "run_clm.py", line 565, in main
    trainer.save_model()  # Saves the tokenizer too for easy upload
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/trainers.py", line 419, in save_model
    self._save_xla(output_dir)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/trainers.py", line 410, in _save_xla
    self.model.save_pretrained(output_dir, is_main_process=self.args.should_save, save_function=xm.save)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/modeling_utils.py", line 1993, in save_pretrained
    save_function(shard, os.path.join(save_directory, shard_file))
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 1216, in save
    cpu_data = _maybe_convert_to_cpu(data, convert=should_write_data)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 1234, in _maybe_convert_to_cpu
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 429, in transform
    self._convert()
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 401, in _convert
    self._converted_tensors = self._convert_fn(self._tensors)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 1225, in convert_fn
    torch_xla._XLAC._xla_sync_multi(
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
	 [[XRTExecute_G15]]
  (1) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
    main()
  File "run_clm.py", line 565, in main
    trainer.save_model()  # Saves the tokenizer too for easy upload
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/trainers.py", line 419, in save_model
    self._save_xla(output_dir)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/optimum/neuron/trainers.py", line 410, in _save_xla
    self.model.save_pretrained(output_dir, is_main_process=self.args.should_save, save_function=xm.save)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/transformers/modeling_utils.py", line 1993, in save_pretrained
    save_function(shard, os.path.join(save_directory, shard_file))
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 1216, in save
    cpu_data = _maybe_convert_to_cpu(data, convert=should_write_data)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 1234, in _maybe_convert_to_cpu
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 429, in transform
    self._convert()
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 401, in _convert
    self._converted_tensors = self._convert_fn(self._tensors)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/core/xla_model.py", line 1225, in convert_fn
    torch_xla._XLAC._xla_sync_multi(
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
	 [[XRTExecute_G15]]
  (1) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/__init__.py", line 133, in _prepare_to_exit
    _XLAC._prepare_to_exit()
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
	 [[XRTExecute_G15]]
  (1) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_xla/__init__.py", line 133, in _prepare_to_exit
    _XLAC._prepare_to_exit()
RuntimeError: INTERNAL: From /job:localservice/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
	 [[XRTExecute_G15]]
  (1) INTERNAL: neuronx-cc compilation failed.
	 [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Recent warning and error logs:
  OP_REQUIRES failed at tpu_execute_op.cc:266 : INTERNAL: neuronx-cc compilation failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9559) of binary: /home/ec2-user/finetune/aws_neuron_venv_pytorch/bin/python
Traceback (most recent call last):
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ec2-user/finetune/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-09_21:39:57
  host      : ip-10-0-255-91.ec2.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 9560)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-09_21:39:57
  host      : ip-10-0-255-91.ec2.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9559)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Here are the versions of relevant libraries that I am using:

```
aws-neuronx-runtime-discovery=2.9
libneuronxla=0.5.538
neuronx-cc=2.11.0.34+c5231f848
optimum=1.14.0
optimum-neuron=0.0.13
torch=1.13.1
torch-neuronx=1.13.1.1.12.0
torch-xla=1.13.1+torchneuronc
```

I have searched this error and not been able to find anything. Probably it is a library incompatibility, but any ideas on which library needs a different version?

**Comment by mrnikwaws** [comment]
Close since issue is resolved
