### ISSUE TITLE
NRT 2.16 Beta: Simple Recv Graph Doesn't Compile

### ISSUE THREAD

**Issue by xanderdunn** [aws-neuron/aws-neuron-sdk#800]
We have some communication test graphs that we run as part of our unit test suite.

The graph: [rust_hlo_run_test_send_recv_rank_2.pb.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/13641297/rust_hlo_run_test_send_recv_rank_2.pb.zip)

The command: `neuronx-cc compile /mnt/drive1/tmp/rust_hlo_run_test_send_recv_rank_2.pb --framework=XLA --target=trn1 --model-type=transformer --auto-cast=none --output /mnt/drive1/tmp/run_test_send_recv_rank_2_6247465408852162857.neff`

XLA HLO:
```
HloModule xla_computation_ordered_wrapper, entry_computation_layout={(f32[4]{0})->(f32[4]{0})}

ENTRY main.9 {
  Arg_0.1 = f32[4]{0} parameter(0)
  after-all.2 = f32[4]{0} after-all(Arg_0.1)
  recv.3 = (f32[4]{0}, u32[], token[]) recv(after-all.2), channel_id=3
  recv-done.4 = (f32[4]{0}, token[]) recv-done(recv.3), channel_id=3
  get-tuple-element.5 = f32[4]{0} get-tuple-element(recv-done.4), index=0
  add.6 = f32[4]{0} add(get-tuple-element.5, get-tuple-element.5)
  ROOT tuple.7 = (f32[4]{0}) tuple(add.6)
}
```
If there is any modification we should make to this XLA^^, please let us know. This graph just receives from a `send` in another graph, doubles the value, and outputs it.

Output:
```
2023-12-11T21:46:07Z Compilation is optimized for best performance and compilation time. For faster compilation time please use -O1
Process Process-1:
Traceback (most recent call last):
  File "neuronxcc/driver/CommandDriver.py", line 343, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
  File "neuronxcc/driver/commands/CompileCommand.py", line 1183, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
  File "neuronxcc/driver/commands/CompileCommand.py", line 1142, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/commands/CompileCommand.py", line 1159, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/commands/CompileCommand.py", line 1162, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
  File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
  File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
  File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
  File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
  File "neuronxcc/driver/jobs/Frontend.py", line 405, in neuronxcc.driver.jobs.Frontend.Frontend.runSingleInput
  File "neuronxcc/driver/jobs/Frontend.py", line 203, in neuronxcc.driver.jobs.Frontend.Frontend.runXLAFrontend
  File "neuronxcc/driver/jobs/Frontend.py", line 186, in neuronxcc.driver.jobs.Frontend.Frontend.runHlo2Tensorizer
neuronxcc.driver.Exceptions.CompilerInvalidInputException: ERROR: Failed command  /home/ubuntu/.local/lib/python3.8/site-packages/neuronxcc/starfish/bin/hlo2penguin --input /mnt/drive1/tmp/rust_hlo_run_test_send_recv_rank_2.pb --out-dir ./ --output penguin.py --remat --max-costly-ops=2 --max-live-in-size=5 --max-remat-chain-size=10 --max-mem-multiple=1.8 --min-def-use-distance=500 --remat-policy=transformer --allow-same-pass-remat=true --split-abc --layers-per-module=1 --coalesce-all-gathers=false --coalesce-reduce-scatters=false --coalesce-all-reduces=false --emit-tensor-level-dropout-ops --emit-tensor-level-rng-ops --native-to-custom-softmax
------------
Reported stdout:
2023-12-11 16:46:07.598686: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
DEBUG: needsModular? No. macCnt 0
INFO: Switching to single-module compile. PrePartitionPipe skipped.
INFO: Found memory bound graph
Replaced 0 dropout sequences with OffloadedDropout
INFO: HloMacCount has found 0
INFO: Traffic has found 32
INFO: AIF 0
HLO Ops used in computation: add after-all custom-call get-tuple-element parameter tuple
INFO: Number of native softmaxes detected and replaced: 0
%1 = "mhlo.after_all"(%arg0) : (memref<4xf32>) -> tensor<4xf32>
double free or corruption (out)

------------
Reported stderr:
None
------------
Import of the HLO graph into the Neuron Compiler has failed.
This may be caused by unsupported operators or an internal compiler error.
More details can be found in the error message(s) above.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "neuronxcc/driver/CommandDriver.py", line 350, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand_in_process
  File "neuronxcc/driver/CommandDriver.py", line 345, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
  File "neuronxcc/driver/CommandDriver.py", line 111, in neuronxcc.driver.CommandDriver.handleError
  File "neuronxcc/driver/GlobalState.py", line 102, in neuronxcc.driver.GlobalState.FinalizeGlobalState
  File "neuronxcc/driver/GlobalState.py", line 82, in neuronxcc.driver.GlobalState._GlobalStateImpl.shutdown
  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/dev/Kholinar/xla/neuronxcc-fkcx04_i'
```

This graph worked on NRT 2.15.

I'm using:
```
$ dpkg-query -W -f='${binary:Package} ${Version}\n' | grep '^aws-neuron'
aws-neuronx-collectives 2.19.5.0-530fb3064
aws-neuronx-dkms 2.15.9.0
aws-neuronx-gpsimd-customop-lib 0.9.1.0
aws-neuronx-gpsimd-tools 0.9.0.0-e7d693355
aws-neuronx-runtime-lib 2.19.4.0-ed642d216
aws-neuronx-tools 2.16.1.0
ubuntu@trn2:~/dev/Kholinar/xla$ neuronx-cc --version
NeuronX Compiler version 2.12.40.0+4928b2c8b

Python version 3.8.10
HWM version 2.12.0.0-422c9037c
NumPy version 1.24.4

Running on AMI ami-01257e71ecb2f431c
Running in region usw2-az4
```

**Comment by xanderdunn** [comment]
McClean pointed out that after-all isn't a supported op with neuronx-cc, so we've removed its usage and these send/recv graphs now compile and run as expected, thanks!
