### ISSUE TITLE
NeuronXCC fails to compile ViT model

### ISSUE THREAD

**Issue by liechtym** [aws-neuron/aws-neuron-sdk#806]
Hello!

I've been working on getting MiniGPT4 working on Inf2. While I have been able to get the LLM portion running successfully on neuron, I am struggling to get to get the ViT model working.

Here's where I'm attempting to compile the model:
https://github.com/liechtym/MiniGPT-4/blob/neuronx/minigpt4/models/base_model.py#L160-L165

I'm running on a `Inf2.8xlarge` instance.

Here are my installation steps on the instance:
```
source /opt/aws_neuron_venv_pytorch/bin/activate

git clone --single-branch --branch neuronx https://github.com/liechtym/MiniGPT-4.git
pip install -e ./MiniGPT-4
cd MiniGPT-4
pip install -r requirements.txt

python -m pip install optimum[neuronx]
python -m pip install --upgrade neuronx-cc==2.* --pre torch-neuronx==2.0.* torchvision
pip install numpy==1.23.4
```

And then I run via:
```
python modular.py
```

Here's the output I get:
```
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert H == self.img_size[0] and W == self.img_size[1], \
2023-12-27 22:27:36.000692:  6173  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2023-12-27 22:27:36.000692:  6173  ERROR ||NEURON_CC_WRAPPER||: Got a cached failed neff at /var/tmp/neuron-compile-cache/neuronxcc-2.12.54.0+f631c2365/MODULE_3138309541370765992+d41d8cd9/model.neff. Will skip compilation, please set --retry_failed_compilation for recompilation: 
 Failed compilation with ['neuronx-cc', 'compile', '--target=trn1', '--framework=XLA', '/tmp/neuroncc_compile_workdir/66c34a5f-d608-45a4-9b55-eff4e28f2690/model.MODULE_3138309541370765992+d41d8cd9.hlo_module.pb', '--output', '/tmp/neuroncc_compile_workdir/66c34a5f-d608-45a4-9b55-eff4e28f2690/model.MODULE_3138309541370765992+d41d8cd9.neff', '--verbose=35']: Process Process-1:
Traceback (most recent call last):
  File "neuronxcc/driver/CommandDriver.py", line 343, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
  File "neuronxcc/driver/commands/CompileCommand.py", line 1184, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
  File "neuronxcc/driver/commands/CompileCommand.py", line 1143, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/commands/CompileCommand.py", line 1160, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/commands/CompileCommand.py", line 1163, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
  File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
  File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
  File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
  File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
  File "neuronxcc/driver/jobs/Frontend.py", line 405, in neuronxcc.driver.jobs.Frontend.Frontend.runSingleInput
  File "neuronxcc/driver/jobs/Frontend.py", line 203, in neuronxcc.driver.jobs.Frontend.Frontend.runXLAFrontend
  File "neuronxcc/driver/jobs/Frontend.py", line 186, in neuronxcc.driver.jobs.Frontend.Frontend.runHlo2Tensorizer
neuronxcc.driver.Exceptions.CompilerInvalidInputException: ERROR: Failed command  /opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/neuronxcc/starfish/bin/hlo2penguin --input /tmp/neuroncc_compile_workdir/66c34a5f-d608-45a4-9b55-eff4e28f2690/model.MODULE_3138309541370765992+d41d8cd9.hlo_module.pb --out-dir ./ --output penguin.py --layers-per-module=1 --coalesce-all-gathers=false --coalesce-reduce-scatters=false --coalesce-all-reduces=false --emit-tensor-level-dropout-ops --emit-tensor-level-rng-ops
------------ 
Reported stdout: 
DEBUG: needsModular? No. macCnt 520719260160
INFO: Switching to single-module compile. PrePartitionPipe skipped.
INFO: Found compute bound graph
Replaced 0 dropout sequences with OffloadedDropout
INFO: HloMacCount has found 260359630080
INFO: Traffic has found 1973475611
INFO: AIF 263.859
HLO Ops used in computation: abs add batch-norm-training broadcast compare concatenate constant convert convolution custom-call divide dot exponential get-tuple-element and or multiply parameter reduce reshape select slice subtract transpose tuple 
hlo2penguin: hilo/puffin/lib/CodegenDriver.cpp:248: mlir::Value mlir::penguin::CodegenDriver::emitMatmult(mlir::Value, mlir::Value, llvm::ArrayRef<long int>, llvm::ArrayRef<long int>, llvm::ArrayRef<long int>, llvm::ArrayRef<long int>): Assertion `elemTy == lhsTy.getElementType() && "unexpected element type."' failed.

------------ 
Reported stderr: 
None
------------                       
Import of the HLO graph into the Neuron Compiler has failed.                       
This may be caused by unsupported operators or an internal compiler error.                       
More details can be found in the error message(s) above.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "neuronxcc/driver/CommandDriver.py", line 350, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand_in_process
  File "neuronxcc/driver/CommandDriver.py", line 345, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
  File "neuronxcc/driver/CommandDriver.py", line 111, in neuronxcc.driver.CommandDriver.handleError
  File "neuronxcc/driver/GlobalState.py", line 102, in neuronxcc.driver.GlobalState.FinalizeGlobalState
  File "neuronxcc/driver/GlobalState.py", line 82, in neuronxcc.driver.GlobalState._GlobalStateImpl.shutdown
  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/MiniGPT-4/neuronxcc-u35c1edk'
.
2023-12-27 22:27:36.717702: F ./tensorflow/compiler/xla/xla_client/debug_macros.h:27] Non-OK-status: status.status() status: INTERNAL: CompileImpl: error condition error != 0: <class 'subprocess.CalledProcessError'>: Command '' died with <Signals.SIGHUP: 1>.
*** Begin stack trace ***
	tsl::CurrentStackTrace()
	std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > ConsumeValue<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >(tsl::StatusOr<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >&&)
	xla::PjRtComputationClient::Compile(std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> >)
	torch_xla::XLAGraphExecutor::Compile(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, absl::lts_20220623::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorCollection const&, torch::lazy::LazyGraphExecutor::PostOrderData*, std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&)
	torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20220623::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&, bool)
	torch_xla::XLAGraphExecutor::GetTensorsFused(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*)
	torch_xla::XLAGraphExecutor::GetTensors(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*)
	torch_xla::bridge::XlaCreateTensorList(c10::IListRef<at::Tensor> const&)
	torch_xla::XLANativeFunctions::_to_cpu(c10::ArrayRef<at::Tensor>)
	
	at::_ops::_to_cpu::call(c10::ArrayRef<at::Tensor>)
	
	at::native::cpu_fallback(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)
	torch_xla::xla_cpu_fallback(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)
	at::native::_call_fallback_fn<&torch_xla::xla_cpu_fallback, at::_ops::_local_scalar_dense, false, c10::Scalar (at::Tensor const&)>::call(at::Tensor const&)
	torch_xla::XLANativeFunctions::_local_scalar_dense(at::Tensor const&)
	
	at::_ops::_local_scalar_dense::redispatch(c10::DispatchKeySet, at::Tensor const&)
	
	
	at::_ops::_local_scalar_dense::call(at::Tensor const&)
	at::native::item(at::Tensor const&)
	
	at::_ops::item::call(at::Tensor const&)
	at::native::is_nonzero(at::Tensor const&)
	at::_ops::is_nonzero::call(at::Tensor const&)
	
	
	
	
	
	PyObject_IsTrue
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCode
	
	
	
	PyRun_SimpleFileExFlags
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	_start
*** End stack trace ***
```

Thanks for your help! If I need to report this issue to another repo, let me know.

Edit: I forgot to include the AMI! I'm using "Deep Learning AMI Neuron PyTorch 1.13 (Ubuntu 20.04) 20231205"

**Comment by aws-taylor** [comment]
Thanks @liechtym,

 We're investigating the issue. I'll update once we have more information.
 
 -T

**Comment by liechtym** [comment]
Any update on this @aws-taylor ?

**Comment by jeffhataws** [comment]
Hi @liechtym , 

When I tried to reproduce using release 2.16, I get a different error. Do you know if https://github.com/liechtym/MiniGPT-4.git has changed since you last report?

```
(aws_neuron_venv_pytorch) ubuntu@ip-10-0-8-193:~/MiniGPT-4$ python modular.py                             
Downloading...                  
From (uriginal): https://drive.google.com/uc?id=11nAPjEok8eAGGEG1N2vXo3kBLCg0WgUk
From (redirected): https://drive.google.com/uc?id=11nAPjEok8eAGGEG1N2vXo3kBLCg0WgUk&confirm=t&uuid=706c5b90-df05-4999-8de3-ce891d31a694
To: /home/ubuntu/MiniGPT-4/pretrained_minigpt4_llama2_7b.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 277M/277M [00:02<00:00, 97.5MB/s]
Initializing Chat               
Loading Visual Encoder...       
/home/ubuntu/aws_neuron_venv_pytorch_r2.15/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:368: UserWarning: Unexpected keyword arguments: ['separate_weights']
  warnings.warn(                
Traceback (most recent call last):
  File "modular.py", line 108, in <module>
    chatbot = LLama2Chatbot(cfg_path, gpu_id)
  File "modular.py", line 63, in __init__
    self.model = model_cls.from_config(model_config)
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/minigpt4.py", line 172, in from_config
    model = cls(              
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in __init__
    super().__init__(       
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/minigpt_base.py", line 56, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/base_model.py", line 166, in init_vision_encoder
    visual_encoder = torch_neuronx.trace(visual_encoder, sample_input, separate_weights=True)
  File "/home/ubuntu/aws_neuron_venv_pytorch_r2.15/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 386, in trace
    neff_filename, metaneff, flattener, packer = _trace(
  File "/home/ubuntu/aws_neuron_venv_pytorch_r2.15/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 447, in _trace
    ) = xla_trace(              
  File "/home/ubuntu/aws_neuron_venv_pytorch_r2.15/lib/python3.8/site-packages/torch_neuronx/xla_impl/hlo_conversion.py", line 134, in xla_trace
    context.build(tensors)
RuntimeError: Error while lowering: [UNKNOWN_SCALAR[]] xla::device_data, xla_shape=f16[1408]{0}, device=NEURON:0
Error: ./tensorflow/compiler/xla/xla_client/pjrt_computation_client.h:155 : Check failed: HasValue() 
*** Begin stack trace ***
        tsl::CurrentStackTrace()
        xla::PjRtComputationClient::PjRtData::GetOpaqueHandle()
        torch_xla::LoweringContext::GetParameter(std::shared_ptr<torch::lazy::BackendData> const&)
        torch_xla::DeviceData::Lower(torch_xla::LoweringContext*) const
        torch_xla::LoweringContext::LowerNode(torch::lazy::Node const*)
        torch_xla::LoweringContext::GetOutputOp(torch::lazy::Output const&)

```

**Comment by liechtym** [comment]
Let me check this out and I'll get back to you soon @jeffhataws

**Comment by liechtym** [comment]
@jeffhataws 

I upgraded to 2.16 and got the following error:

```
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuron/libtorchneuron.py:16: UserWarning: A different version of "libtorchneuron.so" has already been loaded.
  warnings.warn('A different version of "libtorchneuron.so" has already been loaded.')
Initializing Chat
Loading Visual Encoder...
/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:368: UserWarning: Unexpected keyword arguments: ['separate_weights']
  warnings.warn(
2024-01-08T14:43:46Z Compilation is optimized for best performance and compilation time. For faster compilation time please use -O1
Process Process-1:
Traceback (most recent call last):
  File "neuronxcc/driver/CommandDriver.py", line 343, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
  File "neuronxcc/driver/commands/CompileCommand.py", line 1184, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
  File "neuronxcc/driver/commands/CompileCommand.py", line 1143, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/commands/CompileCommand.py", line 1160, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/commands/CompileCommand.py", line 1163, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
  File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
  File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
  File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
  File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
  File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
  File "neuronxcc/driver/jobs/Frontend.py", line 405, in neuronxcc.driver.jobs.Frontend.Frontend.runSingleInput
  File "neuronxcc/driver/jobs/Frontend.py", line 203, in neuronxcc.driver.jobs.Frontend.Frontend.runXLAFrontend
  File "neuronxcc/driver/jobs/Frontend.py", line 186, in neuronxcc.driver.jobs.Frontend.Frontend.runHlo2Tensorizer
neuronxcc.driver.Exceptions.CompilerInvalidInputException: ERROR: Failed command  /opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/neuronxcc/starfish/bin/hlo2penguin --input /tmp/tmpypq1mh7w/model --out-dir ./ --output penguin.py --layers-per-module=1 --coalesce-all-gathers=false --coalesce-reduce-scatters=false --coalesce-all-reduces=false --emit-tensor-level-dropout-ops --emit-tensor-level-rng-ops
------------ 
Reported stdout: 
INFO: Found memory bound graph
Replaced 0 dropout sequences with OffloadedDropout
INFO: HloMacCount has found 260359630080
INFO: Traffic has found 1975142672
INFO: AIF 263.636
HLO Ops used in computation: add batch-norm-training broadcast concatenate constant convert convolution custom-call divide dot exponential get-tuple-element multiply parameter reduce reshape slice subtract transpose tuple 
ElementsAttr does not provide iteration facilities for type `float`, see attribute: dense<"0x9A3B7121753610388AB6BFA683B507B00EA9822B0A359E3796B0E2B53FB619B3113210B1B4B81AB1E03985B026B751B1B1B9E730552AB1B2A5AF3B392AA5C72C1D25FCB310B2E633773AAEB3B9366534E6B18B32C8340B36473A2DBF3EBAF93E59A545B28AB5C82EED342B38C2B06330E63CE43ABDBD1CBC98B250A807B316BAB2348B2F96AFE0B1E6AF5F377AAED8312E2EE336CB159C354BB47B3204B7C4B67FBDF439ED361035AE36222CA3B7CCA293B8D2B00038D53A50347D3A4438C636F9B53AB8C3B03DBA15ACA833BC35812A89391E36C1339B2DC5362FB45A34A135A5AC622E3AB74536363591A9DD3937AF31B4E63CFE3820BA072BAB35BA31EB2960388E9435368DAC2B2F612CDC3B29B15037F53ADEB42DADCF38163272B420BA8BB0F1B9A4B1ABB5962A6CB5872C92B7672D74B4EBBAA7B6BCB7E8ACB42F932F733029B7642FEDB5EEB307BB6CB598B61D2FD537F3B5EF9FD8B6B0B37FA9FFAD1224C7AE66B529ACEB3532371D347BB21C3603BC063875B4DC30F435C732022F28ADAFB2CD330F2CABB1F02A5532A5B41EB6E1361736ABB4DC311A337B2AE427952D5D3276B92630F5B18E3279B928A9FDAAD12F73BDB63ABC2BB5B245235E309F408FB0523B6FB1FCB6DB39F83427B4DDB9D3B44531D9B722BCA92C5B2D7334B42C1D3AE7B53335CB28083CBA34C2AC5DB74AB15FB5ADB5ED37DE3140AEB9364A348D2A20ABA4B848340D21C3B6E93A8639393B89AC7E363C3657B786ABB1B7AAB885337B303CB4B0A5EFAD41B42FB587AE252A16AD3A33F1B8153408B44F30E4B08834B8319334C5B07BACCDB8F8B89DB40F3405265D2BAB2AE0B2B1BA0A31B19F7EB64D25D32D972F1CB9B631FABAC4B6B5B43634A435522A80B34B2FB4B942AA9ABA87B22EBC692CC1B7A5B122B52F317EBB55AFEEB7F23872B198B7BA2FD338C138983C6036F5B4F3AE78AC1AB5CDB1D7A6FF2A7D343521E6361BAB302EB4ADA835ED264CB640B04B3558BD4CA448B0782EDEB9D92C0F349038BCB747A09522633518B5C0A1C83DF49F713BB031C5AE3EAD2BBB6EADACAE173357A75635323DF1AE20B942308C3CC2AD3730DB399434EA30E929C4380035E3AC7AAD0A1F382E32B35DB9B13549B9C5B1663AF537893810B1AA39C7B1A2B6ADB882B2C0B773A20A2F242C3EB3BDA4D7B518B1D4B75236323CD6B9E0B6BEA4B1AB44A5FDC1A136F7BE32B8A138942FAAB4FE326AA57F333CB974A76D3DC9B7783514353BB55024AC3F6EB86434E9335CB0C42F8E3A5CB4762CE138BAB999351E322630AEB5813878B9AE37AC2AF5B053223CBD333D9639482FAD2E3739FAB933386CB1CA3373B6F338853748AAEEB768345FB042A997AD89B50CB4AC298DB508A5392B9A3BAA36C13C5235272A03B3ECB2842F7E2AB5ABFC377DB9B7B1CA38153BD7AD6D383DBBC034A138F5AE2AAAA2382733D5B70E3690B59E398FB7C0240935CEBD25B34E301D3C0535953184B97BB8DCB4A9B8BA3432B697B923B751381A33FDA3C0B51F28B63803318BB97F2E66ABFFB7A624BAAE1DB28DAF423446B93D32F3AD7B34DE394E373C32A6A959A66628B4BC35311DAE53AF3AB94CB4B4A362B85B3543B9E1AD533200B3102DB93160B59FA236AC9D399F29DCB242B5E135B226421AF5A9F1BE11B6D1B82FBE77372C333DA5A3B0A8A8A8362A39B4A8852F513DDF12403482B67B3739B4B1B49FAC3739363517B08FBA0B340936CC388FB77CA7FCB52D3053B87624992AA7AED03677B51CADE53714B8AD300490B5B294BC36B1ECB19B3A5E34B131D72D9F9E51B8169E02BC4C320DB8763549379C24BE33B7348C330F3504B992BE42B84E2ABA2BB6AE88B91D3852B5F0352D2FBAA898B45336892D223839AFE1B3C23C65B45B3ACBAE2DB4A01F40386DB847B03DBADD2DD1B5A12B252E2F2BFEB196207D2668B7A83081B7BC3813B7B1B9163199AF85358524792490B404B8E7B7F2AD6EB0F3AF2A3B4C3B43B74FB42DB9552878B938A18934D62FACB135BC6AB688B44DA8DE2D1D2E112B19B87C269432AF3422B31734413935AC9E39B1AF542C0FB7F22ED1B49E348B2F2FB9DDAC612D5336C0B025B2CCB5829A94A6E7B2832D592EC9B9E62CDDB20733F0AE062AB433D0379AA9CCBA1DB652B445B20CB695312A38592E8FBBFA3CAF344B37E8B1CB367E38B334F133CFB0392F552AB6A37B34B9B78EB423B3932CB638CFB2823511394D38DEA43633E4B31E3038B10EB70EB86B2777B837BD303401B66C346134B435213285B93D3923B369BA973575BCAE3743B703C599B4B4B4C433EA2F8030DA2B432DD5BF31364CB97297A238FB2E4FBBB3343038592C99B1822F00B804A8C6346CBB1FB76F39E8B45AB73635D2B20639AEADF4B4731EF43401BCE12B59308AB8ACB063BB1C3812B480B8962916C371A849BAD63AC9AB19338A389B29CB3B9337E2380631A2A6443B6FA6BEB79B3375B477B529C09BB59E380A34483C9322983C20441AB14FB8A43923B380B3CB3C4F3D5930D73ABCA6E5396A3DCE389B35C4AF2C3720ADA032DF2E1C2C09390238CCB7F2B1023C2EB13815CA2E23B023B4FF303835C4B82B36C936CA374CB402394DB5B4B89FB3EBB491BB5CAE83B719B545B84E31D2AF43AC80B3DA2AC62C5DB4253952B68431402DF935909C20B698B7463365B48327A03067BBF43016A8CEB6B4B1682DEFAF7FA6BF39BD3320B57CB417B289BA73B174378A28D9313EAAA534593774B3DD1D6FB88DAAA43CE632D1A9E735762C653904310A362DAF45BAFAB029379ABB1DBA9FB95FACA9A82631D6A7A5B5D0311332143939B966B8A1B9D93566B5623D3BAF4E341E1BA5AE9FAD4230262CBBB861AC372E08AAE1AF38397039D42AA82A6B35E3356233223863A9B6B04132FD9C97ADFE1A61B7A336913BB6B5292C0E3338A0CFA4723B9732693142B530B7472C01B36A3224B6C4B3B8ACE42D9790523ACAB3B22785B5AC3475B51838182FA4B2A3BC74300E3012B432384A282A29423CFAA80EAEAF3A0AB715341DB30FA55330BDA18F37E724503427B201323439E3304A3686301F90863192B9363346ACD0B3183EE0B11AB55BAE1F2D7436B437143B06B5713B31A6F62CB73A942E51376E3A9FAAE33727A0C4B9352BEEB438AE95BA0F37D7B2302410357DB76F3ACE2F0EAD05AC383C11B63235C2385BA01A2EBE3DC42E6F33E7ABFA3A85A63B330CBCD7B40EAA62ADBC35F8381DB56CB3852DD52EBAB8DDB345348AAD56BD292509ADB52EB83262A8B02E17B400BAF9BAB5ACE7B0E536DE31B732BD346C2C37B688349238BBA941B0BE29A8BA603DB4351CAB44B875389AACD3B8B52FE0BA7CACBA34F3B2E636A73070AD26366D2DED32063538B918B6BDA9AC2E3239CFB46EBF7EB41FB4753182B2EFAD6529A8354C286C39502E3D387EBC9A3382B77BB1FDB059B866B64A2E512EF836BDB406B86AA7003537BD7CB999B3BCA2AB193AAFC338DC382B2CC8AB563D17346FAE1130BC344A255F34EC37AEB81E381C3CB7B31EB3082BEE2937BD603598B440B2FCAA29376730E4AFACB610B38138342CCA31FC380E372BB0F239FDADCE3764338A3955B6A2B63DB498B01BBBFD1CB8B809B22C35DAB2C9B53DAB4D2A1CBEA1AC1330BCB708A8A3B6AA322E3AC228922EFFB3EEB7552E5C35042E7B26F8B883B3613A3A303E3167BA85BCA7B81132CAB6E09209AF272B87A7C93855397C3205B25DB27EB547AF3C2D4FB4F9B5C32710377832F33995357B29B12DE9AD47B249359D2CAD2D33B220312A2E2C3ADB34FBA5BD2E06C2F3B646B07DB0DC3CB9B09F292EB586A84DBDC0B4DDC39A3676331033B13600384DB409B98DB1E9BA2DAC5E31703BFB3963B7403B4929DA36C92EFFB7D82CBD302539721CD82B6AB4892AA6B67A39A72AB7A7C3B4693730230FB753319728CA3D7B34DDAEB3B407C293B526B213B5"> : tensor<1408xf16>

------------ 
Reported stderr: 
None
------------                       
Import of the HLO graph into the Neuron Compiler has failed.                       
This may be caused by unsupported operators or an internal compiler error.                       
More details can be found in the error message(s) above.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "neuronxcc/driver/CommandDriver.py", line 350, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand_in_process
  File "neuronxcc/driver/CommandDriver.py", line 345, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
  File "neuronxcc/driver/CommandDriver.py", line 111, in neuronxcc.driver.CommandDriver.handleError
  File "neuronxcc/driver/GlobalState.py", line 102, in neuronxcc.driver.GlobalState.FinalizeGlobalState
  File "neuronxcc/driver/GlobalState.py", line 82, in neuronxcc.driver.GlobalState._GlobalStateImpl.shutdown
  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/MiniGPT-4/neuronxcc-b365yhy0'
Traceback (most recent call last):
  File "modular.py", line 108, in <module>
    chatbot = LLama2Chatbot(cfg_path, gpu_id)
  File "modular.py", line 63, in __init__
    self.model = model_cls.from_config(model_config)
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/minigpt4.py", line 172, in from_config
    model = cls(
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in __init__
    super().__init__(
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/minigpt_base.py", line 56, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/home/ubuntu/MiniGPT-4/minigpt4/models/base_model.py", line 166, in init_vision_encoder
    visual_encoder = torch_neuronx.trace(visual_encoder, sample_input, separate_weights=True)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 386, in trace
    neff_filename, metaneff, flattener, packer = _trace(
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 479, in _trace
    neff_filename = hlo_compile(model_dir, compiler_workdir, compiler_args)
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 283, in hlo_compile
    raise RuntimeError(f"neuronx-cc failed with {status}")
RuntimeError: neuronx-cc failed with 1
```

From the trace it looks like we're using different virtual environments. I'm using aws_neuron_venv_pytorch, and my pip freeze says `torch==2.1.2` `torch-neuronx==2.1.1.2.0.0b0`

The only change that's happened to the github branch I specified is this small tidbit to load directly from torch neuron x: https://github.com/liechtym/MiniGPT-4/commit/bcc6e713a090732a8b699e04b647416c911711e2#diff-86c9b4c1dbfbb96ec8d1b0c16fa5eb95937ad214b19a1491098c1ee9906ba0a8

Let me know if you need any more information from my environment to debug this.

**Comment by liechtym** [comment]
Any update on this @jeffhataws @aws-taylor ?

**Comment by jeffhataws** [comment]
Hi @liechtym ,
Thanks. I have reproduced your issue after removing the inf1 packages torch-neuron and neuron-cc from the environment (they were installed via the requirements.txt, so maybe you can remove them if you are not targeting inf1). We will take a closer look at the failure.

**Comment by liechtym** [comment]
Thanks @jeffhataws! I will remove those since I'm only targeting Inf2. Looking forward to your diagnosis.

**Comment by liechtym** [comment]
Any update on this @jeffhataws ?

**Comment by jeffhataws** [comment]
Hi @liechtym , currently it looks like the problem is due to the mixed precision in this model that is not yet supported by Neuron. Will you try to turn off mixed precision in the model?

**Comment by liechtym** [comment]
@jeffhataws I will give this a try and report back

**Comment by jyang-aws** [comment]
Please re-open the ticket if you still see issues. thanks!
