### ISSUE TITLE
 Compiler generated too many instructions (6888787). This maybe due to a failure in parallelism extraction by the tensorizer.

### ISSUE THREAD

**Issue by Sadden** [aws-neuron/aws-neuron-sdk#819]
Hi, 
I got following errors when compiling the llama2-13b-chat-hf model. 

```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:07<00:00,  1.48it/s]
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at Llama-2-13b-chat-hf and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2024-01-17 22:59:23.000056:  25606  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000058:  25606  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/4aa81d29-6e94-4a04-843b-5d062ddf7da9/model.MODULE_2c7f9ec5f5c491144500+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/4aa81d29-6e94-4a04-843b-5d062ddf7da9/model.MODULE_2c7f9ec5f5c491144500+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
2024-01-17 22:59:23.000133:  25607  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000136:  25607  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/607b99c6-e69f-4bd9-ae40-18acf1477b9f/model.MODULE_ba97d39078f94da6e7bc+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/607b99c6-e69f-4bd9-ae40-18acf1477b9f/model.MODULE_ba97d39078f94da6e7bc+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
2024-01-17 22:59:23.000242:  25608  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000247:  25608  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
2024-01-17 22:59:23.000389:  25609  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000392:  25609  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/695f19d4-0574-46f2-981c-8a40a45e6f7b/model.MODULE_fd558d07f828053e1bac+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/695f19d4-0574-46f2-981c-8a40a45e6f7b/model.MODULE_fd558d07f828053e1bac+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
.2024-01-17 22:59:23.000495:  25610  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000498:  25610  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/45db6220-6c73-49b8-beeb-98b16bbfff50/model.MODULE_8a055c728341a0876dcf+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/45db6220-6c73-49b8-beeb-98b16bbfff50/model.MODULE_8a055c728341a0876dcf+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
..2024-01-17 22:59:23.000696:  25611  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000699:  25611  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/8e7029d0-999d-4bf7-92a7-5bbb00a65a08/model.MODULE_6ca497e3654e530b8381+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/8e7029d0-999d-4bf7-92a7-5bbb00a65a08/model.MODULE_6ca497e3654e530b8381+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
.2024-01-17 22:59:23.000808:  25612  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:23.000810:  25612  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/6c754551-1265-4726-a9a9-1d7b2a9da878/model.MODULE_f141e0ac17571ddc13ee+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/6c754551-1265-4726-a9a9-1d7b2a9da878/model.MODULE_f141e0ac17571ddc13ee+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
.2024-01-17 22:59:24.000007:  25613  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:24.000009:  25613  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/e122c509-93da-49f3-beb8-7a42b892ce3f/model.MODULE_c96d1d30765bd80e7fd7+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/e122c509-93da-49f3-beb8-7a42b892ce3f/model.MODULE_c96d1d30765bd80e7fd7+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
2024-01-17 22:59:24.000042:  25614  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:24.000044:  25614  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/7f0f28e6-af8a-4294-844b-c2b695ac3e2e/model.MODULE_b42583089ebf9987f31e+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/7f0f28e6-af8a-4294-844b-c2b695ac3e2e/model.MODULE_b42583089ebf9987f31e+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
.2024-01-17 22:59:24.000082:  25615  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-01-17 22:59:24.000084:  25615  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/b0f4483e-c34e-406d-b4a8-4875ec75c99d/model.MODULE_9c16f577267ff0b098e9+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/b0f4483e-c34e-406d-b4a8-4875ec75c99d/model.MODULE_9c16f577267ff0b098e9+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']
......................................................................................................................................
Compiler status PASS

Compiler status PASS

Compiler status PASS
.....
Compiler status PASS
.
Compiler status PASS

2024-01-17 23:04:16.000447:  25608  ERROR ||NEURON_CC_WRAPPER||: Compilation failed for /tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.hlo.pb after 0 retries.

Compiler status PASS
.........
Compiler status PASS
....................................................
Compiler status PASS
..............................
Compiler status PASS
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/compiler.py", line 430, in compile
    self.build(tag=tag)
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/compiler.py", line 437, in build
    self.neff_bytes = compile_hlo_module(self.hlo_module, tag)
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/compiler.py", line 115, in compile_hlo_module
    neff_bytes = neuron_xla_compile(module_bytes, flags, input_format="hlo", platform_target="trn1",
  File "/opt/conda/lib/python3.10/site-packages/libneuronxla/__init__.py", line 38, in neuron_xla_compile
    _neuron_cc_wrapper.neuron_xla_compile(
  File "/opt/conda/lib/python3.10/site-packages/libneuronxla/neuron_cc_wrapper.py", line 268, in neuron_xla_compile
    ret = compile_with_cache(output, compile_cache, cache_key, execution_mode,
  File "/opt/conda/lib/python3.10/site-packages/libneuronxla/neuron_cc_wrapper.py", line 201, in compile_with_cache
    raise(e)
  File "/opt/conda/lib/python3.10/site-packages/libneuronxla/neuron_cc_wrapper.py", line 181, in compile_with_cache
    ret = call_neuron_compiler(
  File "/opt/conda/lib/python3.10/site-packages/libneuronxla/neuron_cc_wrapper.py", line 129, in call_neuron_compiler
    raise RuntimeError(f"Failed compilation with {cmd}: {res.stderr.decode()}")
RuntimeError: Failed compilation with ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']: 2024-01-17T23:04:16Z [LUR015]  Compiler generated too many instructions (6888787). This maybe due to a failure in parallelism extraction by the tensorizer. - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/space/compile.py", line 32, in <module>
    model = NeuronModelForCausalLM.from_pretrained(huggingface_path, export=True, **compiler_args, **input_shapes)
  File "/opt/conda/lib/python3.10/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/modeling_decoder.py", line 155, in _from_transformers
    return cls._from_pretrained(checkpoint_dir, config)
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/modeling_decoder.py", line 226, in _from_pretrained
    neuronx_model.to_neuron()
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/base.py", line 64, in to_neuron
    self.compile()
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/base.py", line 51, in compile
    kernel.neff_bytes = neff_bytes_futures[hash_hlo(kernel.hlo_module)].result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: Failed compilation with ['neuronx-cc', '--target=trn1', 'compile', '--framework', 'XLA', '/tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.hlo.pb', '--output', '/tmp/no-user/neuroncc_compile_workdir/b197ed2c-4f33-43db-b386-427e1d0a9b2a/model.MODULE_bff97bd0b592a177ea09+2c2d707e.neff', '--model-type=transformer', '--auto-cast=none', '--verbose=35']: 2024-01-17T23:04:16Z [LUR015]  Compiler generated too many instructions (6888787). This maybe due to a failure in parallelism extraction by the tensorizer. - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new
```

Host: inf2-48xlarge
env: 
```aws-neuronx-runtime-discovery==2.9
libneuronxla==0.5.570
neuronx-cc==2.12.54.0+f631c2365
neuronx-distributed==0.5.0
neuronx-hwm==2.12.0.0+422c9037c
optimum-neuron==0.0.15
torch-neuronx==1.13.1.1.12.1
torch-xla==1.13.1+torchneuronc
transformers-neuronx==0.9.474
```

here is the code
```
huggingface_path = "meta-llama/Llama-2-13b-chat-hf"
compiler_args = {"num_cores": num_cores, "auto_cast_type": 'fp16'}
input_shapes = {"batch_size": batch_size, "sequence_length": 2048}
model = NeuronModelForCausalLM.from_pretrained(huggingface_path, export=True, **compiler_args, **input_shapes)
```

**Comment by Sadden** [comment]
```
2024-01-18T00:08:08Z ERROR 32017 [/local/p4clients/pkgbuild-O8VDq/workspace/src/KaenaCompiler/neuronxcc/walrus/unroll/include/unroll/unroll.h:70]: Assertion failure: total_count < max_instruction_limit
```

```
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: ***************************************************************
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:  An Internal Compiler Error has occurred
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: ***************************************************************
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: 
2024-01-18T00:08:11Z USER 30010 [neuronxcc.driver.CommandDriver]: [LUR015]  Compiler generated too many instructions (6888787). This maybe due to a failure in parallelism extraction by the tensorizer. - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: 
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: Internal details:
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: Type: <class 'neuronxcc.driver.Exceptions.CompilerInternalError'>
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/CommandDriver.py", line 343, in neuronxcc.driver.CommandDriver.CommandDriver.run_subcommand
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1184, in neuronxcc.driver.commands.CompileCommand.CompileCommand.run
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1143, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1160, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/commands/CompileCommand.py", line 1163, in neuronxcc.driver.commands.CompileCommand.CompileCommand.runPipeline
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/Pipeline.py", line 30, in neuronxcc.driver.Pipeline.Pipeline.runSingleInput
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/jobs/WalrusDriver.py", line 306, in neuronxcc.driver.jobs.WalrusDriver.WalrusDriver.run
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/Job.py", line 344, in neuronxcc.driver.Job.SingleInputJob.run
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/Job.py", line 370, in neuronxcc.driver.Job.SingleInputJob.runOnState
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/jobs/WalrusDriver.py", line 882, in neuronxcc.driver.jobs.WalrusDriver.WalrusDriver.runSingleInput
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/jobs/WalrusDriver.py", line 487, in neuronxcc.driver.jobs.WalrusDriver.WalrusDriver.runWalrusDriver
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]: Cause:
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/jobs/WalrusDriver.py", line 479, in neuronxcc.driver.jobs.WalrusDriver.WalrusDriver.runWalrusDriver
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "neuronxcc/driver/Job.py", line 223, in neuronxcc.driver.Job.Job.shellCommand
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:   File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
2024-01-18T00:08:11Z ERROR 30010 [neuronxcc.driver.CommandDriver]:     raise CalledProcessError(retcode, process.args,
2024-01-18T00:08:11Z USER 30010 [neuronxcc.driver.CommandDriver]: 
```

**Comment by Sadden** [comment]
I suspect it's caused by batch size too large (I'm setting it as 8). But I just don't understand the number 6888787 and what is the max limit

**Comment by aws-donkrets** [comment]
Hi [Sadden](https://github.com/Sadden), The 6888787 number is the number of instructions the compiler generated for your model. As the ``too many instructions`` error message indicates, this maybe due to some data layout decisions in the compiler's optimizer/tensorizer. As a potential workaround, please try compiling your model using the "optlevel=1" ( aka -O1) compiler flag to see if that results in a successful compilation.

**Comment by mrnikwaws** [comment]
Closing since this issue is now 6 weeks old with no further discussion.

**Comment by hasadata** [comment]
[XTP002] Number of instructions (8658944) is over the threshold (5000000). Tiling could potentially do a better job. - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.

i tried setting optlevel=1 getting same results 
why do we have this limits models are getting larger by time
