### ISSUE TITLE
ValueError: Weight with shape torch.Size([8192, 1024]) cannot be sharded along dimension 1. This results in 25 weight partitions which cannot be distributed to 24 NeuronCores evenly

### ISSUE THREAD

**Issue by Sadden** [aws-neuron/aws-neuron-sdk#822]
Hi,
I got this error when trying to compile llama2-70b model into neuron. 

```
Loading checkpoint shards: 100%|█████████████████████████████████| 15/15 [14:00<00:00, 56.04s/it]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/modeling_decoder.py", line 155, in _from_transformers 
    return cls._from_pretrained(checkpoint_dir, config)
  File "/opt/conda/lib/python3.10/site-packages/optimum/neuron/modeling_decoder.py", line 226, in _from_pretrained   
    neuronx_model.to_neuron()
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/llama/model.py", line 124, in to_neuron
    new_layer.to_neuron()
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/decoder.py", line 643, in to_neuron
    self.attn_k_weight = maybe_shard_along(self.attn_k_weight, dim=1)
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/decoder.py", line 937, in shard_along
    return self.manipulator.shard_along(tensor, dim)
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/parallel.py", line 115, in shard_along
    return ops.parallel_to_nc(self.shard_along_on_cpu(tensor, dim))
  File "/opt/conda/lib/python3.10/site-packages/transformers_neuronx/parallel.py", line 107, in shard_along_on_cpu   
    raise ValueError(
ValueError: Weight with shape torch.Size([8192, 1024]) cannot be sharded along dimension 1. This results in 25 weight partitions which cannot be distributed to 24 NeuronCores evenly. To fix this issue either the model parameters or the `tp_degree` must be changed to allow the weight to be evenly split

```
Host: inf2-48xlarge
here is my code
```
compiler_args = {"num_cores": 24, "auto_cast_type": 'fp16'}
input_shapes = {"batch_size": 1, "sequence_length": 2048}
model = NeuronModelForCausalLM.from_pretrained(
    model_name,
    export=True,
    **compiler_args,
    **input_shapes)
```

The same config works for 13B. I wonder if it is caused by exceeding some memory limit.

**Comment by awsilya** [comment]
Hi @Sadden this is strange, we will try to reproduce.

**Comment by jluntamazon** [comment]
Can you validate if you have the latest release of optimum-neuron?

You should expect to see the following versions:
```
optimum-neuron                0.0.17
transformers-neuronx          0.9.474
```

If you are not on the latest version, you should be able to upgrade with:
```
pip install --extra-index-url=https://pip.repos.neuron.amazonaws.com/ --upgrade optimum-neuron[neuronx]
```

The reason you may be seeing this error is because [GQA support](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide.html#grouped-query-attention-gqa-support-beta) was added in the 2.16 release of the NeuronSDK. When using the old version of `transformers-neuronx`, this did not have support for the weight shapes used in Llama 70b

**Comment by jyang-aws** [comment]
Closing it for now. Please re-open the ticket if you still see issues. thanks!
