### ISSUE TITLE
Cannot complete "Compiling and Deploying HuggingFace Pretrained BERT on Trn1 or Inf2" exercise due to error

### ISSUE THREAD

**Issue by astanley-work** [aws-neuron/aws-neuron-sdk#839]
I am attempting to run the [Compiling and Deploying HuggingFace Pretrained BERT on Trn1 or Inf2](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/torch-neuronx/bert-base-cased-finetuned-mrpc-inference-on-trn1-tutorial.html#Compiling-and-Deploying-HuggingFace-Pretrained-BERT-on-Trn1-or-Inf2) on an Amazon inf2.xlarge EC2 instance running Amazon Linux 2023.

I have re-jigged the script to work in a normal python file instead of a Jupyter notebook (see source code below). However, when I attempt to run the code, I get an error that I can't find a solution to.

I have already completed the [installation process](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/pytorch/neuronx/amazon-linux/torch-neuronx-al2.html#setup-torch-neuronx-al2) as instructed and verified that everything works as intended.

CODE:
import torch
import torch_neuronx
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import transformers

def encode(tokenizer, *inputs, max_length=128, batch_size=1):
    tokens = tokenizer.encode_plus(
        *inputs,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors="pt"
    )
    return (
        # .repeat_interleave doubles the inputs (e.g. [1,2,3] becomes [1,1,2,2,3,3])
        torch.repeat_interleave(tokens['input_ids'], batch_size, 0),
        torch.repeat_interleave(tokens['attention_mask'], batch_size, 0),
        torch.repeat_interleave(tokens['token_type_ids'], batch_size, 0),
    )

name = "bert-base-cased-finetuned-mrpc"
tokenizer = AutoTokenizer.from_pretrained(name)
model = AutoModelForSequenceClassification.from_pretrained(name, torchscript=True)

sequence_0 = "The company HuggingFace is based in New York City"
sequence_1 = "Apples are especially bad for your health"
sequence_2 = "HuggingFace's headquarters are situated in Manhattan"

paraphrase = encode(tokenizer, sequence_0, sequence_2)
not_paraphrase = encode(tokenizer, sequence_0, sequence_1)

cpu_paraphrase_logits = model(*paraphrase)[0]
cpu_not_paraphrase_logits = model(*not_paraphrase)[0]

model_neuron = torch_neuronx.trace(model, paraphrase)

neuron_paraphrase_logits = model_neuron(*paraphrase)[0]
neuron_not_paraphrase_logits = model_neuron(*not_paraphrase)[0]

print('CPU paraphrase logits:        ', cpu_paraphrase_logits.detach().numpy())
print('Neuron paraphrase logits:    ', neuron_paraphrase_logits.detach().numpy())
print('CPU not-paraphrase logits:    ', cpu_not_paraphrase_logits.detach().numpy())
print('Neuron not-paraphrase logits: ', neuron_not_paraphrase_logits.detach().numpy())

ERROR:
hf-bert-tutorial-cpu-vs-neuron.py(aws_neuron_venv_pytorch) sh-5.2$ python hf-bert-tutorial-cpu-vs-neuron.py
Traceback (most recent call last):  File "/home/ssm-user/bert-tutorial/hf-bert-tutorial-cpu-vs-neuron.py", line 1, in <module>
    import torch  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/__init__.py", line 1504, in <module>
    from . import masked
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/masked/__init__.py", line 3, in <module>    from ._ops import (
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/masked/_ops.py", line 11, in <module>    from torch._prims_common import corresponding_real_dtype
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/_prims_common/__init__.py", line 23, in <module>    import sympy
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/sympy/__init__.py", line 30, in <module>    from sympy.core.cache import lazy_function
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/sympy/core/__init__.py", line 9, in <module>    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/sympy/core/expr.py", line 4159, in <module>    from .mul import Mul
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/sympy/core/mul.py", line 2193, in <module>    from .numbers import Rational
  File "/home/ssm-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/sympy/core/numbers.py", line 4567, in <module>    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
AttributeError: module 'mpmath' has no attribute 'rational'

**Comment by astanley-work** [comment]
Issue resolved - needed to change version of mpmath by running pip install mpmath==1.3.0 and it worked.
