### ISSUE TITLE
RuntimeError when running llama2_inference.ipynb

### ISSUE THREAD

**Issue by crane-sapia** [aws-neuron/aws-neuron-sdk#849]
Hi all,

I was following the [tut here](https://github.com/aws-neuron/aws-neuron-sdk/blob/master/src/examples/pytorch/neuronx_distributed/llama/llama2_inference.ipynb) to run the trace on llama2-7B. However, when running this line in **Trace the model** section:
```python
runner.trace(traced_model_path=traced_model_path,
             tp_degree=tp_degree,
             batch_size=batch_size,
             max_context_length=max_context_length,
             max_new_tokens=max_new_tokens)
```
I encountered the following error:
<details>
<summary><b>Error Information</b></summary>

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib64/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/neuronx-distributed/examples/inference/llama2_inference.py", line 14, in <module>
    runner.trace(
  File "/home/ec2-user/neuronx-distributed/examples/inference/runner.py", line 183, in trace
    traced_model = parallel_model_trace(
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/neuronx_distributed/trace/trace.py", line 144, in parallel_model_trace
    manager = ctx.Manager()
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/lib64/python3.9/multiprocessing/managers.py", line 554, in start
    self._process.start()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/home/ec2-user/neuronx-distributed/examples/inference/llama2_inference.py", line 14, in <module>
    runner.trace(
  File "/home/ec2-user/neuronx-distributed/examples/inference/runner.py", line 183, in trace
    traced_model = parallel_model_trace(
  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/neuronx_distributed/trace/trace.py", line 144, in parallel_model_trace
    manager = ctx.Manager()
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/lib64/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/usr/lib64/python3.9/multiprocessing/connection.py", line 254, in recv
    buf = self._recv_bytes()
  File "/usr/lib64/python3.9/multiprocessing/connection.py", line 418, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib64/python3.9/multiprocessing/connection.py", line 387, in _recv
    raise EOFError
EOFError
```
</details>

Can anyone give some hints on how to address this problem?

**Comment by aws-taylor** [comment]
Hello @crane-sapia,

 One of our engineers is working to reproduce the issue. We'll update this issue once we've got more information.
 
 -Taylor

**Comment by matkle** [comment]
Hi @aws-taylor, any updates on this? Thx!
