### ISSUE TITLE
Error: "Backward sending grads, but get None"

### ISSUE THREAD

**Issue by wfckl789** [aws-neuron/aws-neuron-sdk#864]
Hi, I'm encountering an error **`Backward sending grads, but get None`** raised by the bwd_postprocess_task() during the model training. It seems that tensor will lose its requires_grad property after  passing into this source code **`tensor_recv_next = xm.all_reduce(xm.REDUCE_SUM, tensor_recv_next, groups=groups)`** in `src/neuronx_distributed/pipeline/comm.py`.

This error also happens when I tried the demo [Training Llama-2-13B/70B with Tensor Parallelism and Pipeline Parallelism (neuronx-distributed )](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/neuronx-distributed/tutorials/training_llama2_tp_pp.html#) provided by the neuron document.

This is the log and compiler info:
[simple.log](https://github.com/aws-neuron/aws-neuron-sdk/files/14895876/simple.log)

```
`2024-04-01 06:59:57.748428: W torch_xla/csrc/lowering_context.cpp:71] No custom opname metadata! op_type=xla___op_TransferWithStaticRingTransfer
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/pipeline/model.py", line 982, in _exec_schedule
    self._exec_instr()
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/pipeline/model.py", line 920, in _bwd_postprocess_task
    raise RuntimeError(rmsg("Backward sending grads, but get None"))
RuntimeError: [rank_8_pp1_tp0_dp0] Backward sending grads, but get None
Traceback (most recent call last):
  File "run_simple_model_nxd.py", line 289, in <module>
    _mp_fn(0, args)
  File "run_simple_model_nxd.py", line 225, in _mp_fn
    train_simple_model(args)
  File "run_simple_model_nxd.py", line 188, in train_simple_model
    loss = model.run_train(
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/trainer/model.py", line 25, in run_train
    return self.module.run_train(*args, **kwargs)
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/pipeline/model.py", line 542, in run_train
    loss = self._run_train(**kwargs)
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/pipeline/model.py", line 561, in _run_train
    self._exec_schedule(self.train_scheduler)
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/pipeline/model.py", line 982, in _exec_schedule
    self._exec_instr()
  File "/home/ubuntu/qwb_venv_pytorch/lib/python3.8/site-packages/neuronx_distributed/pipeline/model.py", line 920, in _bwd_postprocess_task
    raise RuntimeError(rmsg("Backward sending grads, but get None"))
RuntimeError: [rank_24_pp3_tp0_dp0] Backward sending grads, but get None`
```

Package version:
![image](https://github.com/aws-neuron/aws-neuron-sdk/assets/42508752/041656c0-0dc1-4c51-9624-87ca6c5aff0a)
![image](https://github.com/aws-neuron/aws-neuron-sdk/assets/42508752/1ad47fed-42e4-4876-b772-b1ba23f3c0e9)
![image](https://github.com/aws-neuron/aws-neuron-sdk/assets/42508752/0337c58c-8c6d-4b2c-b221-778aa36f95db)

Other system details:
instance: Trn1
OS: Ubuntu 20.04

If you need other information, please let me konw. Thanks.

**Comment by jluntamazon** [comment]
I am closing this issue in favor of:
https://github.com/aws-neuron/neuronx-distributed/issues/19
We will track that ticket until resolution instead.
