### ISSUE TITLE
Input tensor is not an XLA tensor: CPUFloatType  while using crf.decode function

### ISSUE THREAD

**Issue by PrateekAg1511** [aws-neuron/aws-neuron-sdk#901]
Hi,

I am trying to trace crf.decode function in ml.inf2.8xlarge instance.

Here is the code I am trying to run.

def tags(output , mask):
    a = model.crf.decode(output , mask)
    a = torch.FloatTensor(a)
    return (a)

inputs = output , mask

model_crf = torch_neuronx.trace(tags, inputs)

Error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[38], line 1
----> 1 model_crf = torch_neuronx.trace(tags, inputs)

File ~/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:556, in trace(func, example_inputs, input_output_aliases, compiler_workdir, compiler_args, partitioner_config, inline_weights_to_neff, *_, **kwargs)
    551     return torch_neuronx.partition(
    552         func, example_inputs, **(partitioner_config.__dict__)
    553     )
    555 with context:
--> 556     neff_filename, metaneff, flattener, packer, weights = _trace(
    557         func,
    558         example_inputs,
    559         states,
    560         input_output_aliases,
    561         compiler_workdir,
    562         compiler_args,
    563         inline_weights_to_neff,
    564     )
    565     return create_neuron_model(
    566         neff_filename,
    567         metaneff,
   (...)
    572         weights,
    573     )

File ~/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:614, in _trace(func, example_inputs, states, input_output_aliases, compiler_workdir, compiler_args, inline_weights_to_neff)
    597 def _trace(
    598     func: Union[Callable, torch.nn.Module],
    599     example_inputs: Any,
   (...)
    605 ) -> Union[str, str, structure.Flattener, structure.Packer]:
    606     # Convert the function to a HloProto message
    607     (
    608         hlo,
    609         constant_parameter_tensors,
    610         flattener,
    611         packer,
    612         metaneff,
    613         weights,
--> 614     ) = generate_hlo(
    615         func,
    616         example_inputs,
    617         states=states,
    618         input_output_aliases=input_output_aliases,
    619         inline_weights_to_neff=inline_weights_to_neff
    620     )
    622     # Call neuronx-cc to generate neff
    623     neff_filename = generate_neff(
    624         hlo,
    625         constant_parameter_tensors,
   (...)
    628         inline_weights_to_neff=inline_weights_to_neff,
    629     )

File ~/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/trace.py:404, in generate_hlo(func, example_inputs, states, input_output_aliases, inline_weights_to_neff)
    389 def generate_hlo(
    390     func: Union[Callable, torch.nn.Module],
    391     example_inputs: Any,
   (...)
    394     inline_weights_to_neff: bool = True
    395 ):
    396     with torch_neuronx.contexts.mock_neuron_cores(), revert_device_placement(func):
    397         (
    398             hlo,
    399             input_parameter_names,
    400             constant_parameter_tensors,
    401             flattener,
    402             packer,
    403             updated_input_output_aliases,
--> 404         ) = xla_trace(
    405             func,
    406             example_inputs,
    407             states,
    408             input_output_aliases,
    409         )
    411     # make sure that hlo dtype and torch dtype match
    412     coerce_parameter_dtypes(hlo, constant_parameter_tensors)

File ~/aws_neuron_venv_pytorch/lib64/python3.8/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:133, in xla_trace(func, example_inputs, states, input_output_aliases)
    131 # Lower the HLO graph
    132 context = torch_xla._XLAC.lowering.LoweringContext()
--> 133 context.build(tensors)
    135 # Determine which HloModule parameters should be inlined (ie. constants,
    136 # parameters, buffers). This should NOT include the example inputs.
    137 parameters = context.parameter_id_tensor_mapping()

RuntimeError: torch_xla/csrc/aten_xla_bridge.cpp:73 : Check failed: xtensor 
*** Begin stack trace ***
	tsl::CurrentStackTrace()
	torch_xla::bridge::GetXlaTensor(at::Tensor const&)
	
	
	
	
	PyCFunction_Call
	_PyObject_MakeTpCall
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	
	
	_PyObject_MakeTpCall
	
	
	PyVectorcall_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	_start
*** End stack trace ***
Input tensor is not an XLA tensor: CPUFloatType

I am have been to find a solution for it but nothing worked so far. Please help!

**Comment by tombettany** [comment]
We had a similar problem when trying to run `torch_neuronx.trace()` and it was because the output of our model had the device set for `cpu` rather than an XLA device. Solution we found was just to [set `FloatTensor(a, device=torch_xla.core.xla_model.xla_device())` when creating the tensor](https://pytorch.org/xla/release/2.3/index.html) to set the device type. Alternatively you can run `.to(torch_xla.core.xla_model.xla_device())` on the output:

```python
import torch_xla.core.xla_model as xm

def tags(output , mask):
    return model.crf.decode(output, mask).to(m.xla_device())

...
```

Presumably you could set the device type on the input tensor instead but we did have issues with this on our model.

Hopefully this gets you a little bit further towards solving the problem.

**Comment by jluntamazon** [comment]
Would you be able to give more details about the model you are trying to trace? If there is a minimal open source reproduction of the error you are encountering, we can try to help you solve the problem.

The warning you are running into indicates that the output of the model does not appear to depend on the inputs. This can happen when the output is calculated entirely based on tensors which are newly constructed within the forward function. This likely happens due to the implementation of the `model.crf.decode` method.

**Comment by PrateekAg1511** [comment]
@jluntamazon Here is the minimal open source reproduction of the error:

import torch
from torchcrf import CRF
num_tags = 184
model = CRF(num_tags)

emissions = torch.rand([1,60,184])
mask = torch.ones([1,60], dtype=torch.uint8)

def decode_fn(emissions , mask):
    a = model.decode(emissions , mask)
    a = torch.Tensor(a)
    a = a.to(xm.xla_device())
    return (a)

inputs_crf = emissions , mask

trace_crf = torch_neuronx.trace(decode_fn , inputs_crf)

After running trace, I get the waring message for both inputs. 


"/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:144: UserWarning: Received an input tensor that was unused. Tensor will be ignored. (index=0, shape=torch.Size([1, 60, 184]), dtype=torch.float32)
  warnings.warn(
//aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:144: UserWarning: Received an input tensor that was unused. Tensor will be ignored. (index=1, shape=torch.Size([1, 60]), dtype=torch.uint8)
  warnings.warn( "

**Comment by elghayatiloubna** [comment]
Did anyone find a solution to this problem? I'm encountering the same error when I try to trace a DETR model

**Comment by jeffhataws** [comment]
By following https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/programming-guide/inference/trace-vs-xla-lazytensor.html#tensor-materialization-during-tracing , I see the following error indicating some tensor materialization that causes graph breakage/execution:

```
Unexpected Execution Analysis: ================================================================================
Unexpected Execution Analysis: Compilation Cause
Unexpected Execution Analysis:   most likely user code trying to access tensor value before mark_step
Unexpected Execution Analysis: Graph Info: 
Unexpected Execution Analysis:   Graph Hash: 80106c1ddbb434ea6d1efb6597d97d6b
Unexpected Execution Analysis:   Number of Graph Inputs: 1
Unexpected Execution Analysis:   Number of Graph Outputs: 1
Unexpected Execution Analysis: Python Frame Triggered Execution: 
Unexpected Execution Analysis:   _validate (/home/ubuntu/aws_neuron_venv_pt27_r224/lib/python3.10/site-packages/torchcrf/__init__.py:166)
Unexpected Execution Analysis:   decode (/home/ubuntu/aws_neuron_venv_pt27_r224/lib/python3.10/site-packages/torchcrf/__init__.py:131)
Unexpected Execution Analysis:   <module> (/home/ubuntu/test_crf.py:17)
Unexpected Execution Analysis: --------------------------------------------------------------------------------
Unexpected Execution Analysis: ================================================================================
Traceback (most recent call last):
  File "/home/ubuntu/test_crf.py", line 17, in <module>
    print(model.decode(emissions , mask))
  File "/home/ubuntu/aws_neuron_venv_pt27_r224/lib/python3.10/site-packages/torchcrf/__init__.py", line 131, in decode
    self._validate(emissions, mask=mask)
  File "/home/ubuntu/aws_neuron_venv_pt27_r224/lib/python3.10/site-packages/torchcrf/__init__.py", line 166, in _validate
    if not no_empty_seq and not no_empty_seq_bf:
RuntimeError: torch_xla/csrc/debug_util.cpp:413 : Unexpected execution happens inside the compiled function, exiting
```

If you can clear all these to be static, it may help.

For now, you can try just executing with JIT compilation (comment out ``torch_xla._XLAC._set_allow_execution(False)`` , although there are many graphs created due to the breaks above:

```
import torch
from torchcrf import CRF
import torch_xla.core.xla_model as xm
import torch_neuronx
import torch_xla
#torch_xla._XLAC._set_allow_execution(False)

num_tags = 184
model = CRF(num_tags).to("xla")

for i in range(5):
    emissions = torch.rand([1,10,num_tags]).to("xla")
    mask = torch.ones([1,10], dtype=torch.uint8).to("xla")
    print(model.decode(emissions , mask))

```

```
...(removed some messages of cached neff loading)

2025-10-03 17:23:27.000323:  219854  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.20.9961.0+0acef03a/MODULE_47790846
10248224103+e30acd3a/model.neff                                                                                                                                     
2025-10-03 17:23:27.000341:  219854  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.20.9961.0+0acef03a/MODULE_13478590
783761056696+e30acd3a/model.neff                                                                                                                                    
2025-10-03 17:23:27.000360:  219854  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.20.9961.0+0acef03a/MODULE_15383675
708548619470+e30acd3a/model.neff                                                                                                                                    
2025-10-03 17:23:27.000378:  219854  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.20.9961.0+0acef03a/MODULE_67862420
53365739854+e30acd3a/model.neff                                                                                                                                     
2025-10-03 17:23:27.000397:  219854  INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /var/tmp/neuron-compile-cache/neuronxcc-2.20.9961.0+0acef03a/MODULE_10587945
7164113302+e30acd3a/model.neff                                                                                                                                      
[[83], [5], [182], [145], [56], [49], [5], [143], [9], [74]]
[[135], [122], [130], [122], [56], [49], [83], [156], [130], [126]]                                                                                                 
[[122], [130], [75], [70], [135], [13], [156], [156], [48], [5]]
[[107], [145], [26], [13], [56], [122], [63], [56], [155], [180]]            
[[135], [13], [56], [5], [143], [153], [126], [56], [138], [56]]
(aws_neuron_venv_pt27_r224) ubuntu@ip-10-4-245-26:~$ vi test_crf.py                
(aws_neuron_venv_pt27_r224) ubuntu@ip-10-4-245-26:~$ python test_crf.py

```

Closing the ticket for now. Feel free to reopen if you still need more support.
